Repository koordinator-sh/koordinator, pull requests merged in 2022-10, with the labels that each got.

#662 koordlet: unset cfs_quota for LSR/LSE pods
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/runtimeproxy/resexecutor/cri/utils.go
  pkg/util/pod.go
  pkg/util/pod_qos_utils.go
  pkg/util/pod_qos_utils_test.go
  pkg/util/pod_test.go
Labels: lgtm, approved, size/XL

#660 koord-manager: modify quota-webhook
  cmd/koord-manager/main.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
  pkg/webhook/elasticquota/mutating/mutating_handle_test.go
  pkg/webhook/elasticquota/mutating/mutating_handler.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
  pkg/webhook/elasticquota/validating/validating_handler.go
  pkg/webhook/elasticquota/validating/validating_handler_test.go
  pkg/webhook/pod/validating/validating_handler.go
  pkg/webhook/pod/validating/validating_handler_test.go
Labels: lgtm, approved, size/L

#673 slo-controller report koordinator-gpu resource dimension
  pkg/slo-controller/noderesource/noderesource.go
Labels: size/XS, lgtm, approved

#680 koordlet: fix cpuset hook for unset cfs
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
Labels: lgtm, approved, size/M

#675 koord-scheduler: modify cpu and memory quantity formats and scales
  apis/scheduling/config/v1beta2/defaults.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
  pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Labels: lgtm, approved, size/L

#683 fix gang by annotation create pg crd fail
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
Labels: lgtm, approved, size/M

#687 koordlet: enable group identity by sysctl when cpu qos enabled
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/util/system/system_file.go
  pkg/util/system/system_file_test.go
  pkg/util/system/util_test_tool.go
Labels: lgtm, approved, size/XL

#686 koord-scheduler: add GetQuotaSummaries/GetGangSummaries debug API
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/plugin_service.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/plugin_service.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: lgtm, approved, size/L

#688 koordlet: supply cpushare inject logic in runtimehooks protocols
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
Labels: lgtm, approved, size/M

#690 koord-scheduler: abstract nodenumaresource plugin allowUseCPUSet
  pkg/scheduler/plugins/nodenumaresource/plugin.go
Labels: size/XS, lgtm, approved

#694 chore: update ClusterColocationProfile UT
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
Labels: size/XS, lgtm, approved

#695 koord-scheduler: fix deviceshare onPodAdd when its device is not loaded
  pkg/scheduler/plugins/deviceshare/pod_handler.go
Labels: lgtm, approved, size/S

#676 koordlet: divide states informer into plugins
  pkg/koordlet/koordlet.go
  pkg/koordlet/statesinformer/callback_runner.go
  pkg/koordlet/statesinformer/callback_runner_test.go
  pkg/koordlet/statesinformer/registry.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/koordlet/statesinformer/states_node.go
  pkg/koordlet/statesinformer/states_node_test.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/koordlet/statesinformer/states_nodeslo_test.go
  pkg/koordlet/statesinformer/states_pod.go
  pkg/koordlet/statesinformer/states_pods.go
  pkg/koordlet/statesinformer/states_pods_test.go
Labels: size/XXL, lgtm, approved

#699 apis: refactor scheduling config layout for release apis
  apis/extension/node.go
  apis/extension/resource.go
  cmd/koord-scheduler/main.go
  hack/update-codegen.sh
  pkg/scheduler/apis/config/doc.go
  pkg/scheduler/apis/config/register.go
  pkg/scheduler/apis/config/scheme/scheme.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/doc.go
  pkg/scheduler/apis/config/v1beta2/register.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.defaults.go
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/plugins/batchresource/batch_resource.go
  pkg/scheduler/plugins/batchresource/batch_resource_test.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_manager.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/L

#700 chore: use openkruise/kruise-api instead of openkruise/kruise
  cmd/koord-descheduler/app/options/scheme.go
  go.mod
  go.sum
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
Labels: lgtm, approved, size/M

#702 fix pleg init err
  pkg/koordlet/pleg/pleg.go
Labels: size/XS, lgtm, approved

#706 Fix #705 for the error of "io/ioutil" is deprecated
  pkg/util/system/common.go
  pkg/util/system/system_file.go
Labels: lgtm, approved, size/S

#710 koord-scheduler: fix nodeNUMAResource allowUseCPUSet
  pkg/scheduler/plugins/nodenumaresource/plugin.go
Labels: lgtm, approved, size/S

#709 koord-scheduler: fix NodeNUMAResource sortCPUsByRefCount
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
Labels: lgtm, approved, size/M

#713 fix pleg ut for darwin
  pkg/koordlet/pleg/pleg.go
  pkg/koordlet/pleg/watcher.go
  pkg/koordlet/pleg/watcher_other.go
Labels: lgtm, approved, size/S

#602 Qos manager framework
  cmd/koordlet/main.go
  pkg/features/koordlet_features.go
  pkg/koordlet/common/reason/reason.go
  pkg/koordlet/common/testutil/k8s.go
  pkg/koordlet/common/types/constants.go
  pkg/koordlet/common/utils/containers.go
  pkg/koordlet/common/utils/pod.go
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/qosmanager/config/config.go
  pkg/koordlet/qosmanager/config/config_test.go
  pkg/koordlet/qosmanager/k8s/k8s.go
  pkg/koordlet/qosmanager/manager.go
  pkg/koordlet/qosmanager/manager_test.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query_test.go
  pkg/koordlet/qosmanager/plugins/context.go
  pkg/koordlet/qosmanager/plugins/plugin.go
Labels: size/XXL, lgtm, approved

#715 add webhook and node topo feature gates control
  cmd/koord-manager/main.go
  pkg/features/features.go
  pkg/features/koordlet_features.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
Labels: lgtm, approved, size/M

#719 reducing nesting
  pkg/koordlet/executor/resource_update_executor.go
  pkg/koordlet/resmanager/cpu_suppress.go
Labels: lgtm, approved, size/M

#725 fix typo in pkg/koordlet/metriccache/api.go
  pkg/koordlet/metriccache/api.go
Labels: size/XS, lgtm, approved

#721 koord-scheduler: fix failed scheduling since missing CPUTopology
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: size/XS, lgtm, approved

#704 koord-scheduler: make Coscheduling/ElasticQuota/DeviceShare plugins more flexible
  apis/extension/elastic_quota.go
  apis/extension/scheduling.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/util/gang_helper.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/pod_handler.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/deviceshare/utils_test.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/webhook/elasticquota/pod_check.go
Labels: lgtm, approved, size/L

#681 koord-scheduler: optimize the use of GroupQuotaManager's hierarchyLock
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_service.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/pod_handler.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Labels: lgtm, approved, size/L

#732 koordlet: fix throw Can't get node error during initialization
  pkg/koordlet/koordlet.go
Labels: size/XS, lgtm, approved

#689 bugfix: append origin env when inject gpu env
  pkg/koordlet/runtimehooks/hooks/gpu/gpu.go
  pkg/koordlet/runtimehooks/hooks/gpu/gpu_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/protocol_test.go
  pkg/koordlet/runtimehooks/proxyserver/service.go
Labels: lgtm, approved, size/M

#731 apis: fix resctrl qos defaults
  apis/slo/v1alpha1/nodeslo_types.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Labels: lgtm, approved, size/M

#653 making code easier to read
  pkg/scheduler/plugins/coscheduling/controller/podgroup.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/preempt.go
Labels: lgtm, approved, size/L

#651 code collation
  pkg/scheduler/plugins/compatibledefaultpreemption/preemption.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
Labels: lgtm, approved, size/M

#734 koord-scheduler: fix the lack of gang function conversion
  apis/extension/scheduling.go
Labels: size/XS, lgtm, approved

#735 fix:exit the loop when enough pods have been found to be evicted
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/memory_evict.go
Labels: lgtm, approved, size/M

#724 fix: delete unused return args
  pkg/koordlet/executor/resource_update_executor.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
Labels: lgtm, approved, size/S

#736 chore: update make deploy
  Makefile
  PROJECT
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/scheduling.sigs.k8s.io_elasticquotas.yaml
  config/crd/bases/scheduling.sigs.k8s.io_podgroups.yaml
  config/crd/bases/topology.node.k8s.io_noderesourcetopologies.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/descheduler-config.yaml
  config/manager/descheduler.yaml
  config/manager/koord-batch.yaml
  config/manager/koord-free.yaml
  config/manager/koord-mid.yaml
  config/manager/koord-prod.yaml
  config/manager/koordlet.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/scheduler-config.yaml
  config/manager/scheduler.yaml
  config/manager/slo-controller-config.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/descheduler_role.yaml
  config/rbac/descheduler_role_binding.yaml
  config/rbac/koordlet.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/scheduler_role.yaml
  config/rbac/scheduler_role_binding.yaml
  config/rbac/service_account.yaml
  config/webhook/manifests.yaml
  hack/kustomize.sh
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/webhook/elasticquota/mutating/webhooks.go
  pkg/webhook/elasticquota/validating/validating_handler.go
  pkg/webhook/elasticquota/validating/webhooks.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
Labels: size/XXL, lgtm, approved

#738 chore: fix image registry in Kustomization
  config/manager/kustomization.yaml
Labels: lgtm, approved, size/M

#737 koordlet: fix for cpu suppress when node topology reporting disabled
  pkg/koordlet/statesinformer/kubelet_stub_test.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
Labels: lgtm, approved, size/XL

#741 koordlet: rm kubebuilder default tag for ResourceThresholdStrategy
  apis/slo/v1alpha1/nodeslo_types.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Labels: size/XS, lgtm, approved

#740 support webhook debug api
  pkg/webhook/add_quota.go
  pkg/webhook/api_debug_server.go
  pkg/webhook/elasticquota/plugin_check_quota_meta_validate.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/elasticquota/validating/validating_handler.go
  pkg/webhook/server.go
Labels: lgtm, approved, size/M

#744 fix:failed to start nodeTopoInformer when tcp6 is not find in node
  pkg/util/system/common_linux.go
Labels: lgtm, approved, size/S

#718 RuntimeProxy: Support hook server deployed by k8s pod
  cmd/koord-runtime-proxy/main.go
  cmd/koord-runtime-proxy/options/options.go
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/container_test.go
  pkg/runtimeproxy/resexecutor/cri/pod.go
  pkg/runtimeproxy/resexecutor/cri/utils.go
  pkg/runtimeproxy/resexecutor/resource_executor.go
  pkg/runtimeproxy/server/cri/criserver.go
  pkg/runtimeproxy/utils/utils.go
Labels: lgtm, approved, size/L

#747 koordlet: add pprof flag
  cmd/koordlet/main.go
  cmd/koordlet/options/options.go
  pkg/tools/cache/expiration_cache.go
Labels: lgtm, approved, size/S

#745 koordlet report gpu model and driver version
  apis/extension/resource.go
  pkg/koordlet/statesinformer/states_device_linux.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
  pkg/koordlet/statesinformer/states_device_unsupported.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_test.go
Labels: lgtm, approved, size/L

#622 koordlet: CPI collector for Interference Detection
  go.mod
  go.sum
  pkg/features/koordlet_features.go
  pkg/koordlet/metriccache/api.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/metriccache/storage.go
  pkg/koordlet/metriccache/storage_tables.go
  pkg/koordlet/metriccache/storage_test.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/config.go
  pkg/koordlet/metricsadvisor/config_test.go
  pkg/koordlet/metricsadvisor/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
  pkg/koordlet/metricsadvisor/performance_collector_unsupported.go
  pkg/util/container.go
  pkg/util/container_test.go
  pkg/util/perf/perf_linux.go
  pkg/util/perf/perf_linux_test.go
  pkg/util/perf/perf_unsupported.go
  pkg/util/stat.go
  pkg/util/stat_test.go
Labels: size/XXL, lgtm, approved

#729 koord-scheduler: optimize ElasticQuota plugin's update logic
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
Labels: lgtm, approved, size/L

#750 fix: error to init option(SysRootDir)
  pkg/util/system/config.go
Labels: size/XS, lgtm, approved

#751 apis: change the required fields in ClusterColocationProfile to optional
  apis/config/v1alpha1/cluster_colocation_profile_types.go
  config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
Labels: size/XS, lgtm, approved

#753 fix: remove unnecessary reassignments
  pkg/util/system/config.go
Labels: size/XS, lgtm, approved

#754 RuntimeProxy: return err when FailurePolicyType set to Fail
  pkg/runtimeproxy/client/hookclient.go
  pkg/runtimeproxy/client/mock/mockhookclient.go
  pkg/runtimeproxy/config/config.go
  pkg/runtimeproxy/config/config_manager.go
  pkg/runtimeproxy/config/mock/mockconfig.go
  pkg/runtimeproxy/dispatcher/dispatcher.go
  pkg/runtimeproxy/dispatcher/dispatcher_test.go
  pkg/runtimeproxy/mock/runtimeproxy-client.go
  pkg/runtimeproxy/server/cri/criserver.go
  pkg/runtimeproxy/server/docker/handler.go
Labels: lgtm, approved, size/XL

#761 koordlet: fix kubelet pid not found in tcp4 socks
  pkg/util/system/common_linux.go
Labels: lgtm, approved, size/S

#749 koordlet: add gc logs for metric cache
  go.mod
  go.sum
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/storage.go
  pkg/koordlet/metriccache/storage_test.go
  pkg/koordlet/metricsadvisor/collector.go
Labels: lgtm, approved, size/L
