Repository koordinator-sh/koordinator, pull requests merged in 2022-03, with the labels that each got.

#11 ✨ Introduce LSE into QoS Class
  apis/extension/qos.go
  pkg/slo-controller/config/constants.go
  pkg/slo-controller/noderesource/configmap_event_handler.go
Labels: lgtm, approved, size/S

#13 add spark example and remove deploy dir
  examples/nginx/nginx.yaml
  examples/spark-jobs/cluster-colocation-profile.yaml
  examples/spark-jobs/service-account.yaml
  examples/spark-jobs/spark-pi.yaml
  examples/spark-jobs/spark-tc-complex.yaml
  examples/spark-jobs/spark-tc-simple.yaml
  examples/spark-operator-chart/.helmignore
  examples/spark-operator-chart/Chart.yaml
  examples/spark-operator-chart/README.md
  examples/spark-operator-chart/README.md.gotmpl
  examples/spark-operator-chart/ci/ci-values.yaml
  examples/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  examples/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  examples/spark-operator-chart/templates/_helpers.tpl
  examples/spark-operator-chart/templates/deployment.yaml
  examples/spark-operator-chart/templates/prometheus-podmonitor.yaml
  examples/spark-operator-chart/templates/rbac.yaml
  examples/spark-operator-chart/templates/serviceaccount.yaml
  examples/spark-operator-chart/templates/spark-rbac.yaml
  examples/spark-operator-chart/templates/spark-serviceaccount.yaml
  examples/spark-operator-chart/templates/webhook-cleanup-job.yaml
  examples/spark-operator-chart/templates/webhook-init-job.yaml
  examples/spark-operator-chart/templates/webhook-service.yaml
  examples/spark-operator-chart/values.yaml
Labels: size/XXL, lgtm, approved

#14 add node slo crd
  Makefile
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  hack/fix_crd_plural.sh
  pkg/client/clientset/versioned/typed/slo/v1alpha1/fake/fake_nodeslo.go
  pkg/client/clientset/versioned/typed/slo/v1alpha1/fake/fake_slo_client.go
  pkg/client/clientset/versioned/typed/slo/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/slo/v1alpha1/nodeslo.go
  pkg/client/clientset/versioned/typed/slo/v1alpha1/slo_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/slo/v1alpha1/interface.go
  pkg/client/informers/externalversions/slo/v1alpha1/nodeslo.go
  pkg/client/listers/slo/v1alpha1/expansion_generated.go
  pkg/client/listers/slo/v1alpha1/nodeslo.go
Labels: lgtm, approved, size/XL

#15 support config QoSClass/PriorityClass/ColocationPriority in Profile
  apis/config/v1alpha1/cluster_colocation_profile_types.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/util/pod.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
  pkg/webhook/pod/validating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/L

#16 remove duplicate function like Int64Ptr
  pkg/slo-controller/config/config.go
  pkg/util/utils.go
Labels: lgtm, size/M

#17 Add nodeslo controller
  Makefile
  cmd/koord-manager/main.go
  go.mod
  pkg/koordlet/koordlet.go
  pkg/koordlet/reporter/reporter_test.go
  pkg/koordlet/util/node.go
  pkg/koordlet/util/pod.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/constants.go
  pkg/slo-controller/nodemetric/node_event_handler.go
  pkg/slo-controller/noderesource/configmap_event_handler.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
Labels: size/XL

#18 🐛 Fix typo in ClusterColocationProfile
  apis/config/v1alpha1/cluster_colocation_profile_types.go
  config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
Labels: lgtm, size/S

#21 align the units of koordinator.sh/batch-cpu
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/S

#20 Add resource manager for koordlet
  pkg/features/koordlet_features.go
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/resmanager/config.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/metrics_query.go
  pkg/koordlet/resmanager/reason.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/util/util.go
  pkg/koordlet/util/util_test.go
  pkg/util/config.go
Labels: do-not-merge/hold, size/XXL, lgtm, approved

#22 rename koordinator priority class name
  apis/config/v1alpha1/cluster_colocation_profile_types.go
  apis/extension/priority.go
  config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
  pkg/webhook/pod/validating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/M

#23 add quick start link to website
  README.md
Labels: size/XS, lgtm, approved

#25 change batch priority value range
  apis/extension/priority.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
Labels: size/XS, lgtm, approved

#27 add best practices in Quick Start section
  README.md
Labels: size/XS, lgtm, approved

#26 use default image user
  Dockerfile
Labels: size/XS, lgtm, approved

#28 update cluster colocation profile
  examples/spark-jobs/cluster-colocation-profile.yaml
  examples/spark-jobs/service-account.yaml
Labels: lgtm, approved, size/S

#29 Add contributing docs
  .github/workflows/ci.yaml
  .github/workflows/license.yml
  CONTRIBUTING.md
  README.md
  docs/proposals/YYYYMMDD-template.md
Labels: lgtm, approved, size/L
