Repository koordinator-sh/koordinator, pull requests merged in 2022-04, with the labels that each got.

#30 fix webhook validating
  Makefile
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/role.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/patch_manifests.yaml
  config/webhook/service.yaml
  pkg/webhook/add_pod.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
  pkg/webhook/pod/validating/request_limit_validator.go
  pkg/webhook/pod/validating/webhooks.go
Labels: lgtm, approved, size/L

#32 Config dependency licenses
  .license/README.md
  .license/dependency_decisions.yml
Labels: lgtm, approved, size/M

#34 Add changelog for v0.1.0
  CHANGELOG.md
Labels: lgtm, approved, size/L

#35 🐛 Remove unused code
  Makefile
  pkg/koordlet/audit/auditor_test.go
  pkg/koordlet/audit/logger_test.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/metriccache/util.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/pleg/watcher_other.go
  pkg/koordlet/reporter/reporter.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/metrics_query.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/util/container_test.go
  pkg/koordlet/util/node.go
  pkg/koordlet/util/pod.go
  pkg/koordlet/util/resource.go
  pkg/koordlet/util/util.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/noderesource/configmap_event_handler.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/util/client/delegating_client.go
  pkg/util/metrics/leadership/leader.go
  pkg/util/resource.go
  pkg/util/utils.go
  pkg/webhook/server.go
Labels: lgtm, approved, size/L

#41 📖 Add Dingtalk QRCode in README
  README.md
  docs/images/dingtalk.jpg
Labels: lgtm, approved, size/S

#43 🐛 Fix golangci-lint error
  .github/workflows/ci.yaml
Labels: size/XS, lgtm, approved

#38 Change Kubebuilder RBAC Annotation Groups
  pkg/slo-controller/nodeslo/nodeslo_controller.go
Labels: size/XS, lgtm, approved

#48 📖 Add Slack invite URL in README
  README.md
Labels: size/XS, lgtm, approved

#42 add some error handlers
  pkg/koordlet/metricsadvisor/collector.go
Labels: lgtm, approved, size/S

#61 🐛 Fix image tag typo
  examples/nginx/nginx.yaml
Labels: size/XS, lgtm, approved

#51 add HasSync function for collector
  pkg/koordlet/koordlet.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/collector_test.go
  pkg/koordlet/metricsadvisor/state.go
  pkg/koordlet/metricsadvisor/state_test.go
Labels: lgtm, approved, size/L, area/koordlet

#67 📖 Add logo and badges in README
  README.md
  docs/images/koordinator-logo.jpeg
Labels: lgtm, approved, size/S

#72 🌱 Add staticcheck ci action
  .github/workflows/ci.yaml
  pkg/runtime/handler/containerd_runtime.go
Labels: lgtm, approved, size/S

#74 🌱 Better CI pipeline
  .github/workflows/ci.yaml
  .github/workflows/license.yml
  Makefile
Labels: approved, size/L

#80 ⚠️ ignore Test_metaService_syncPods temporarily
  .github/workflows/ci.yaml
  pkg/koordlet/statesinformer/states_informer_test.go
Labels: lgtm, approved, size/M

#79 📖 Add membership doc & issue template
  .github/ISSUE_TEMPLATE/membership.yml
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  README.md
  docs/community/community-membership.md
Labels: lgtm, approved, size/L

#81 add koordlet arch design
  docs/desgin-archive/koordlet-architecture.md
  docs/images/cpu-suppress.png
  docs/images/koordlet-arch.png
  docs/images/llc-isolation.png
Labels: lgtm, approved, size/M

#76 Introduce protocol between RuntimeManager and RuntimeHookServer
  apis/runtime/v1alpha1/api.pb.go
  apis/runtime/v1alpha1/api.proto
  apis/runtime/v1alpha1/api_grpc.pb.go
  go.mod
  scripts/generate_runtime.sh
Labels: size/XXL, lgtm, approved

#36 add a proposal to improve Nodemetric
  Makefile
  docs/proposals/20220402-improve-the-efficiency-of-nodemetric.md
  hack/generate_client.sh
Labels: lgtm, approved, size/M

#86 🐛 fix nodeslo syncing issue
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/util/config.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/L

#88 Improve readme
  README.md
  docs/images/dingtalk.jpg
  docs/images/dingtalk.png
Labels: size/XS, lgtm, approved

#73 New feature: cpu burst strategy
  apis/extension/pod.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  go.mod
  go.sum
  pkg/features/koordlet_features.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/metrics_query.go
  pkg/koordlet/resmanager/reason.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/resource_update_executor.go
  pkg/koordlet/resmanager/resource_update_executor_test.go
  pkg/koordlet/resmanager/types.go
  pkg/koordlet/resmanager/types_test.go
  pkg/koordlet/statesinformer/mockstatesinformer/mock.go
  pkg/tools/cache/expiration_cache.go
  pkg/tools/cache/expiration_cache_test.go
  pkg/util/container.go
  pkg/util/system/cgroup.go
  pkg/util/system/cgroup_resource.go
  pkg/util/system/common.go
  pkg/util/utils.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#92 update image file format
  docs/desgin-archive/koordlet-architecture.md
  docs/images/cpu-suppress.png
  docs/images/cpu-suppress.svg
  docs/images/koordlet-arch.png
  docs/images/koordlet-arch.svg
  docs/images/llc-isolation.png
  docs/images/llc-isolation.svg
Labels: lgtm, approved, size/S

#93 🌱 add expire cache
  pkg/cache/expiration_cache.go
  pkg/cache/expiration_cache_test.go
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resmanager/resmanager.go
Labels: lgtm, approved, size/L

#100 Introduce HookServer config loading from /etc/runtime/hookserver.d/
  examples/runtime-hook-server/koordlet.json
  pkg/runtime-manager/config/config.go
  pkg/runtime-manager/config/config_manager.go
Labels: lgtm, approved, size/L

#98 📖 fix typo in docs
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: lgtm, approved, size/M

#108 add an issue template and rename feature request to proposal
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/membership.yml
  .github/ISSUE_TEMPLATE/proposal.md
  .github/ISSUE_TEMPLATE/support-request.md
Labels: lgtm, approved, size/M

#101 add memory qos strategy
  apis/extension/pod.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/features/koordlet_features.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/config.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/resource_update_executor.go
  pkg/koordlet/resmanager/resource_update_executor_test.go
  pkg/koordlet/resmanager/strategy_util.go
  pkg/koordlet/resmanager/strategy_util_test.go
  pkg/koordlet/resmanager/types.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/constants.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/util/config.go
  pkg/util/container.go
  pkg/util/pod.go
  pkg/util/system/cgroup.go
  pkg/util/system/cgroup_resource.go
  pkg/util/system/util_test_tool.go
  pkg/util/system/version.go
  pkg/util/system/version_test.go
Labels: size/XXL, lgtm, approved

#105 Introduce framwork of RuntimeManager and cri-proxy
  go.mod
  pkg/runtime-manager/dispatcher/dispatcher.go
  pkg/runtime-manager/dispatcher/hookclient.go
  pkg/runtime-manager/resource-executor/resource_executor.go
  pkg/runtime-manager/server/cri/criserver.go
  pkg/runtime-manager/server/cri/runtime.go
  pkg/runtime-manager/server/cri/utils.go
  pkg/runtime-manager/server/server.go
  pkg/runtime-manager/server/utils/utils.go
  vendor/google.golang.org/grpc/credentials/insecure/insecure.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#94 ✨ support LLC & MBA isolation
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/cache/expiration_cache.go
  pkg/cache/expiration_cache_test.go
  pkg/features/koordlet_features.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/reason.go
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/strategy_util.go
  pkg/koordlet/resmanager/types.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/tools/cache/expiration_cache.go
  pkg/tools/cache/expiration_cache_test.go
  pkg/util/config.go
  pkg/util/container.go
  pkg/util/container_test.go
  pkg/util/cpuinfo.go
  pkg/util/system/cgroup.go
  pkg/util/system/cgroup_resource.go
  pkg/util/system/resctrl.go
  pkg/util/system/resctrl_linux.go
  pkg/util/system/resctrl_linux_test.go
  pkg/util/system/resctrl_test.go
  pkg/util/system/resctrl_unsupported.go
Labels: size/XXL, lgtm, approved

#111 🌱 add unit test for resmanager
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/resmanager_test.go
  pkg/koordlet/resmanager/strategy_util.go
  pkg/util/config.go
  pkg/util/system/resctrl.go
Labels: lgtm, approved, size/XL
