Repository koordinator-sh/koordinator, pull requests merged in 2022-09, with the labels that each got.

#567 chore: add comments about CUDA version in dockerfile
  .goreleaser/koordlet.dockerfile
  docker/koordlet.dockerfile
Labels: lgtm, approved, size/S

#556 cpu suppress: only limits cpuset at besteffot container level if kube…
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/config_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/proxyserver/server.go
  pkg/koordlet/runtimehooks/proxyserver/service.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/statesinformer/mockstatesinformer/mock.go
  pkg/koordlet/statesinformer/register.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
Labels: lgtm, approved, size/L

#575 koord-runtime-proxy: add more tests
  pkg/runtimeproxy/resexecutor/cri/container_test.go
  pkg/runtimeproxy/resexecutor/cri/pod_test.go
Labels: lgtm, approved, size/L

#576 ci: ignore apis & pkg/client in codecov
  codecov.yml
Labels: size/XS, lgtm, approved

#578 test: add Test_DumpJSON()
  pkg/util/json_test.go
Labels: lgtm, approved, size/M

#544 koord-runtime-proxy: Introduce envs injecting under contianerd scenario
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/container_test.go
  pkg/runtimeproxy/resexecutor/cri/utils.go
  pkg/runtimeproxy/resexecutor/cri/utils_test.go
  pkg/runtimeproxy/server/cri/runtime.go
Labels: lgtm, approved, size/L

#410 feature: report gpu resource
  cmd/koord-manager/main.go
  go.mod
  go.sum
  pkg/koordlet/koordlet.go
  pkg/koordlet/statesinformer/config.go
  pkg/koordlet/statesinformer/states_device.go
  pkg/koordlet/statesinformer/states_device_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/slo-controller/noderesource/device_event_handler.go
  pkg/slo-controller/noderesource/nodemetric_event_handler.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/util/node.go
Labels: lgtm, approved, size/XL

#571 docs: Update details about compatible existing GPU Pods
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Labels: lgtm, approved, size/L

#580 koodlet: fix gpu reporter build tag
  pkg/koordlet/statesinformer/states_device_linux.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
  pkg/koordlet/statesinformer/states_device_unsupported.go
Labels: lgtm, approved, size/M

#521 feat: get kubelet pid through kubeletEndpoint port
  go.mod
  go.sum
  pkg/koordlet/koordlet.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/util/system/cgroup_driver_linux.go
  pkg/util/system/cgroup_driver_unsupported.go
  pkg/util/system/common_linux.go
  pkg/util/system/common_linux_test.go
  pkg/util/system/cpu_manager_linux.go
  pkg/util/system/cpu_manager_unsupported.go
Labels: lgtm, approved, size/L

#582 test: add tests for reservation utils
  pkg/util/reservation_test.go
Labels: lgtm, approved, size/L

#541 add groupQuotaManager
  apis/extension/elastic_quota.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
  pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
  pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res_test.go
Labels: size/XXL, lgtm, approved

#510 koord-scheduler: implement enhanced coscheduling
  .licenseignore
  apis/extension/priority.go
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/types.go
  cmd/koord-scheduler/main.go
  docs/proposals/scheduling/20200901-gang-scheduling.md
  pkg/scheduler/plugins/coscheduling/controller/podgroup.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
  pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Labels: size/XXL, lgtm, approved

#587 koodlet: fix resource in cri proxy response maybe nil for kubelet 1.18
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/protocol/protocol_test.go
Labels: lgtm, approved, size/L

#579 add extension plugin framework for nodeslo
  apis/extension/qos.go
  apis/slo/v1alpha1/nodeslo_ext.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  cmd/koord-manager/extensions/extension.go
  cmd/koord-manager/main.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/executor/reason.go
  pkg/koordlet/executor/resctrl_executor.go
  pkg/koordlet/executor/resource_update_executor.go
  pkg/koordlet/executor/resource_update_executor_test.go
  pkg/koordlet/executor/types.go
  pkg/koordlet/executor/types_test.go
  pkg/koordlet/resmanager/be_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/config.go
  pkg/koordlet/resmanager/config_test.go
  pkg/koordlet/resmanager/context/extensionplugin.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resmanager/plugins/plugins.go
  pkg/koordlet/resmanager/plugins/register.go
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/util/pod.go
  pkg/util/system/cgroup_resource.go
  pkg/util/system/resctrl.go
  pkg/util/system/util_test_tool.go
Labels: size/XXL, lgtm, approved

#588 koord-scheduler: fix Reserve Pod concurrent map write fatal error
  pkg/util/reservation.go
Labels: size/XS, lgtm, approved

#589 koord-scheduler: fix Reservation normalize score
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/L

#502 koord-scheduler: support device(GPU/RDMA/FPGA) sharing feature
  apis/extension/resource.go
  apis/extension/scheduling.go
  apis/extension/scheduling_test.go
  cmd/koord-scheduler/main.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_cache_test.go
  pkg/scheduler/plugins/deviceshare/device_handler.go
  pkg/scheduler/plugins/deviceshare/device_handler_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/pod_handler.go
  pkg/scheduler/plugins/deviceshare/pod_handler_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/deviceshare/utils_test.go
Labels: size/XXL, lgtm, approved

#593 koordlet: startup flag replace int with time.Duration in reporter
  pkg/koordlet/reporter/config.go
  pkg/koordlet/reporter/config_test.go
  pkg/koordlet/reporter/reporter.go
Labels: lgtm, approved, size/S

#594 koord-scheduler: fix DeviceShare UT
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/S

#590 QoS Manager Framework
  cmd/koordlet/main.go
  pkg/features/koordlet_features.go
  pkg/koordlet/common/reason/reason.go
  pkg/koordlet/common/testutil/k8s.go
  pkg/koordlet/common/types/constants.go
  pkg/koordlet/common/utils/containers.go
  pkg/koordlet/common/utils/pod.go
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/qosmanager/config/config.go
  pkg/koordlet/qosmanager/config/config_test.go
  pkg/koordlet/qosmanager/k8s/k8s.go
  pkg/koordlet/qosmanager/manager.go
  pkg/koordlet/qosmanager/manager_test.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query_test.go
  pkg/koordlet/qosmanager/plugins/context.go
  pkg/koordlet/qosmanager/plugins/plugin.go
Labels: size/XXL, lgtm, approved

#592 koordlet: report kubelet reserved cpus
  .licenseignore
  apis/extension/node.go
  apis/extension/resource.go
  cmd/koordlet/main.go
  go.mod
  go.sum
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
  pkg/util/kubelet/cpu_assignment.go
  pkg/util/kubelet/cpu_assignment_test.go
  pkg/util/kubelet/kubelet.go
  pkg/util/kubelet/kubelet_test.go
  pkg/util/kubelet/policy_test.go
  pkg/util/system/common_linux.go
  pkg/util/system/cpu_manager_linux.go
  pkg/util/system/cpu_manager_unsupported.go
Labels: size/XXL, lgtm, approved

#595 koord-scheduler: support kubelet reserved cpus
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
Labels: lgtm, approved, size/S

#598 chore: add aliyun hangzhou registry when publish release
  .goreleaser.yaml
Labels: size/XS, lgtm, approved

#601 Revert "QoS Manager Framework"
  cmd/koordlet/main.go
  pkg/features/koordlet_features.go
  pkg/koordlet/common/reason/reason.go
  pkg/koordlet/common/testutil/k8s.go
  pkg/koordlet/common/types/constants.go
  pkg/koordlet/common/utils/containers.go
  pkg/koordlet/common/utils/pod.go
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/qosmanager/config/config.go
  pkg/koordlet/qosmanager/config/config_test.go
  pkg/koordlet/qosmanager/k8s/k8s.go
  pkg/koordlet/qosmanager/manager.go
  pkg/koordlet/qosmanager/manager_test.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query_test.go
  pkg/koordlet/qosmanager/plugins/context.go
  pkg/koordlet/qosmanager/plugins/plugin.go
Labels: size/XXL, lgtm, approved

#605 chore: remove deprecated io/ioutil
  pkg/koordlet/audit/auditor_test.go
  pkg/koordlet/audit/event_logger_test.go
  pkg/koordlet/audit/logger_test.go
  pkg/koordlet/metricsadvisor/collector_gpu_linux_test.go
  pkg/koordlet/resmanager/be_reconcile.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/statesinformer/kubelet_stub.go
  pkg/runtimeproxy/config/config_manager.go
  pkg/runtimeproxy/server/docker/handler.go
  pkg/runtimeproxy/server/docker/handler_test.go
  pkg/util/container.go
  pkg/util/container_test.go
  pkg/util/cpuinfo.go
  pkg/util/cpuset.go
  pkg/util/cpuset_test.go
  pkg/util/kubelet/kubelet.go
  pkg/util/kubelet/kubelet_test.go
  pkg/util/meminfo.go
  pkg/util/meminfo_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
  pkg/util/runtime/handler/docker_runtime_test.go
  pkg/util/runtime/runtime_test.go
  pkg/util/stat.go
  pkg/util/stat_test.go
  pkg/util/system/cgroup.go
  pkg/util/system/common.go
  pkg/util/system/common_linux.go
  pkg/util/system/resctrl.go
  pkg/util/system/resctrl_test.go
  pkg/util/system/util_test_tool.go
  pkg/webhook/util/health/checker.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
  pkg/webhook/util/writer/fs.go
Labels: lgtm, approved, size/L

#606 fix: fix panic when NodeTopo is nil
  pkg/koordlet/resmanager/cpu_suppress.go
Labels: size/XS, lgtm, approved

#604 koord-scheduler: support debug scores
  cmd/koord-scheduler/app/options/options.go
  cmd/koord-scheduler/app/server.go
  go.mod
  go.sum
  pkg/scheduler/frameworkext/debug_scores.go
  pkg/scheduler/frameworkext/debug_scores_test.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/util/routes/flags.go
Labels: lgtm, approved, size/L

#611 feat(deps): bump github.com/lluissm/license-header-checker from 1.3 to 1.4
  hack/update-license-header.sh
Labels: size/XS, lgtm, approved

#609 koord-descheduler: support plugins customize MigrationJob via context
  pkg/descheduler/controllers/migration/context.go
  pkg/descheduler/controllers/migration/context_test.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/evictor/interpreter.go
  pkg/descheduler/controllers/names/names.go
Labels: lgtm, approved, size/L

#613 koordlet: change evict to v1beta1 for compatible with 1.21-
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/koordlet/resmanager/resmanager.go
Labels: lgtm, approved, size/S

#612 koordlet: fix incompatibility with kubelet v1.18 flags
  pkg/util/kubelet/kubelet.go
Labels: size/XS, lgtm, approved

#616 chore: update license checker repo
  .github/workflows/license.yml
  hack/update-license-header.sh
Labels: size/XS, lgtm, approved

#584 koord-scheduler: add elastic quota plugin
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/defaults.go
  apis/scheduling/config/v1beta2/types.go
  apis/scheduling/config/v1beta2/zz_generated.conversion.go
  apis/scheduling/config/v1beta2/zz_generated.deepcopy.go
  apis/scheduling/config/validation/validation_pluginargs.go
  apis/scheduling/config/zz_generated.deepcopy.go
  cmd/koord-scheduler/main.go
  go.mod
  pkg/scheduler/plugins/elasticquota/candidate.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/controller_test.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
  pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
  pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res_test.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/pod_handler.go
  pkg/scheduler/plugins/elasticquota/preempt.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Labels: size/XXL, lgtm, approved

#615 feat(deps): bump github.com/NVIDIA/go-nvml
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#620 koord-scheduler: fix quota ut failed
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: lgtm, approved, size/M

#603 add restful api for coscheduling
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/plugin_service.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
Labels: lgtm, approved, size/L

#625 koord-scheduler: optimize ElasticQuota UT
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Labels: lgtm, approved, size/L

#624 koord-scheduler:refine gang restful api for coscheduling
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_summary.go
  pkg/scheduler/plugins/coscheduling/plugin_service.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
Labels: lgtm, approved, size/L

#627 koord-scheduler: support score schedulingPhase hook and multiple hook
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
Labels: lgtm, approved, size/L

#628 koord-scheduler: add quota debug restful api
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_summary.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
  pkg/scheduler/plugins/elasticquota/plugin_service.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: lgtm, approved, size/L

#635 koordlet: fix nvml init error
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#634 koordlet: fix failed update existing Device CRD object
  pkg/koordlet/statesinformer/states_device_linux.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
Labels: lgtm, approved, size/M

#623 Update and rename support-request.md to question.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/support-request.md
Labels: lgtm, approved, size/M

#633 fix coScheduling ut
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
Labels: lgtm, approved, size/L

#637 koord-scheduler: add device scheduling debug api
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_cache_test.go
  pkg/scheduler/plugins/deviceshare/device_handler.go
  pkg/scheduler/plugins/deviceshare/device_handler_test.go
  pkg/scheduler/plugins/deviceshare/device_summary.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_service.go
  pkg/scheduler/plugins/deviceshare/plugin_service_test.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/pod_handler_test.go
Labels: lgtm, approved, size/XL

#638 koord-scheduler: change NodeNUMAResource API endpoints
  pkg/scheduler/plugins/nodenumaresource/plugin_service.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
Labels: size/XS, lgtm, approved

#641 koord-scheduler: fix schedulingPhaseHook registerd log nil pointer bug
  pkg/scheduler/frameworkext/framework_extender.go
Labels: size/XS, lgtm, approved

#640 koordlet: cpu suppress check whether nodeslo enable
  pkg/koordlet/resmanager/be_reconcile.go
  pkg/koordlet/resmanager/cpu_suppress.go
Labels: lgtm, approved, size/S

#631 fix: panic on node nil
  pkg/koordlet/koordlet.go
Labels: size/XS, lgtm, approved

#642 koord-scheduler: fix quota panic if missing QuotaInfo
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
Labels: lgtm, approved, size/M

#636 bugfix: not report when no gpu device
  pkg/koordlet/statesinformer/states_device_linux.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/util/resource.go
Labels: lgtm, approved, size/M

#643 fix CoScheduling ut:wg count negative bug
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved, size/M

#645 koord-scheduler: fix ElasticQuota panic when init
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
Labels: lgtm, approved, size/M

#646 chore: change ElasticQuota log level
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
Labels: size/XS, lgtm, approved

#648 koordlet: fix memory evict for nil podMetric
  pkg/koordlet/resmanager/memory_evict.go
Labels: lgtm, approved, size/S

#644 just tidy up some logic
  pkg/runtimeproxy/server/cri/criserver.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/nodeslo/resource_strategy.go
Labels: lgtm, approved, size/M

#649 chore: update resource names in Fine-grained Device Scheduling proposal
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Labels: lgtm, approved, size/M

#647 chore: rename Gang Scheduling proposal
  docs/proposals/scheduling/20220901-gang-scheduling.md
Labels: size/XS, lgtm, approved

#650 koord-manager: revise node batch resource update
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_test.go
Labels: lgtm, approved, size/M

#658 koord-scheduler: fix ElasticQuota controller panic when update annotations
  pkg/scheduler/plugins/elasticquota/controller.go
Labels: size/XS, lgtm, approved

#659 koord-scheduler: fix PodGroupController panic when init
  pkg/scheduler/plugins/coscheduling/controller/podgroup.go
Labels: lgtm, approved, size/S

#652 koord-manager: support calculate batch resource based on memory request
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/config_extender_test.go
  pkg/slo-controller/config/config_test.go
  pkg/slo-controller/config/zz_generated.deepcopy.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: lgtm, approved, size/L

#666 chore: update bug issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: size/XS, lgtm, approved

#669 fix: correct pod informer delete event
  pkg/scheduler/plugins/deviceshare/plugin.go
Labels: size/XS, lgtm, approved

#656 fix: use pointer for minor in device crd
  apis/scheduling/v1alpha1/device_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/koordlet/reporter/reporter.go
  pkg/koordlet/statesinformer/states_device_linux.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
  pkg/scheduler/plugins/deviceshare/device_handler.go
  pkg/scheduler/plugins/deviceshare/device_handler_test.go
  pkg/scheduler/plugins/deviceshare/plugin_service_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
Labels: lgtm, approved, size/M
