Repository koordinator-sh/koordinator, pull requests merged in 2022-06, with the labels that each got.

#208 chore: update codecov.yaml
  codecov.yml
  pkg/util/meminfo_test.go
Labels: lgtm, approved, size/M

#215 fix: change directory of generate-runtime.sh
  apis/runtime/v1alpha1/api.pb.go
  apis/runtime/v1alpha1/api.proto
Labels: size/XS, lgtm, approved

#220 Fix bug where runtime proxy cannot decode annotations in Docker config
  pkg/runtimeproxy/server/docker/utils.go
  pkg/runtimeproxy/server/docker/utils_test.go
Labels: lgtm, approved, size/M

#180 feat: add kubelet http2 support
  pkg/koordlet/statesinformer/config.go
  pkg/koordlet/statesinformer/config_test.go
  pkg/koordlet/statesinformer/kubelet_stub.go
  pkg/koordlet/statesinformer/kubelet_stub_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/koordlet/statesinformer/states_pod.go
  pkg/util/http.go
  pkg/util/node.go
  pkg/util/node_test.go
Labels: lgtm, approved, size/XL

#231 Add PreCreateContainerHook and PostStopSandboxHook and update parameters
  apis/runtime/v1alpha1/api.pb.go
  apis/runtime/v1alpha1/api.proto
  apis/runtime/v1alpha1/api_grpc.pb.go
  hack/generate-runtime.sh
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
  pkg/koordlet/runtimehooks/server/service.go
  pkg/runtimeproxy/dispatcher/dispatcher.go
  pkg/runtimeproxy/resexecutor/cri/pod.go
  pkg/runtimeproxy/server/docker/handler.go
  pkg/runtimeproxy/server/docker/server.go
  pkg/runtimeproxy/store/manager.go
Labels: lgtm, approved, size/XL

#238 Fix: Regenerate runtime api to fix typo
  apis/runtime/v1alpha1/api.pb.go
  apis/runtime/v1alpha1/api.proto
  apis/runtime/v1alpha1/api_grpc.pb.go
Labels: lgtm, approved, size/L

#242 fix: incorrect coversion of an integer
  pkg/util/cpuinfo.go
  pkg/util/system/lscpu.go
  pkg/util/utils.go
Labels: lgtm, approved, size/S

#207 docs: what is a good pull request
  CONTRIBUTING.md
  docs/contributors/first-pr.md
  docs/contributors/good-pr.md
Labels: lgtm, approved, size/L

#247 Add Defer os.Remove before starting runtime proxy server
  cmd/koord-runtime-proxy/main.go
Labels: size/XS, lgtm, approved

#243 Add container id to ContainerResourceHookRequest
  apis/runtime/v1alpha1/api.pb.go
  apis/runtime/v1alpha1/api.proto
  apis/runtime/v1alpha1/api_grpc.pb.go
Labels: lgtm, approved, size/L

#239 Implement cri scenario PreCreateContainerHook and PostStopPodSandboxHook
  pkg/runtimeproxy/config/config.go
  pkg/runtimeproxy/dispatcher/dispatcher.go
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/container_test.go
  pkg/runtimeproxy/resexecutor/cri/pod.go
  pkg/runtimeproxy/resexecutor/cri/pod_test.go
  pkg/runtimeproxy/resexecutor/cri/utils.go
  pkg/runtimeproxy/resexecutor/cri/utils_test.go
  pkg/runtimeproxy/resexecutor/resource_executor.go
  pkg/runtimeproxy/resexecutor/resource_executor_test.go
  pkg/runtimeproxy/server/cri/criserver.go
  pkg/runtimeproxy/server/docker/handler.go
  pkg/runtimeproxy/store/manager.go
Labels: lgtm, approved, size/XL

#250 refactor: prune socket before launching runtime-proxy
  cmd/koord-runtime-proxy/main.go
  pkg/runtimeproxy/server/cri/criserver.go
Labels: lgtm, approved, size/M

#251 Add container id to container info when store to cache
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/container_test.go
Labels: lgtm, approved, size/M

#244 refactor: replace reinvented wheel with `Get()` in standard library
  pkg/koordlet/audit/auditor.go
Labels: lgtm, approved, size/S

#248 change cpuacct.stat to cpuacct.usage
  pkg/koordlet/metricsadvisor/be_collector.go
  pkg/koordlet/metricsadvisor/be_collector_test.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/util/container.go
  pkg/util/container_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
  pkg/util/stat.go
  pkg/util/stat_test.go
  pkg/util/system/cgroup_resource.go
  pkg/util/system/cgroup_test.go
Labels: lgtm, approved, size/XL

#212 docs: propose a logging convention
  docs/contributors/logging.md
Labels: lgtm, approved, size/M

#237 chore: update OWNERS in each module
  OWNERS
  pkg/koordlet/OWNERS
  pkg/runtimeproxy/OWNERS
  pkg/scheduler/OWNERS
  pkg/slo-controller/OWNERS
  pkg/webhook/OWNERS
Labels: lgtm, approved, size/S

#252 docker-proxy: update podInfo and containerInfo with hook resp cgroupParent
  pkg/runtimeproxy/server/docker/handler.go
Labels: size/XS

#261 ci: build & push docker when PR is merged into main
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/M

#209 Add fine-grained cpu orchestration proposal
  docs/images/cpu-orchestration-seq-uml.svg
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
Labels: lgtm, approved, size/XL

#241 add resource reservation proposal
  codecov.yml
  docs/images/resource-reservation.svg
  docs/proposals/scheduling/20220609-resource-reservation.md
Labels: lgtm, approved, size/L

#267 ci: fix docker build context
  .github/workflows/ci.yaml
  Dockerfile
Labels: lgtm, approved, size/S

#263 defines CPU orchestration APIs
  apis/extension/constants.go
  apis/extension/node.go
  apis/extension/resource.go
  apis/extension/scheduling.go
Labels: lgtm, approved, size/L

#269 remove macos tests
  .github/workflows/ci.yaml
Labels: size/XS, lgtm, approved

#272 add more tests
  pkg/util/pod.go
  pkg/util/pod_test.go
Labels: lgtm, approved, size/L

#266 refactor: move runtime module under util package
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/util/runtime/handler/containerd_runtime.go
  pkg/util/runtime/handler/containerd_runtime_test.go
  pkg/util/runtime/handler/docker_runtime.go
  pkg/util/runtime/handler/docker_runtime_test.go
  pkg/util/runtime/handler/fake_runtime.go
  pkg/util/runtime/handler/interface.go
  pkg/util/runtime/handler/mockclient/mock.go
  pkg/util/runtime/runtime.go
  pkg/util/runtime/runtime_test.go
Labels: lgtm, approved, size/M

#274 fixed setup kubelet docs, which caused kubelet startup exception
  docs/design-archive/koord-runtime-proxy-design-doc.md
Labels: size/XS, lgtm, approved

#276 api: add reservation API
  apis/scheduling/v1alpha1/groupversion_info.go
  apis/scheduling/v1alpha1/reservation_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
  hack/update-codegen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_reservation.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_scheduling_client.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/reservation.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/scheduling/interface.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/interface.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/reservation.go
  pkg/client/listers/scheduling/v1alpha1/expansion_generated.go
  pkg/client/listers/scheduling/v1alpha1/reservation.go
Labels: size/XXL, lgtm, approved

#282 ci: use matrix and cache to speed up the build
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/M

#253 chore: add goreleaser
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  .goreleaser/Dockerfile
  Makefile
Labels: lgtm, approved, size/L

#277 chore: improve pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: lgtm, approved, size/M

#287 add more tests for docker-proxy
  pkg/runtimeproxy/server/docker/handler_test.go
  pkg/runtimeproxy/server/docker/server.go
  pkg/runtimeproxy/server/docker/server_test.go
Labels: size/L

#290 feat(deps): bump sigs.k8s.io/controller-runtime from 0.10.2 to 0.10.3
  apis/scheduling/v1alpha1/groupversion_info.go
  apis/scheduling/v1alpha1/reservation_types.go
  go.mod
  go.sum
Labels: lgtm, approved, size/S

#291 feat(deps): bump k8s.io/klog/v2 from 2.9.0 to 2.10.0
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#308 apis: update cpu scheduling plugin args and apis
  apis/extension/constants.go
  apis/extension/node.go
  apis/extension/resource.go
  apis/scheduling/config/register.go
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/defaults.go
  apis/scheduling/config/v1beta2/register.go
  apis/scheduling/config/v1beta2/types.go
  apis/scheduling/config/v1beta2/zz_generated.conversion.go
  apis/scheduling/config/v1beta2/zz_generated.deepcopy.go
  apis/scheduling/config/v1beta2/zz_generated.defaults.go
  apis/scheduling/config/zz_generated.deepcopy.go
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
Labels: lgtm, approved, size/L

#307 koord-scheduler: refactor framework extender init function
  cmd/koord-scheduler/app/config/config.go
  cmd/koord-scheduler/app/options/options.go
  cmd/koord-scheduler/app/server.go
  go.mod
  go.sum
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/M

#309 bugfix: fix noderesource-controller, reporter reconcile on node deletion
  pkg/koordlet/reporter/reporter.go
  pkg/koordlet/reporter/reporter_test.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
Labels: lgtm, approved, size/L

#306 add koordlet running mode design doc
  docs/design-archive/koordlet-runtime-hooks-mode.md
  docs/images/koordlet-hooks-running-mode.svg
Labels: lgtm, approved, size/M

#311 ci: ignore generated files when calculating coverage
  codecov.yml
Labels: size/XS, lgtm, approved

#305 refactor: slo-controller use cache manage configmap
  Makefile
  go.mod
  go.sum
  pkg/slo-controller/config/colocation_cm_event_handler.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/configmap_event_handler.go
  pkg/slo-controller/config/configmap_event_handler_test.go
  pkg/slo-controller/config/zz_generated.deepcopy.go
  pkg/slo-controller/nodemetric/collect_policy.go
  pkg/slo-controller/nodemetric/collect_policy_test.go
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/nodemetric/nodemetric_controller_test.go
  pkg/slo-controller/noderesource/configmap_event_handler.go
  pkg/slo-controller/noderesource/configmap_event_handler_test.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
Labels: size/XXL, lgtm, approved

#283 use unified internal protocol for running hooks plugin
  docs/design-archive/koordlet-runtime-hooks.md
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/kubeqos_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/proxyserver/server.go
  pkg/koordlet/runtimehooks/proxyserver/service.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/server/service.go
  pkg/koordlet/statesinformer/register.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/koordlet/statesinformer/states_pod.go
  pkg/util/container.go
  pkg/util/system/cgroup_driver.go
Labels: size/XXL, lgtm, approved

#262 Proposal QoS Manager
  docs/images/qos-manager.svg
  docs/proposals/koordlet/20220615-qos-manager.md
Labels: lgtm, approved, size/L

#317 koord-scheduler: loadAwareScheduling skip node without NodeMetric in …
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/L, area/koord-scheduler

#318 rename runtime-hook working mode (Bypass->Standalone)
  docs/images/runtime-hooks-working-mode.svg
Labels: size/XS, lgtm, approved

#312 feature: report cpu info to noderesoucetopology
  pkg/koordlet/koordlet.go
  pkg/koordlet/statesinformer/config.go
  pkg/koordlet/statesinformer/config_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/koordlet/statesinformer/states_node.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
Labels: lgtm, size/L

#320 feat: add read only port support for koordlet
  pkg/koordlet/statesinformer/kubelet_stub.go
  pkg/koordlet/statesinformer/kubelet_stub_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_informer_test.go
Labels: lgtm, approved, size/L

#319 add reconciler for runtime hook standalone work mode
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
  pkg/koordlet/runtimehooks/rule/inject.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/koordlet/statesinformer/mockstatesinformer/mock.go
  pkg/koordlet/statesinformer/register.go
  pkg/koordlet/statesinformer/register_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/koordlet/statesinformer/states_pod.go
Labels: lgtm, approved, size/XL

#324 add cpuset allocator
  apis/extension/node.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/statesinformer/register.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
Labels: size/XXL, lgtm, approved

#325 Fix wrong cgroup path for PLEG
  pkg/koordlet/pleg/pleg.go
Labels: size/XS, lgtm, approved

#329 add logs for proxy server
  pkg/koordlet/runtimehooks/proxyserver/service.go
Labels: size/XS, approved
