Repository koordinator-sh/koordinator, pull requests merged in 2022-07, with the labels that each got.

#336 chore: remove useless feature-gates
  pkg/features/koord_features.go
Labels: lgtm, approved, size/M

#334 ci: enable CGO when GoReleaser compiles binaries
  .goreleaser.yaml
Labels: lgtm, approved, size/S

#339 rename resourceQoS to resourceQOS
  apis/extension/pod.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/koordlet/statesinformer/states_nodeslo_test.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/constants.go
  pkg/slo-controller/config/zz_generated.deepcopy.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/util/config.go
Labels: size/XXL, lgtm, approved

#338 improve koordlet log verbosity
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/reporter/reporter.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/memory_evict.go
Labels: lgtm, approved, size/M

#344 Add pod uid to pod meta when failover
  pkg/runtimeproxy/resexecutor/cri/pod.go
  pkg/runtimeproxy/server/docker/server.go
Labels: size/XS

#349 cleanup: Use the structure as the key of the map instead of string
  pkg/runtimeproxy/dispatcher/hookclient.go
Labels: size/XS, lgtm, approved

#354 koord-scheduler: support default preferredCPUBindPolicy for LSE/LSR P…
  apis/extension/resource.go
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/defaults.go
  apis/scheduling/config/v1beta2/types.go
  apis/scheduling/config/v1beta2/zz_generated.conversion.go
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/L

#322 add fine-grained device scheduling proposal
  docs/images/nvlink.jpg
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Labels: lgtm, approved, size/L

#355 [koord-runtime-proxy]: fix panic when no hook registered
  pkg/runtimeproxy/server/cri/criserver.go
Labels: size/XS, lgtm, approved

#359 koord-scheduler: support CPU exclusive policy
  apis/extension/resource.go
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/types.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocator.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocator_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
  pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/L, area/koord-scheduler

#363 [koord-runtime-proxy] fix the loss of new updated resources from UpdateContainerResources request
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/container_test.go
  pkg/runtimeproxy/resexecutor/cri/utils.go
  pkg/runtimeproxy/resexecutor/cri/utils_test.go
  pkg/runtimeproxy/server/docker/handler.go
  pkg/runtimeproxy/server/docker/utils.go
  pkg/runtimeproxy/server/docker/utils_test.go
Labels: lgtm, approved, size/L

#365 add scheduling framework extender
  cmd/koord-scheduler/app/server.go
  cmd/koord-scheduler/main.go
  pkg/scheduler/frameworkext/framework_extender.go
Labels: lgtm, approved, size/L

#367 koordlet: refine initJiffies with default value
  pkg/koordlet/metricsadvisor/collector.go
Labels: lgtm, approved, size/S

#358 add PodMigrationJob CRD proposal
  docs/proposals/scheduling/20220701-pod-migration-job.md
Labels: lgtm, approved, size/L, area/koord-descheduler

#333 add proposal for gang scheduling
  docs/proposals/scheduling/20220701-schedule-gang.md
Labels: lgtm, approved, size/L

#360 Support node cpu orchestration api
  apis/extension/node.go
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/defaults.go
  apis/scheduling/config/v1beta2/types.go
  apis/scheduling/config/v1beta2/zz_generated.conversion.go
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
  pkg/scheduler/plugins/nodenumaresource/cpu_allocator.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/L

#364 chore: update dockerfile for each module
  .github/workflows/ci.yaml
  .goreleaser.yaml
  .goreleaser/Dockerfile
  .goreleaser/koord-manager.dockerfile
  .goreleaser/koord-scheduler.dockerfile
  .goreleaser/koordlet.dockerfile
  Dockerfile
  Makefile
  docker/koord-manager.dockerfile
  docker/koord-scheduler.dockerfile
  docker/koordlet.dockerfile
Labels: lgtm, approved, size/L

#374 chore: supply UT for pkg/util and pkg/util/system
  pkg/util/resource_test.go
  pkg/util/system/cgroup_test.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/L

#375 api: add PodMigrationJob API
  apis/scheduling/v1alpha1/pod_migration_job_types.go
  apis/scheduling/v1alpha1/reservation_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_podmigrationjobs.yaml
  docs/proposals/scheduling/20220701-pod-migration-job.md
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_podmigrationjob.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_scheduling_client.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/podmigrationjob.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/interface.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/podmigrationjob.go
  pkg/client/listers/scheduling/v1alpha1/expansion_generated.go
  pkg/client/listers/scheduling/v1alpha1/podmigrationjob.go
Labels: size/XXL, lgtm, approved

#377 docs: remove redundant field in Device CRD
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Labels: lgtm, approved, size/M

#376 api: add device CRD in scheduling group
  apis/scheduling/v1alpha1/device_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/device.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_device.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_scheduling_client.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/device.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/interface.go
  pkg/client/listers/scheduling/v1alpha1/device.go
  pkg/client/listers/scheduling/v1alpha1/expansion_generated.go
Labels: lgtm, approved, size/XL

#379 fix auditor test in MacOS
  hack/run-test.sh
  pkg/koordlet/audit/auditor_test.go
Labels: size/XS, lgtm, approved

#382 koordlet: optimize auditor UT with httptest.Server
  pkg/koordlet/audit/auditor.go
  pkg/koordlet/audit/auditor_test.go
Labels: lgtm, approved, size/M

#380 docs: add chinese version readme.md
  README-zh_CN.md
  README.md
Labels: lgtm, approved, size/M

#372 fix: consider lse/lsr when cpu suppress (#234)
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
Labels: lgtm, approved, size/XL

#378 api: add device info into NodeMetric CRD
  apis/extension/resource.go
  apis/scheduling/v1alpha1/device_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  apis/slo/v1alpha1/nodemetric_types.go
  apis/slo/v1alpha1/resources.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved, size/L

#361 koordlet: support collecting GPU metrics from node/pod/container
  go.mod
  go.sum
  pkg/koordlet/metriccache/api.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/storage_tables.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/collector_gpu.go
  pkg/koordlet/metricsadvisor/collector_gpu_test.go
  pkg/util/container.go
  pkg/util/container_test.go
  pkg/util/system/cgroup_resource.go
Labels: size/XXL, lgtm

#383 chore: cleanup resmanager
  pkg/koordlet/resmanager/resmanager.go
  pkg/util/feature.go
Labels: lgtm, size/S

#371 add descheduler framework proposal
  docs/proposals/scheduling/20220701-simple-descheduler-framework.md
Labels: lgtm, approved, size/L

#394 koordlet: Turn on pleg
  pkg/koordlet/koordlet.go
Labels: size/XS, lgtm, approved

#397 feat: update GPU metrics in NodeMetric CRD
  pkg/koordlet/metriccache/api.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/storage_tables.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/collector_gpu.go
  pkg/koordlet/metricsadvisor/collector_gpu_test.go
  pkg/koordlet/reporter/reporter.go
  pkg/koordlet/reporter/reporter_test.go
Labels: lgtm, approved, size/XL

#403 bugfix: always need to reset cpuset when cpu supress
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
Labels: lgtm, approved, size/S

#386 feature: report pod alloc of Guaranteed pod and cpu manager policy
  apis/extension/node.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
  pkg/util/system/cpu_manager_linux.go
  pkg/util/system/cpu_manager_unsupported.go
Labels: lgtm, size/L

#399 api: update PodMigrationJob and Reservation CRD
  apis/scheduling/v1alpha1/pod_migration_job_types.go
  apis/scheduling/v1alpha1/reservation_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_podmigrationjobs.yaml
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
  docs/proposals/scheduling/20220609-resource-reservation.md
  docs/proposals/scheduling/20220701-pod-migration-job.md
Labels: size/XXL, lgtm, approved

#393 koordlet: introduce `Accelerators` feature gate for GPU related features
  pkg/features/koordlet_features.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/collector_gpu.go
Labels: lgtm, approved, size/S

#413 koordlet: fix build error caused by GPU
  pkg/koordlet/metricsadvisor/collector_gpu.go
  pkg/koordlet/metricsadvisor/collector_gpu_linux.go
  pkg/koordlet/metricsadvisor/collector_gpu_linux_test.go
  pkg/koordlet/metricsadvisor/collector_gpu_unsupported.go
Labels: lgtm, approved, size/XL

#414 cri-runtime-proxy: fix containerErr error when failOver pods and cont…
  pkg/runtimeproxy/server/cri/criserver.go
Labels: size/XS, lgtm, approved

#415 make slo configmap name configurable
  cmd/koord-manager/main.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/config_test.go
  pkg/slo-controller/config/constants.go
Labels: lgtm, approved, size/M

#412 clear cpuset of BE container to avoid conflict with kubelet static po…
  apis/extension/node.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
Labels: lgtm, approved, size/L

#418 change qos func name for old format adaption reason
  apis/extension/qos.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
Labels: lgtm, approved, size/S
