Repository koordinator-sh/koordinator, pull requests merged in 2022-12, with the labels that each got.

#855 docs: update fine-grained CPU orchestration doc
  docs/images/qos-cpu-orchestration.png
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
Labels: lgtm, approved, size/S

#857 koord-scheduler: ElasticQuota supports Decorator to decorate Node, Pod and ElasticQuota
  pkg/scheduler/plugins/elasticquota/core/decorator.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/pod_handler.go
  pkg/scheduler/plugins/elasticquota/preempt.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: lgtm, approved, size/L

#864 Update new slack channel in K8s workspace
  README-zh_CN.md
  README.md
Labels: size/XS, lgtm, approved

#861 api: add percentile node usage to NodeMetric
  apis/slo/v1alpha1/nodemetric_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved, size/L

#858 koord-scheduler: fix quota ut error
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: size/XS, lgtm, approved

#862 docs: add star history into README
  README.md
Labels: size/XS, lgtm, approved

#863 docs: add star history into README-zh_CN
  README-zh_CN.md
Labels: size/XS, lgtm, approved

#866 koord-scheduler: fix PodGroupController init error
  .github/workflows/ci.yaml
  apis/slo/v1alpha1/nodemetric_types.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/plugin_controller.go
  pkg/scheduler/plugins/coscheduling/plugin_service.go
Labels: lgtm, approved, size/L

#876 koord-scheduler: make ForceSyncFromInformer easier to use
  pkg/scheduler/frameworkext/helper/synced_eventhandler.go
Labels: lgtm, approved, size/S

#852 koordlet: make UsageHighEnough configurable for cpu_evict
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/cpu_evict_test.go
Labels: lgtm, approved, size/L, ok-to-test

#877 cleanup: move pkg/tool/cache to pkg/util/cache
  pkg/koordlet/executor/resource_update_executor.go
  pkg/koordlet/executor/resource_update_executor_test.go
  pkg/koordlet/qosmanager/k8s/k8s.go
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/resmanager_test.go
  pkg/koordlet/util/resourceexecutor/executor.go
  pkg/koordlet/util/resourceexecutor/executor_test.go
  pkg/util/cache/expiration_cache.go
  pkg/util/cache/expiration_cache_test.go
Labels: lgtm, approved, size/M

#875 koord-scheduler: check whether the number of Pods meets minMember first in Coscheduling
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
Labels: lgtm, approved, size/M

#878 koord-scheduler: NodeCPUBindPolicy supports SpreadByPCPUs
  apis/extension/node.go
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/L

#869 koordlet: report aggregate node usage in NodeMetric
  apis/slo/v1alpha1/nodemetric_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/storage.go
  pkg/koordlet/metriccache/util.go
  pkg/koordlet/metriccache/util_test.go
  pkg/koordlet/reporter/config.go
  pkg/koordlet/reporter/config_test.go
  pkg/koordlet/reporter/reporter_test.go
  pkg/koordlet/statesinformer/config.go
  pkg/koordlet/statesinformer/config_test.go
  pkg/koordlet/statesinformer/registry.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/koordlet/statesinformer/states_nodemetric.go
  pkg/koordlet/statesinformer/states_nodemetric_test.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/config_extender_test.go
  pkg/slo-controller/config/config_test.go
  pkg/slo-controller/config/zz_generated.deepcopy.go
Labels: size/XXL, lgtm, approved

#883 koord-scheduler: LoadAware scheduling adds ScoreAccordingProdUsage parameter
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/M

#890 koordlet: fix updateBatch method of executor and update some comments in util
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/util/node.go
  pkg/koordlet/util/pod.go
  pkg/koordlet/util/resourceexecutor/executor.go
Labels: lgtm, approved, size/S

#860 docs: proposal for new repo koordetector
  docs/images/koordetector.jpg
  docs/proposals/20221205-new-repo-koordetector.md
Labels: lgtm, approved, size/L

#879 koordlet: node resource report and common QoS features support cgroups-v2
  pkg/koordlet/config/config.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/collector_test.go
  pkg/koordlet/pleg/pleg.go
  pkg/koordlet/pleg/pleg_test.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resourceexecutor/config.go
  pkg/koordlet/resourceexecutor/config_test.go
  pkg/koordlet/resourceexecutor/executor.go
  pkg/koordlet/resourceexecutor/executor_test.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/reader_test.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/resourceexecutor/updater_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/util/container.go
  pkg/koordlet/util/container_test.go
  pkg/koordlet/util/meminfo.go
  pkg/koordlet/util/node.go
  pkg/koordlet/util/stat.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/cgroup2.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/cgroup_resource_test.go
  pkg/koordlet/util/system/cgroup_test.go
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/resource.go
  pkg/koordlet/util/system/system_file.go
  pkg/koordlet/util/system/util_test_tool.go
Labels: size/XXL, lgtm, approved

#887 koordlet: release feature gates config
  cmd/koordlet/main.go
  config/manager/koordlet.yaml
  pkg/features/koordlet_features.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/koordlet/statesinformer/states_informer_test.go
Labels: lgtm, approved, size/L

#889 koord-descheduler: support loadaware/lowNodeLoad descheduling
  pkg/descheduler/apis/config/register.go
  pkg/descheduler/apis/config/types.go
  pkg/descheduler/apis/config/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/register.go
  pkg/descheduler/apis/config/v1alpha2/types.go
  pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.defaults.go
  pkg/descheduler/apis/config/validation/validation_loadaware.go
  pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
  pkg/descheduler/apis/config/validation/validation_test.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/framework/plugins/defaultevictor/evictor.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/framework/plugins/loadaware/sorter.go
  pkg/descheduler/framework/plugins/loadaware/sorter_test.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
  pkg/descheduler/framework/plugins/registry.go
  pkg/descheduler/framework/testing/framework_helpers.go
  pkg/descheduler/node/node.go
Labels: size/XXL, lgtm, approved

#882 koord-scheduler: LoadAware scheduling support percentile usage
  apis/extension/scheduling.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/plugins/loadaware/helper.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/util/pod_resources_utils.go
Labels: lgtm, approved, size/XL

#892 koordlet: remove deprecated BEReconcile
  pkg/features/koordlet_features.go
  pkg/koordlet/resmanager/be_reconcile.go
  pkg/koordlet/resmanager/be_reconcile_test.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/util/system/cgroup.go
Labels: lgtm, approved, size/XL

#900 koordlet: fix pleg to increase pod sync interval
  pkg/koordlet/pleg/pleg.go
  pkg/koordlet/statesinformer/config.go
  pkg/koordlet/statesinformer/config_test.go
  pkg/koordlet/statesinformer/states_pods.go
Labels: lgtm, approved, size/S

#898 koordlet: Other qos features support cgroups v2
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/metrics_query.go
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resourceexecutor/config.go
  pkg/koordlet/resourceexecutor/executor.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/resctrl_updater.go
  pkg/koordlet/resourceexecutor/resctrl_updater_test.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/resourceexecutor/updater_test.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/util/container.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/resctrl.go
  pkg/koordlet/util/system/resctrl_test.go
  pkg/koordlet/util/system/resource.go
  pkg/util/cpuset/cpuset.go
Labels: size/XXL, lgtm, approved

#902 koordlet: delete deprecated featuregate performance collector
  pkg/features/koordlet_features.go
  pkg/koordlet/metricsadvisor/collector.go
Labels: lgtm, approved, size/S

#726 koordlet:encapsulating reused logics(updatePodCFSQuota,updateContainerCFSQuota)
  pkg/koordlet/resmanager/cpu_burst.go
Labels: lgtm, approved, size/M

#906 koord-scheduler: retrieve reservationInfo from cache first in preFilter hook
  pkg/scheduler/plugins/reservation/hook.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/rcache.go
Labels: lgtm, approved, size/S

#909 koordlet: fix cpi collector return value sequence
  pkg/koordlet/util/perf/perf_linux.go
Labels: size/XS, lgtm, approved

#893 koordlet: Reduce update NodeResourceTopology frequency
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
Labels: lgtm, approved, size/L

#908 koord-scheduler: check if reservation port match the pod
  pkg/scheduler/plugins/reservation/utils.go
  pkg/scheduler/plugins/reservation/utils_test.go
Labels: lgtm, approved, size/L

#905 Koordlet: Feat add more metrics for cpu burst and suppress
  pkg/koordlet/metrics/common.go
  pkg/koordlet/metrics/cpu_burst.go
  pkg/koordlet/metrics/cpu_suppress.go
  pkg/koordlet/metrics/metrics.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_suppress.go
Labels: lgtm, approved, size/L
