Repository koordinator-sh/koordinator, pull requests merged in 2022-08, with the labels that each got.

#392 docs: add ADOPTERS.md of Koordinator
  ADOPTERS.md
Labels: lgtm, approved, size/S

#422 koord-descheduler: implement descheduling configuration
  .licenseignore
  go.mod
  hack/update-codegen.sh
  hack/update-license-header.sh
  pkg/descheduler/apis/config/doc.go
  pkg/descheduler/apis/config/register.go
  pkg/descheduler/apis/config/scheme/scheme.go
  pkg/descheduler/apis/config/types.go
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/conversion.go
  pkg/descheduler/apis/config/v1alpha2/default_plugins.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/doc.go
  pkg/descheduler/apis/config/v1alpha2/register.go
  pkg/descheduler/apis/config/v1alpha2/types.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.defaults.go
  pkg/descheduler/apis/config/validation/validation.go
  pkg/descheduler/apis/config/validation/validation_pluginargs.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
Labels: size/XXL, lgtm, approved

#421 chore: execute staticcheck instead of github action by running golang…
  .github/workflows/ci.yaml
  .golangci.yml
  docs/contributors/good-pr.md
Labels: lgtm, approved, size/S

#353 koord-scheduler: add reservation plugin
  apis/scheduling/config/register.go
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/defaults.go
  apis/scheduling/config/v1beta2/register.go
  apis/scheduling/config/v1beta2/types.go
  apis/scheduling/config/v1beta2/zz_generated.conversion.go
  apis/scheduling/config/v1beta2/zz_generated.deepcopy.go
  apis/scheduling/config/v1beta2/zz_generated.defaults.go
  apis/scheduling/config/zz_generated.deepcopy.go
  apis/scheduling/v1alpha1/reservation_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  cmd/koord-scheduler/app/options/options.go
  cmd/koord-scheduler/app/server.go
  cmd/koord-scheduler/main.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
  config/samples/scheduling_v1alpha1_reservation.yaml
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_reservation.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_scheduling_client.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/reservation.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/interface.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/reservation.go
  pkg/client/listers/scheduling/v1alpha1/expansion_generated.go
  pkg/client/listers/scheduling/v1alpha1/reservation.go
  pkg/scheduler/eventhandlers/internal_handler.go
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/hook.go
  pkg/scheduler/plugins/reservation/hook_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
  pkg/scheduler/plugins/reservation/rpod.go
  pkg/scheduler/plugins/reservation/utils.go
  pkg/scheduler/plugins/reservation/utils_test.go
Labels: size/XXL, lgtm, approved

#423 koord-descheduler: implement descheduling framework
  go.mod
  pkg/descheduler/apis/config/v1alpha2/default_plugins.go
  pkg/descheduler/controllers/options/manager.go
  pkg/descheduler/controllers/registry.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/framework/plugins/defaultevictor/evictor.go
  pkg/descheduler/framework/plugins/registry.go
  pkg/descheduler/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/descheduler/framework/runtime/framework.go
  pkg/descheduler/framework/runtime/registry.go
  pkg/descheduler/framework/types.go
  pkg/descheduler/informers/factory.go
  pkg/descheduler/informers/generic.go
  pkg/descheduler/metrics/metrics.go
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/profile/profile.go
  pkg/descheduler/test/test_utils.go
  pkg/descheduler/utils/pod.go
  pkg/descheduler/utils/pod_test.go
  pkg/descheduler/utils/predicates.go
  pkg/descheduler/utils/predicates_test.go
  pkg/descheduler/utils/priority.go
  pkg/descheduler/utils/priority_test.go
Labels: size/XXL, lgtm, approved

#424 [adopter] add xiaohongshu as koordinator adopter
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#425 add koord-descheduler
  .github/workflows/ci.yaml
  .goreleaser.yaml
  .goreleaser/koord-descheduler.dockerfile
  Makefile
  cmd/koord-descheduler/app/config/config.go
  cmd/koord-descheduler/app/options/configfile.go
  cmd/koord-descheduler/app/options/insecure_serving.go
  cmd/koord-descheduler/app/options/options.go
  cmd/koord-descheduler/app/options/scheme.go
  cmd/koord-descheduler/app/server.go
  cmd/koord-descheduler/main.go
  docker/koord-descheduler.dockerfile
Labels: size/XXL, lgtm, approved

#428 fix reservation on pod patch failed
  apis/extension/scheduling.go
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/rcache.go
  pkg/scheduler/plugins/reservation/rpod.go
  pkg/scheduler/plugins/reservation/utils.go
Labels: lgtm, approved, size/L

#431 fix reservation on mutil-scheduler
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/reservation/rpod.go
  pkg/scheduler/plugins/reservation/utils_test.go
Labels: lgtm, approved, size/L

#432 fix koord-descheduler initialize profile error
  pkg/descheduler/OWNERS
  pkg/descheduler/apis/config/v1alpha2/default_plugins.go
Labels: size/XS, lgtm, approved

#409 api: add Gang api
  apis/extension/scheduling.go
Labels: lgtm, approved, size/M

#433 koord-scheduler: compatible with Pods using kubelet static CPU manager policy
  apis/extension/node.go
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
  pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
  pkg/scheduler/plugins/nodenumaresource/node_numa_info_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
Labels: lgtm, approved, size/L

#434 koord-scheduler: support kubelet cpu manager policy
  apis/extension/node.go
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/L

#426 docs: add maturity level in adopters.md
  ADOPTERS.md
Labels: lgtm, approved, size/S

#438 koord-descheduler: release Reservation when PodMigrationJob completes or is deleted
  pkg/descheduler/controllers/migration/controller.go
Labels: size/S

#442 koord-scheduler: improve reservation validation
  apis/scheduling/v1alpha1/reservation_types.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rpod.go
Labels: lgtm, approved, size/L

#444 bugfix: skip when pod sandbox not found
  pkg/runtimeproxy/server/cri/criserver.go
Labels: size/XS

#445 bugfix: avoid pod terminating in docker
  pkg/runtimeproxy/server/docker/handler.go
  pkg/runtimeproxy/server/docker/server.go
Labels: lgtm, approved, size/S

#350 refactor extended resource with `kubernetes.io` namespace
  docs/proposals/api-machinery/20220707-rename-extended-resource.md
Labels: lgtm, approved, size/M

#398 add multi-hierarchy-elastic-quota-management
  docs/images/quotaguarantee1.jpg
  docs/images/quotaguarantee2.jpg
  docs/images/quotatree.jpg
  docs/images/quotatree1.jpg
  docs/images/quotatree2.jpg
  docs/images/quotatree3.jpg
  docs/images/quotatree4.jpg
  docs/images/runtimequota1.jpg
  docs/images/runtimequota2.jpg
  docs/images/runtimequota3.jpg
  docs/images/runtimequota4.jpg
  docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md
Labels: size/L

#449 ci: rolling back to golangci-lint 1.47.3
  .github/workflows/ci.yaml
Labels: size/XS, lgtm, approved

#448 adjusted the description of elastic quota
  docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md
Labels: size/M

#452 koord-scheduler: adapt to different cpuset scheduling protocols
  apis/extension/resource.go
  apis/extension/resource_test.go
  pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
Labels: lgtm, approved, size/L

#447 apis: add allocateOnce in reservation
  apis/scheduling/v1alpha1/reservation_types.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
  docs/proposals/scheduling/20220609-resource-reservation.md
Labels: lgtm, approved, size/M

#453 rename prefix of extended resource
  Makefile
  apis/extension/constants.go
  apis/extension/resource.go
  pkg/koordlet/metricsadvisor/be_collector_test.go
  pkg/koordlet/resmanager/be_reconcile_test.go
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/util/container.go
  pkg/util/pod_test.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/L

#456 koord-descheduler: complete configuration
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/validation/validation.go
  pkg/descheduler/apis/config/validation/validation_pluginargs.go
  pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
  pkg/descheduler/apis/config/validation/validation_test.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
Labels: lgtm, approved, size/L

#461 ci: extend golangci-lint timeout to 10m
  .github/workflows/ci.yaml
  .golangci.yml
  Makefile
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/reporter/reporter_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/slo-controller/noderesource/nodemetric_event_handler_test.go
  pkg/util/container_test.go
  pkg/util/node_test.go
  pkg/webhook/pod/mutating/mutating_handler.go
Labels: lgtm, approved, size/M

#455 fix: use uint32 to record process id
  pkg/koordlet/metricsadvisor/collector_gpu_linux.go
  pkg/koordlet/metricsadvisor/collector_gpu_linux_test.go
  pkg/util/container.go
  pkg/util/container_test.go
Labels: lgtm, approved, size/M

#463 ci: remove cache when setup go
  .github/workflows/ci.yaml
Labels: size/XS

#240 ci: add codeql analysis in workflows
  .github/workflows/codeql.yml
Labels: lgtm, approved, size/M

#465 ADOPTERS: add iQIYI
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#469 koord-scheduler: export NodeNUMAInfoCache and getAvailableCPUs
  pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/M

#471 koord-scheduler: abstract GetPodQoSClass
  pkg/scheduler/plugins/nodenumaresource/plugin.go
Labels: size/XS, lgtm, approved

#472 add extended resource schedule plugin for compatibility
  cmd/koord-scheduler/main.go
  pkg/scheduler/plugins/batchresource/batch_resource.go
  pkg/scheduler/plugins/batchresource/batch_resource_test.go
Labels: lgtm, approved, size/L

#473 set kubernetes.io/batch-cpu as milli-core
  docs/proposals/api-machinery/20220707-rename-extended-resource.md
  pkg/koordlet/metricsadvisor/be_collector_test.go
  pkg/koordlet/resmanager/be_reconcile_test.go
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/util/container.go
  pkg/util/pod_test.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
  pkg/webhook/pod/validating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/L

#458 koord-descheduler: init evictor plugin first
  pkg/descheduler/framework/runtime/framework.go
Labels: lgtm, approved, size/L

#470 feature: support read args from KubeletConfiguration
  go.mod
  go.sum
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/util/system/common_linux.go
  pkg/util/system/common_linux_test.go
  pkg/util/system/common_unsupported.go
  pkg/util/system/cpu_manager_linux.go
  pkg/util/system/cpu_manager_unsupported.go
Labels: size/L

#474 koord-scheduler: fix stale reservation status
  apis/extension/scheduling.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
  pkg/scheduler/plugins/reservation/utils.go
Labels: size/XXL, lgtm, approved

#446 bugfix: fix exec exit with 126
  .golangci.yml
  go.mod
  pkg/runtimeproxy/server/docker/handler_test.go
  pkg/runtimeproxy/server/docker/server.go
  pkg/util/httputil/reverseproxy.go
  pkg/util/httputil/reverseproxy_test.go
Labels: size/XXL, lgtm, approved

#476 koord-scheduler: fix typo
  pkg/scheduler/plugins/batchresource/batch_resource.go
Labels: size/S

#475 koord-descheduler: add tests for framework runtime
  pkg/descheduler/framework/runtime/framework.go
  pkg/descheduler/framework/runtime/framework_test.go
  pkg/descheduler/framework/runtime/registry.go
  pkg/descheduler/framework/runtime/registry_test.go
Labels: lgtm, approved, size/XL

#479 [NO MERGE] ci: remove codeql from workflows
  .github/workflows/codeql.yml
Labels: lgtm, approved, size/M

#480 docs: format markdown
  docs/proposals/api-machinery/20220707-rename-extended-resource.md
Labels: lgtm, approved, size/M

#481 ci: add codeql in pipeline workflows
  .github/workflows/codeql.yml
Labels: size/M

#478 koord-scheduler: reservation support allocateOnce
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/hook.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
  pkg/scheduler/plugins/reservation/utils.go
Labels: lgtm, approved, size/L

#484 koord-runtime-proxy: regard empty string for CpusetCpus and CpusetMem…
  pkg/runtimeproxy/resexecutor/cri/utils.go
Labels: lgtm, approved, size/S

#485 refactor batch node resource update
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_test.go
Labels: lgtm, approved, size/L

#487 koord-runtime-proxy: regard empty string for CpusetCpus and CpusetMem…
  pkg/runtimeproxy/resexecutor/cri/utils.go
Labels: lgtm, approved, size/S

#486 ci: use fast-test to skip redundant steps in workflows
  .github/workflows/ci.yaml
  Makefile
Labels: size/XS, lgtm, approved

#488 mv container extend resource to independent file
  pkg/koordlet/resmanager/be_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/util/container.go
  pkg/util/container_ext_resource.go
  pkg/util/container_test.go
  pkg/util/pod.go
Labels: lgtm, approved, size/L

#494 koord-descheduler: enable allocateOnce when creating Reservation
  apis/scheduling/v1alpha1/pod_migration_job_types.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/reservation/interpreter.go
  pkg/descheduler/controllers/migration/reservation/reservation.go
  pkg/descheduler/controllers/migration/reservation/types.go
  pkg/descheduler/controllers/migration/reservation/util.go
Labels: lgtm, approved, size/L

#491 support node extended resource plugin
  go.mod
  go.sum
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/config_extender.go
  pkg/slo-controller/config/config_extender_test.go
  pkg/slo-controller/config/zz_generated.deepcopy.go
  pkg/slo-controller/noderesource/extender_plugin.go
  pkg/slo-controller/noderesource/extender_plugin_test.go
  pkg/slo-controller/noderesource/noderesource.go
Labels: lgtm, approved, size/L

#495 fix metric-expire-seconds usage
  pkg/koordlet/metriccache/config.go
Labels: size/XS, lgtm, approved

#497 adopters: add Quwan
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#500 koord-descheduler: fix incorrect handling of Reservation's status
  apis/scheduling/v1alpha1/pod_migration_job_types.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/reservation/reservation.go
Labels: size/L

#501 koord-scheduler: fix succeeded reservation GC and unschedulable retry
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/eventhandlers/internal_handler.go
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
  pkg/scheduler/plugins/reservation/utils.go
Labels: size/L

#503 feature: support inject env in proxy
  apis/runtime/v1alpha1/api.pb.go
  apis/runtime/v1alpha1/api.proto
  apis/runtime/v1alpha1/api_grpc.pb.go
  go.mod
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/container_test.go
  pkg/runtimeproxy/server/docker/handler.go
  pkg/runtimeproxy/server/docker/server.go
  pkg/runtimeproxy/server/docker/utils.go
  pkg/runtimeproxy/server/docker/utils_test.go
Labels: lgtm, approved, size/L

#504 refactor: move GeneratePodPatch under util package
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_helper.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/utils.go
  pkg/util/cpuset.go
  pkg/util/cpuset_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/XL

#506 fix: correct misspells in pkg/koordlet/metriccache
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/storage.go
  pkg/koordlet/metriccache/storage_test.go
Labels: size/XS, lgtm, approved

#511 koord-runtime-proxy: add more test cases
  pkg/runtimeproxy/resexecutor/cri/pod.go
  pkg/runtimeproxy/resexecutor/cri/pod_test.go
  pkg/runtimeproxy/store/manager.go
  pkg/runtimeproxy/store/manager_test.go
  pkg/runtimeproxy/utils/utils_test.go
Labels: lgtm, approved, size/L

#513 apis: add DeviceAllocations and methods
  apis/extension/resource.go
  apis/extension/scheduling.go
Labels: lgtm, approved, size/M

#516 koord-scheduler: fix succeeded reservation in scheduler cache
  codecov.yml
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/hook_test.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/M

#519 koord-descheduler: stop migration when reserved on the same node
  apis/extension/scheduling.go
  apis/scheduling/v1alpha1/pod_migration_job_types.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
Labels: lgtm, approved, size/L

#520 koord-descheduler: support evict flow control to ensure availability
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/validation/validation_pluginargs.go
  pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/evictor/interpreter.go
Labels: lgtm, approved, size/M

#518 koord-manager: record configmap and pod qos unmarshal failed events
  cmd/koord-manager/main.go
  pkg/slo-controller/config/colocation_cm_event_handler.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/nodemetric/nodemetric_controller_test.go
  pkg/slo-controller/noderesource/nodemetric_event_handler_test.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
Labels: lgtm, approved, size/L

#507 koord-scheduler: refactor NodeNUMAResource plugin
  cmd/koord-scheduler/app/config/config.go
  cmd/koord-scheduler/app/options/options.go
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_manager.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
  pkg/scheduler/plugins/nodenumaresource/node_numa_info_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_helper.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
Labels: size/XXL, lgtm, approved

#522 koord-descheduler: control the maximum number of migrations to ensure availability
  .licenseignore
  apis/scheduling/v1alpha1/pod_migration_job_types.go
  cmd/koord-descheduler/app/options/scheme.go
  cmd/koord-descheduler/app/server.go
  config/crd/bases/scheduling.koordinator.sh_podmigrationjobs.yaml
  docs/proposals/scheduling/20220701-pod-migration-job.md
  go.mod
  go.sum
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/validation/validation_pluginargs.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
  pkg/descheduler/controllers/migration/controllerfinder/pods_finder.go
  pkg/descheduler/controllers/migration/filter.go
  pkg/descheduler/controllers/migration/util/util.go
  pkg/descheduler/fieldindex/register.go
Labels: size/XXL, lgtm, approved

#517 feature: support inject NVIDIA_VISIBLE_DEVICES env
  apis/extension/scheduling.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/gpu/gpu.go
  pkg/koordlet/runtimehooks/hooks/gpu/gpu_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
Labels: lgtm, approved, size/L

#460 fix: Walkfunc should check the err
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
Labels: size/XS, lgtm, approved

#505 runtime-hooks: add auto register hooks
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/config_test.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/proxyserver/server.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/runtimeproxy/config/config.go
  pkg/util/system/config.go
  pkg/util/system/config_test.go
Labels: lgtm, approved, size/L

#529 qos grep control extension
  apis/extension/pod.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/configextensions/pod_qos_control.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/pod_qos_control_test.go
  pkg/koordlet/resmanager/resmanager.go
Labels: lgtm, approved, size/L

#526 Add runtime hooks stage config flag
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/config_test.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/proxyserver/server.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
Labels: lgtm, approved, size/S

#531 docs: update fine grained device proposal
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Labels: lgtm, approved, size/M

#535 chore: update tools version
  Makefile
Labels: size/XS, lgtm, approved

#537 docs: reformat adopters list
  ADOPTERS.md
Labels: lgtm, approved, size/S

#515 add quotaTreeWrapper and elasticQuota API
  apis/extension/elastic_quota.go
  apis/scheduling/config/register.go
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/defaults.go
  apis/scheduling/config/v1beta2/register.go
  apis/scheduling/config/v1beta2/types.go
  apis/scheduling/config/v1beta2/zz_generated.conversion.go
  apis/scheduling/config/v1beta2/zz_generated.deepcopy.go
  apis/scheduling/config/v1beta2/zz_generated.defaults.go
  apis/scheduling/config/validation/validation_pluginargs.go
  apis/scheduling/config/zz_generated.deepcopy.go
  docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md
  go.mod
  go.sum
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_tree_wrapper.go
  pkg/scheduler/plugins/elasticquota/core/quota_tree_wrapper_test.go
Labels: size/XXL, lgtm, approved

#532 koord-scheduler: optimize the process after reservation scheduling fails
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/utils.go
  pkg/util/utils.go
Labels: lgtm, approved, size/L

#540 fix bug: modify unit test file path to temp dir
  pkg/koordlet/runtimehooks/runtimehooks_test.go
Labels: size/XS, lgtm, approved

#542 ci: support aliyun hangzhou registry
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/S

#538 koord-scheduler: add coscheduling plugin args
  apis/scheduling/config/register.go
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/defaults.go
  apis/scheduling/config/v1beta2/register.go
  apis/scheduling/config/v1beta2/types.go
  apis/scheduling/config/v1beta2/zz_generated.conversion.go
  apis/scheduling/config/v1beta2/zz_generated.deepcopy.go
  apis/scheduling/config/v1beta2/zz_generated.defaults.go
  apis/scheduling/config/validation/validation_pluginargs.go
  apis/scheduling/config/zz_generated.deepcopy.go
Labels: lgtm, approved, size/L

#543 Update 20220629-fine-grained-device-scheduling.md
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Labels: size/XS, lgtm, approved

#547 koord-scheduler: export getDefaultNUMAAllocateStrategy
  pkg/scheduler/plugins/nodenumaresource/plugin.go
Labels: size/XS, lgtm, approved

#545 koord-scheduler: support API Services
  cmd/koord-scheduler/app/config/config.go
  cmd/koord-scheduler/app/options/options.go
  cmd/koord-scheduler/app/server.go
  go.mod
  go.sum
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/services/services.go
  pkg/scheduler/frameworkext/services/types.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager.go
  pkg/scheduler/plugins/nodenumaresource/cpuset.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
Labels: lgtm, approved, size/XL

#548 chore: downgrade CUDA version to 11.2.2
  .goreleaser/koordlet.dockerfile
  docker/koordlet.dockerfile
Labels: size/XS, lgtm, approved

#549 koord-scheduler: support custom SharedLister
  pkg/scheduler/frameworkext/framework_extender.go
Labels: lgtm, approved, size/S

#553 fix container cgroup comment
  pkg/util/container.go
Labels: size/XS, lgtm, approved

#555 koord-scheduler: fix CPUTopologyManager get&update race condition
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
Labels: lgtm, approved, size/M

#551 koord-scheduler: CPU allocate algorithm supports maxRefCount
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_manager.go
Labels: lgtm, approved, size/L

#554 apis: update Device CRD fields
  apis/scheduling/v1alpha1/device_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
Labels: lgtm, approved, size/M

#558 koord-scheduler: fix coSchedulingArgs json name
  apis/scheduling/config/types.go
  apis/scheduling/config/v1beta2/types.go
Labels: size/XS, lgtm, approved

#552 support Reservation select order
  apis/extension/scheduling.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/reservation/util.go
  pkg/scheduler/plugins/reservation/hook.go
  pkg/scheduler/plugins/reservation/hook_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
Labels: lgtm, approved, size/XL

#559 koord-descheduler: fix failed evict with StatefulSet Pod
  cmd/koord-descheduler/app/server.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/controllerfinder/pods_finder.go
  pkg/descheduler/controllers/migration/filter.go
  pkg/descheduler/fieldindex/register.go
Labels: lgtm, approved, size/L

#563 koord-descheduler: fix UT conflict
  pkg/descheduler/controllers/migration/controller_test.go
Labels: lgtm, approved, size/M

#550 koord-scheduler: improve reservation compatibility
  go.mod
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/hook.go
  pkg/scheduler/plugins/reservation/hook_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
  pkg/scheduler/plugins/reservation/rpod.go
  pkg/scheduler/plugins/reservation/utils.go
  pkg/scheduler/plugins/reservation/utils_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
  pkg/util/reservation.go
  pkg/util/reservation_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: size/XXL, lgtm, approved

#564 kood-scheduler: fix Reservation Score divide by zero
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
Labels: lgtm, approved, size/M

#565 koord-scheduler: fix Reservation Score divide by zero with some empty…
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
Labels: lgtm, approved, size/M
