Repository koordinator-sh/koordinator, pull requests merged in 2022-11, with the labels that each got.

#770 koord-scheduler: export client-go metrics
  cmd/koord-scheduler/main.go
Labels: size/XS, lgtm, approved

#763 koord-manager: remove the quota webhook's dependency on koord-scheduler
  pkg/webhook/elasticquota/quota_handler.go
  pkg/webhook/elasticquota/quota_info.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/L

#682 feature: support pod skip runtime hook with specified label
  cmd/koord-runtime-proxy/options/options.go
  config/manager/koordlet.yaml
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/pod.go
  pkg/runtimeproxy/resexecutor/cri/utils.go
  pkg/runtimeproxy/server/docker/handler.go
  pkg/runtimeproxy/server/types/docker_types.go
Labels: lgtm, approved, size/M

#765 no processing for successfully exited pods
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
Labels: size/XS, lgtm, approved

#772 koord-manager: add containerFilterFunc in requestLimitValidator
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
  pkg/webhook/pod/validating/request_limit_validator.go
Labels: lgtm, approved, size/M

#764 koord-scheduler: only allow the leader to initialize controllers
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/controllers.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/controller_test.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
Labels: lgtm, approved, size/L

#775 koord-scheduler: fix typo error in framework_extender.go
  pkg/scheduler/frameworkext/framework_extender.go
Labels: size/XS, lgtm, approved

#779 koord-manager: update RBAC
  config/rbac/role.yaml
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
Labels: lgtm, approved, size/S

#784 koord-scheduler: fix ElasticQuota plugin don't clean node cache when node delete
  pkg/scheduler/plugins/elasticquota/node_handler.go
Labels: size/XS, lgtm, approved

#785 ADOPTERS: add 360 as stable user
  ADOPTERS.md
Labels: lgtm, approved, size/S

#787 koord-manager: make webhookConfigurationName configurable
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/util.go
Labels: lgtm, approved, size/M

#782 koordlet: fix cpi collector bad fd err
  pkg/koordlet/metricsadvisor/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
  pkg/util/perf/perf_linux.go
  pkg/util/perf/perf_linux_test.go
  pkg/util/perf/perf_unsupported.go
  pkg/util/stat.go
  pkg/util/stat_test.go
Labels: lgtm, approved, size/M

#788 koord-scheduler: fix ElasticQuota plugin failover panic
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: lgtm, approved, size/S

#792 chore: split util/pod.go by function
  pkg/util/pod.go
  pkg/util/pod_qos_utils.go
  pkg/util/pod_qos_utils_test.go
  pkg/util/pod_resources_utils.go
  pkg/util/pod_resources_utils_test.go
  pkg/util/pod_test.go
Labels: lgtm, approved, size/XL

#720 docs: proposal koordlet support cgroups v2
  docs/images/resource-executor.svg
  docs/images/system-resource.svg
  docs/proposals/koordlet/20221018-koordlet-support-cgroups-v2.md
Labels: size/XXL, lgtm, approved

#714 fix golang lint errors in newer version golang-lint
  pkg/descheduler/framework/runtime/framework_test.go
  pkg/koordlet/executor/resource_update_executor.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
  pkg/slo-controller/config/config.go
  pkg/util/reservation.go
  pkg/util/utils.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
Labels: lgtm, approved, size/L

#778 api: pass extended resource spec via annotation
  apis/extension/resource.go
  apis/extension/resource_test.go
Labels: lgtm, approved, size/L

#793 chore: refactor cpuset in package for code reuse
  .licenseignore
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_manager.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
  pkg/util/container.go
  pkg/util/container_test.go
  pkg/util/cpuset.go
  pkg/util/cpuset/cpuset.go
  pkg/util/cpuset/cpuset_test.go
  pkg/util/cpuset/helper.go
  pkg/util/cpuset/helper_test.go
  pkg/util/node.go
Labels: lgtm, approved, size/XL

#791 koord-descheduler: add validator and tests for descheduler profile
  pkg/descheduler/framework/runtime/framework.go
  pkg/descheduler/framework/runtime/framework_test.go
  pkg/descheduler/profile/profile.go
  pkg/descheduler/profile/profile_test.go
Labels: lgtm, approved, size/L

#789 koord-scheduler: exclude DefaultQuota and SystemQuota when updating quota tree
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
Labels: lgtm, approved, size/S

#794 chore: remove scheduler Pod Update permissions
  config/rbac/scheduler_role.yaml
Labels: size/XS, lgtm, approved

#742 proposal: enhanced scheduler extension
  docs/images/scheduler-extension.jpg
  docs/proposals/scheduling/20220513-enhanced-scheduler-extension.md
Labels: lgtm, approved, size/L

#797 webhook: pod mutating handler add extended resource spec
  apis/extension/resource.go
  apis/extension/resource_test.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/extended_resource_spec.go
  pkg/webhook/pod/mutating/extended_resource_spec_test.go
  pkg/webhook/pod/mutating/mutating_handler.go
Labels: lgtm, approved, size/L

#796 QoS Manager Framework
  cmd/koordlet/main.go
  pkg/features/koordlet_features.go
  pkg/koordlet/common/reason/reason.go
  pkg/koordlet/common/testutil/k8s.go
  pkg/koordlet/common/types/constants.go
  pkg/koordlet/common/utils/containers.go
  pkg/koordlet/common/utils/pod.go
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/qosmanager/config/config.go
  pkg/koordlet/qosmanager/config/config_test.go
  pkg/koordlet/qosmanager/k8s/k8s.go
  pkg/koordlet/qosmanager/manager.go
  pkg/koordlet/qosmanager/manager_test.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query_test.go
  pkg/koordlet/qosmanager/plugins/context.go
  pkg/koordlet/qosmanager/plugins/plugin.go
Labels: size/XXL, lgtm, approved

#802 Add FillZpp into approvers alias
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#798 proposal: update Enhanced Scheduler Extension
  docs/images/scheduler-extension.jpg
  docs/proposals/scheduling/20220513-enhanced-scheduler-extension.md
Labels: lgtm, approved, size/S

#804 Add honpey into approvers alias
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#803 Add zwzhang0107 into approvers alias
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#805 Add saintube into approvers alias
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#799 fixed quota deep copy and cyclestate
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
Labels: lgtm, approved, size/S

#809 Add jasonliu747 into approvers alias
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#812 Add buptcozy into approvers alias
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#813 Add ZYecho into approvers alias
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#814 koordlet: add flag to support disable querying kubelet configuration
  pkg/koordlet/statesinformer/config.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
Labels: lgtm, approved, size/L, area/koordlet

#816 ci: add cache to reduce the time of codeql
  .github/workflows/codeql.yml
  Makefile
Labels: lgtm, approved, size/S

#818 ci: simplify go build command
  .github/workflows/ci.yaml
Labels: size/XS, lgtm, approved

#810 koord-scheduler: fix errors caused by incorrect lock in ElasticQuota
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
Labels: size/XS, lgtm, approved, area/koord-scheduler

#811 koord-descheduler: evict pod by perferred groupverison
  pkg/descheduler/controllers/migration/evictor/evictor_delete.go
  pkg/descheduler/controllers/migration/evictor/evictor_native.go
  pkg/descheduler/controllers/migration/evictor/interpreter.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/evictions/utils/utils.go
  pkg/descheduler/framework/plugins/defaultevictor/evictor.go
Labels: lgtm, approved, size/L, area/koord-descheduler

#819 koord-scheduler: fix elasticQuota ut fail
  pkg/scheduler/plugins/elasticquota/plugin.go
Labels: size/XS, lgtm, approved

#831 Add bi-weekly community meeting
  README-zh_CN.md
  README.md
Labels: size/XS, lgtm, approved

#821 Support the method of custom querying quota name
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/webhook/elasticquota/pod_check.go
Labels: lgtm, approved, size/M

#832 koord-scheduler: make initialization scalable
  cmd/koord-scheduler/main.go
Labels: lgtm, approved, size/M

#830 koord-scheduler: support force sync data from informer
  pkg/scheduler/frameworkext/helper/synced_eventhandler.go
  pkg/scheduler/frameworkext/helper/synced_eventhandler_test.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_handler.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/pod_handler.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
  pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
  pkg/scheduler/plugins/reservation/plugin.go
Labels: lgtm, approved, size/XL

#833 koord-manager: make initialization scalable
  cmd/koord-manager/main.go
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
Labels: lgtm, approved, size/M

#774 koordlet: add runtime hook plugin batch resource
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/util/container.go
  pkg/util/pod.go
  pkg/util/pod_resources_utils.go
  pkg/util/system/cgroup_resource.go
Labels: size/XXL, lgtm, approved, area/koordlet

#790 koordlet: PSI collector and use Prometheus to record interference metrics
  pkg/features/koordlet_features.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/metriccache/storage.go
  pkg/koordlet/metriccache/storage_tables.go
  pkg/koordlet/metriccache/storage_test.go
  pkg/koordlet/metriccache/util.go
  pkg/koordlet/metriccache/util_test.go
  pkg/koordlet/metrics/common.go
  pkg/koordlet/metrics/cpi.go
  pkg/koordlet/metrics/metrics.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metrics/psi.go
  pkg/koordlet/metrics/psi_test.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/config.go
  pkg/koordlet/metricsadvisor/config_test.go
  pkg/koordlet/metricsadvisor/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
  pkg/koordlet/metricsadvisor/performance_collector_unsupported.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query.go
  pkg/util/container.go
  pkg/util/container_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
  pkg/util/psi.go
  pkg/util/psi_test.go
  pkg/util/stat.go
  pkg/util/stat_test.go
  pkg/util/system/cgroup_resource.go
  pkg/util/system/psi_file.go
  pkg/util/system/psi_file_test.go
Labels: size/XXL, lgtm, approved, area/koordlet

#834 koordlet: refactor cgroup resource
  pkg/koordlet/executor/resource_update_executor_test.go
  pkg/koordlet/executor/types.go
  pkg/koordlet/executor/types_test.go
  pkg/koordlet/metricsadvisor/be_collector_test.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
  pkg/util/container.go
  pkg/util/container_test.go
  pkg/util/meminfo_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
  pkg/util/stat.go
  pkg/util/stat_test.go
  pkg/util/system/cgroup.go
  pkg/util/system/cgroup_resource.go
  pkg/util/system/cgroup_resource_test.go
  pkg/util/system/cgroup_test.go
  pkg/util/system/config.go
  pkg/util/system/config_test.go
  pkg/util/system/resource.go
  pkg/util/system/system_file.go
  pkg/util/system/util_test_tool.go
  pkg/util/system/validator.go
  pkg/util/system/validator_test.go
  pkg/util/system/version.go
  pkg/util/system/version_test.go
Labels: size/XXL, lgtm, approved

#841 koord-scheduler: ElasticQuota uses Pod Namespace/Name as cache key
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Labels: lgtm, approved, size/M

#847 koord-scheduler: support log filtering failure reasons as needed
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/debug.go
  pkg/scheduler/frameworkext/debug_test.go
  pkg/scheduler/frameworkext/framework_extender.go
Labels: lgtm, approved, size/M

#851 utils: Fix words typo in error message
  pkg/util/utils.go
Labels: size/XS, lgtm, approved
