Repository koordinator-sh/koordinator, pull requests merged in 2022-05, with the labels that each got.

#116 ✨ Remove deprecated go get from Makefile
  Makefile
Labels: lgtm, approved, size/M

#118 Support cpu burst strategy
  pkg/koordlet/resmanager/reason.go
  pkg/koordlet/resmanager/resource_update_executor_test.go
  pkg/koordlet/resmanager/types.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/constants.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
Labels: lgtm, approved, size/XL

#119 🌱 add unit test for memory evict feature
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/runtime/handler/fake_runtime.go
  pkg/util/container.go
  vendor/k8s.io/cri-api/pkg/apis/testing/fake_image_service.go
  vendor/k8s.io/cri-api/pkg/apis/testing/fake_runtime_service.go
  vendor/k8s.io/cri-api/pkg/apis/testing/utils.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#110 Introduce cri request parsing/generate-hook-request/checkpoing logic
  pkg/runtime-manager/resource-executor/cri/container.go
  pkg/runtime-manager/resource-executor/cri/pod.go
  pkg/runtime-manager/resource-executor/cri/utils.go
  pkg/runtime-manager/resource-executor/resource_executor.go
  pkg/runtime-manager/server/cri/criserver.go
  pkg/runtime-manager/server/utils/utils.go
  pkg/runtime-manager/store/manager.go
  pkg/runtime-manager/utils/utils.go
Labels: lgtm, approved, size/XL

#126 📖 add changelog for v0.3
  CHANGELOG.md
Labels: lgtm, approved, size/M

#127 Activate rdt res_ctrl in resmanager
  pkg/koordlet/resmanager/resmanager.go
Labels: size/XS, lgtm, approved

#129 fix(koordlet): fix be container memory request
  pkg/util/container.go
Labels: size/XS, lgtm, approved

#130 chore: add cache for staticcheck
  .github/workflows/ci.yaml
Labels: size/XS, lgtm, approved

#123 add koordlet runtime design
  docs/desgin-archive/koordlet-runtime-hooks.md
  docs/images/runtime-hooks-arch.svg
  docs/images/runtime-hooks-modules.svg
  docs/images/runtime-hooks-working-mode.svg
Labels: lgtm, approved, size/M

#132 feat(koordlet): support memoryEvictLowerPercent in memory evict
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resmanager/memory_evict_test.go
Labels: lgtm, approved, size/L

#133 🌱 add validation for CRD
  apis/slo/v1alpha1/nodeslo_types.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Labels: lgtm, approved, size/S

#137 test(controller): add unit test for resource_calculator
  pkg/slo-controller/config/config.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: lgtm, approved, size/XL

#142 Modify memqos wmark ratio doc desc
  apis/slo/v1alpha1/nodeslo_types.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Labels: lgtm, approved, size/S

#134 test(controller): add unit test for `config/config.go`
  pkg/slo-controller/config/config_test.go
Labels: lgtm, approved, size/L

#138 test(controller): add unit test for noderesource
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_test.go
Labels: lgtm, approved, size/XL

#122 add scaffold of runtime hooks
  apis/extension/qos.go
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/rule/inject.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/koordlet/runtimehooks/server/server.go
  pkg/koordlet/runtimehooks/server/service.go
  pkg/util/system/cgroup_resource.go
  vendor/google.golang.org/grpc/reflection/README.md
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.proto
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/reflection/serverreflection.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#135 proposal load-aware scheduling plugin
  docs/images/load-aware-scheduling-arch.svg
  docs/proposals/scheduling/20220510-load-aware-scheduling.md
Labels: lgtm, approved, size/L

#151 test: use `T.TempDir` to create temporary test directory
  pkg/koordlet/audit/auditor_test.go
  pkg/koordlet/audit/event_logger_test.go
  pkg/koordlet/audit/logger_test.go
  pkg/koordlet/pleg/watcher_linux_test.go
  pkg/koordlet/resmanager/be_reconcile_test.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/resmanager/resource_update_executor_test.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/runtime/handler/containerd_runtime_test.go
  pkg/runtime/handler/docker_runtime_test.go
  pkg/runtime/runtime_test.go
  pkg/util/container_test.go
  pkg/util/meminfo_test.go
  pkg/util/pod_test.go
  pkg/util/stat_test.go
  pkg/util/system/cgroup_driver_linux_test.go
  pkg/util/system/cgroup_test.go
  pkg/util/system/common_linux_test.go
  pkg/util/system/resctrl_linux_test.go
  pkg/util/system/resctrl_test.go
  pkg/util/system/util_test_tool.go
  pkg/util/system/util_test_tool_test.go
  pkg/util/system/version_test.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/L

#155 update LoadAwareScheduling proposal
  docs/proposals/scheduling/20220510-load-aware-scheduling.md
Labels: lgtm, approved, size/S

#156 chore: fix test tempdir generation
  pkg/util/system/util_test_tool.go
Labels: size/XS, lgtm, approved

#157 koordlet: support NodeMetricCollectPolicy
  apis/slo/v1alpha1/nodemetric_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
  pkg/koordlet/reporter/reporter.go
  pkg/koordlet/reporter/reporter_test.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/config_test.go
  pkg/slo-controller/nodemetric/collect_policy.go
  pkg/slo-controller/nodemetric/collect_policy_test.go
  pkg/slo-controller/nodemetric/nodemetric.go
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/nodemetric/nodemetric_controller_test.go
  pkg/slo-controller/nodemetric/suite_test.go
Labels: lgtm, approved, size/XL

#153 add cpu qos and mv nodeslo informer to states informer
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/koordlet.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/resmanager_test.go
  pkg/koordlet/resmanager/resource_update_executor_test.go
  pkg/koordlet/resmanager/strategy_util_test.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/koordlet/runtimehooks/server/service.go
  pkg/koordlet/statesinformer/mockstatesinformer/mock.go
  pkg/koordlet/statesinformer/register.go
  pkg/koordlet/statesinformer/register_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/koordlet/statesinformer/states_node.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/koordlet/statesinformer/states_nodeslo_test.go
  pkg/koordlet/statesinformer/states_pod.go
  pkg/util/config.go
Labels: size/XXL, lgtm, approved

#131 update codecov configuration
  .github/workflows/ci.yaml
  codecov.yml
  pkg/util/pod.go
  pkg/util/stat_test.go
Labels: lgtm, approved, size/M

#158 koordlet: support collect BE CPU metric
  pkg/koordlet/metricsadvisor/be_collector.go
  pkg/koordlet/metricsadvisor/be_collector_test.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/util/container.go
  pkg/util/node.go
  pkg/util/stat.go
  pkg/util/stat_test.go
Labels: lgtm, approved, size/L

#161 apis: introduce cpu evict fields in NodeSLO
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Labels: lgtm, approved, size/M

#165 Add pod annotations/labels for container level hook
  apis/runtime/v1alpha1/api.pb.go
  apis/runtime/v1alpha1/api.proto
  apis/runtime/v1alpha1/api_grpc.pb.go
Labels: lgtm, approved, size/L

#162 ci: support running unit test on multiple os
  .github/workflows/ci.yaml
  README.md
Labels: lgtm, approved, size/M

#167 style: format header to fix ci errors
  .github/workflows/license.yml
  pkg/koordlet/metricsadvisor/be_collector.go
  pkg/koordlet/metricsadvisor/be_collector_test.go
Labels: lgtm, approved, size/M

#168 Introduce image service proxy under cri scenario
  pkg/runtime-manager/server/cri/criserver.go
  pkg/runtime-manager/server/cri/image.go
  pkg/runtime-manager/server/cri/runtime.go
  pkg/runtime-manager/server/utils/utils.go
Labels: lgtm, approved, size/L

#170 runtime-manager: refactor codes about store and resource-exectutor
  pkg/runtime-manager/dispatcher/dispatcher.go
  pkg/runtime-manager/dispatcher/hookclient.go
  pkg/runtime-manager/resource-executor/cri/container.go
  pkg/runtime-manager/resource-executor/cri/pod.go
  pkg/runtime-manager/resource-executor/resource_executor.go
  pkg/runtime-manager/server/cri/criserver.go
  pkg/runtime-manager/server/utils/utils.go
  pkg/runtime-manager/store/manager.go
Labels: lgtm, approved, size/L

#169 koordlet: support cpu evict feature
  pkg/features/koordlet_features.go
  pkg/koordlet/resmanager/config.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/koordlet/resmanager/metrics_query.go
  pkg/koordlet/resmanager/metrics_query_test.go
  pkg/koordlet/resmanager/reason.go
  pkg/koordlet/resmanager/resmanager.go
Labels: size/XXL, lgtm, approved

#171 Introduce main for runtime-manager
  .github/workflows/ci.yaml
  Makefile
  cmd/runtime-manager/main.go
  cmd/runtime-manager/options/options.go
  pkg/runtime-manager/server/cri/criserver.go
  pkg/runtime-manager/server/utils/utils.go
Labels: lgtm, approved, size/L

#159 Support load aware scheduling
  Makefile
  apis/extension/resource.go
  apis/extension/scheduling.go
  cmd/koord-scheduler/app/config/config.go
  cmd/koord-scheduler/app/options/options.go
  cmd/koord-scheduler/app/server.go
  cmd/koord-scheduler/main.go
  go.mod
  hack/update-scheduler-codegen.sh
  pkg/scheduler/OWNERS
  pkg/scheduler/apis/config/doc.go
  pkg/scheduler/apis/config/register.go
  pkg/scheduler/apis/config/scheme/scheme.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/doc.go
  pkg/scheduler/apis/config/v1beta2/register.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.defaults.go
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/scheduler/plugins/loadaware/pod_assign_cache.go
  pkg/scheduler/plugins/loadaware/pod_assign_cache_test.go
  pkg/util/pod.go
  pkg/webhook/OWNERS
  vendor/k8s.io/kubernetes/pkg/scheduler/testing/fake_extender.go
  vendor/k8s.io/kubernetes/pkg/scheduler/testing/fake_plugins.go
  vendor/k8s.io/kubernetes/pkg/scheduler/testing/framework_helpers.go
  vendor/k8s.io/kubernetes/pkg/scheduler/testing/workload_prep.go
  vendor/k8s.io/kubernetes/pkg/scheduler/testing/wrappers.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#173 koord-scheduler: update scheduler apis groupName
  pkg/scheduler/apis/config/doc.go
  pkg/scheduler/apis/config/v1beta2/doc.go
Labels: size/XS, lgtm, approved

#176 test: add ut for configmap_event_handler
  pkg/slo-controller/noderesource/configmap_event_handler_test.go
Labels: lgtm, approved, size/L

#177 test: add ut for node_event_handler
  pkg/slo-controller/nodemetric/node_event_handler.go
  pkg/slo-controller/nodemetric/node_event_handler_test.go
Labels: lgtm, approved, size/M

#179 fix: add CPU Evict check in isFeatureDisabled
  pkg/koordlet/resmanager/resmanager.go
Labels: size/XS, lgtm, approved

#178 Add the runtime-manager design doc
  docs/design-archive/koordlet-architecture.md
  docs/design-archive/koordlet-runtime-hooks.md
  docs/design-archive/runtime-manager-design-doc.md
  docs/images/runtime-manager-architecture.svg
  docs/images/runtime-manager-design.svg
Labels: lgtm, approved, size/L

#181 chore: introduce dependabot
  .github/dependabot.yml
Labels: lgtm, approved, size/S

#166 add group identity plugin
  cmd/koordlet/main.go
  examples/nginx/nginx.yaml
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/server/server.go
  pkg/koordlet/statesinformer/register.go
  pkg/koordlet/statesinformer/register_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/util/pod.go
Labels: size/XXL, lgtm, approved

#182 add more tests
  cmd/koord-manager/main.go
  pkg/slo-controller/nodemetric/node_event_handler_test.go
  pkg/slo-controller/noderesource/nodemetric_event_handler_test.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/webhook/pod/mutating/mutating_handler_test.go
  pkg/webhook/pod/validating/validating_handler_test.go
Labels: lgtm, approved, size/XL

#192 chore: remove additional cache in golangci-lint
  .github/workflows/ci.yaml
Labels: size/XS, lgtm, approved

#191 api: remove deprecated field in NodeSLO
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Labels: lgtm, approved, size/S

#195 Rename runtime-manager to koord-runtime-proxy
  .github/workflows/ci.yaml
  Makefile
  cmd/koord-runtime-proxy/main.go
  cmd/koord-runtime-proxy/options/options.go
  docs/design-archive/koord-runtime-proxy-design-doc.md
  docs/images/koord-runtime-proxy-architecture.svg
  docs/images/koord-runtime-proxy-design.svg
  docs/images/runtime-manager-architecture.svg
  docs/images/runtime-manager-design.svg
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/server/service.go
  pkg/runtimeproxy/config/config.go
  pkg/runtimeproxy/config/config_manager.go
  pkg/runtimeproxy/dispatcher/dispatcher.go
  pkg/runtimeproxy/dispatcher/hookclient.go
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/pod.go
  pkg/runtimeproxy/resexecutor/cri/utils.go
  pkg/runtimeproxy/resexecutor/resource_executor.go
  pkg/runtimeproxy/server/cri/criserver.go
  pkg/runtimeproxy/server/cri/image.go
  pkg/runtimeproxy/server/cri/runtime.go
  pkg/runtimeproxy/server/cri/utils.go
  pkg/runtimeproxy/server/server.go
  pkg/runtimeproxy/store/manager.go
  pkg/runtimeproxy/utils/utils.go
Labels: lgtm, approved, size/L

#128 feature: support docker proxy
  cmd/koord-runtime-proxy/main.go
  go.mod
  go.sum
  pkg/runtimeproxy/server/docker/handler.go
  pkg/runtimeproxy/server/docker/server.go
  pkg/runtimeproxy/server/docker/utils.go
  pkg/runtimeproxy/server/docker/utils_test.go
  pkg/runtimeproxy/server/types/docker_types.go
Labels: lgtm, approved, size/XL

#198 koord-runtime-proxy: add installation manual
  docs/design-archive/koord-runtime-proxy-design-doc.md
Labels: lgtm, approved, size/M

#200 add ChangeLog for v0.4.0
  CHANGELOG.md
Labels: lgtm, approved, size/M
