Repository koordinator-sh/koordinator, pull requests merged in 2023-03, with the labels that each got.

#1058 apis: correct LabelGPUModel & LabelGPUDriverVersion
  apis/extension/resource.go
Labels: size/XS, lgtm, approved

#1069 e2e: fix e2e BatchResource for custom namespace
  test/e2e/framework/test_context.go
  test/e2e/slocontroller/batchresource.go
Labels: lgtm, approved, size/M

#1070 e2e: fix e2e BatchResource for custom namespace
  test/e2e/slocontroller/batchresource.go
Labels: size/XS, lgtm, approved

#1073 koordlet: fix kubelet policy nil
  pkg/koordlet/resmanager/cpu_suppress.go
Labels: size/XS, lgtm, approved

#1047 koordlet: ensure report nodetopo after nodecpuinfo have already collected
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query_test.go
  pkg/koordlet/resmanager/metrics_query_test.go
Labels: lgtm, approved, size/S

#1077 koord-scheduler: improve the readability of the PreFilter error message of the DeviceShare plugin
  pkg/scheduler/plugins/deviceshare/utils.go
Labels: size/XS, lgtm, approved

#1066 koord-scheduler: clarify framework extender
  cmd/koord-scheduler/app/server.go
  cmd/koord-scheduler/main.go
  pkg/scheduler/eventhandlers/reservation_handler.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/framework_extender_factory_test.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_transformer_test.go
  pkg/scheduler/frameworkext/sharedlisterext/sharedlister_adapter.go
  pkg/scheduler/frameworkext/sharedlisterext/sharedlister_adapter_test.go
  pkg/scheduler/plugins/deviceshare/plugin_service_test.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/hook_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/rcache.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/scheduler/plugins/reservation/utils.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: size/XXL, lgtm, approved

#1075 koord-manager: allow plugins configured by configmap then updated in NodeSLO
  apis/extension/slo_controller_config.go
  apis/extension/zz_generated.deepcopy.go
  pkg/slo-controller/nodeslo/extender_config.go
  pkg/slo-controller/nodeslo/extender_config_test.go
  pkg/slo-controller/nodeslo/extender_plugin.go
  pkg/slo-controller/nodeslo/extender_plugin_test.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
Labels: lgtm, approved, size/L

#1085 koord-descheduler: allow annotated migrationJob pass filter
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/evictions/evictions.go
Labels: lgtm, approved, size/M

#1024 koordlet: cgroup file read and write is privatized and consolidated into the resource executor package.
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metrics/psi.go
  pkg/koordlet/metrics/psi_test.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resourceexecutor/cgroup.go
  pkg/koordlet/resourceexecutor/cgroup_test.go
  pkg/koordlet/resourceexecutor/executor.go
  pkg/koordlet/resourceexecutor/psi.go
  pkg/koordlet/resourceexecutor/psi_test.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/resctrl_updater.go
  pkg/koordlet/resourceexecutor/resctrl_updater_test.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/resourceexecutor/updater_test.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/koordlet/runtimehooks/hooks/gpu/gpu.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/kubeqos_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/proxyserver/server.go
  pkg/koordlet/runtimehooks/proxyserver/service.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/util/container.go
  pkg/koordlet/util/container_test.go
  pkg/koordlet/util/meminfo.go
  pkg/koordlet/util/meminfo_test.go
  pkg/koordlet/util/node.go
  pkg/koordlet/util/node_test.go
  pkg/koordlet/util/pod.go
  pkg/koordlet/util/pod_test.go
  pkg/koordlet/util/stat.go
  pkg/koordlet/util/stat_test.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/cgroup_test.go
  pkg/koordlet/util/system/psi.go
  pkg/koordlet/util/system/psi_file_test.go
  pkg/koordlet/util/system/util_test_tool.go
Labels: size/XXL, lgtm, approved

#1078 koordlet: require gc started for cacheable update
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/system_config_test.go
  pkg/koordlet/resourceexecutor/executor.go
  pkg/koordlet/resourceexecutor/executor_test.go
Labels: lgtm, approved, size/L

#1086 koordlet: merge extensions in nodeslo and add general util methods
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/reader_test.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/koordlet/statesinformer/states_nodeslo_test.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/cgroup2.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/util/config.go
  pkg/util/config_test.go
Labels: lgtm, approved, size/L

#1065 koord-manager: refactor noderesource and add resource calculation extenders
  pkg/slo-controller/noderesource/device_event_handler.go
  pkg/slo-controller/noderesource/device_resource_calculator.go
  pkg/slo-controller/noderesource/device_resource_calculator_test.go
  pkg/slo-controller/noderesource/extender_plugin.go
  pkg/slo-controller/noderesource/extender_plugin_test.go
  pkg/slo-controller/noderesource/framework/extender_plugin.go
  pkg/slo-controller/noderesource/framework/extender_plugin_test.go
  pkg/slo-controller/noderesource/framework/noderesource.go
  pkg/slo-controller/noderesource/nodemetric_event_handler.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: size/XXL, lgtm, approved

#1053 koord-descheduler: LowNodeLoad eliminates abnormal states based on consecutiveNormalities
  pkg/descheduler/apis/config/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/utils/anomaly/basic_detector.go
  pkg/descheduler/utils/anomaly/basic_detector_test.go
  pkg/descheduler/utils/anomaly/types.go
Labels: lgtm, approved, size/L

#1097 koord-manager: remove duplicate registration in noderesource controller
  pkg/slo-controller/noderesource/noderesource_controller.go
Labels: size/XS, lgtm, approved

#1068 koord-descheduler: support to configure eviction filter separately
  docs/proposals/scheduling/20220701-simple-descheduler-framework.md
  pkg/descheduler/apis/config/types.go
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/default_plugins.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/evict.go
  pkg/descheduler/controllers/migration/filter.go
  pkg/descheduler/framework/plugins/kubernetes/defaultevictor/evictor.go
  pkg/descheduler/framework/plugins/kubernetes/plugin_test.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/framework/runtime/evictor_proxy.go
  pkg/descheduler/framework/runtime/framework.go
  pkg/descheduler/framework/runtime/framework_test.go
  pkg/descheduler/framework/testing/framework_helpers.go
  pkg/descheduler/framework/types.go
  pkg/descheduler/profile/profile_test.go
Labels: lgtm, approved, size/XL

#1095 koord-descheduler: refactor GetExpectedScaleForPod
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
  pkg/descheduler/controllers/migration/filter.go
Labels: lgtm, approved, size/M

#1105 ci: fix invalid image tag
  .github/workflows/ci.yaml
Labels: size/XS, lgtm, approved

#1104 koord-manager: fix not compatible with ElasticQuota associated by namespace
  pkg/scheduler/plugins/elasticquota/controller_test.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_helper_test.go
  pkg/webhook/elasticquota/pod_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/L

#1055 koordlet:move audit log to resource executor after resource update
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/system_config.go
  pkg/koordlet/resourceexecutor/cgroup.go
  pkg/koordlet/resourceexecutor/cgroup_test.go
  pkg/koordlet/resourceexecutor/executor_test.go
  pkg/koordlet/resourceexecutor/resctrl_updater.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/resourceexecutor/updater_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/kubeqos_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/util/system/common.go
  pkg/util/cpuset/cpuset.go
  pkg/util/cpuset/cpuset_test.go
Labels: lgtm, approved, size/L

#1109 koord-scheduler: rename built-in ElasticQuota name
  apis/extension/elastic_quota.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/L

#1107 koord-scheduler: refresh runtime quota before check
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: lgtm, approved, size/M

#1106 koord-scheduler: PodGroups are no longer created if pods use Gang annotations
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Labels: lgtm, approved, size/L

#1112 koord-scheduler: allow Reservation to reserve a subset of resources requested by Pod
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/utils.go
  pkg/scheduler/plugins/reservation/utils_test.go
Labels: lgtm, approved, size/L

#1119 koord-descheduler: enhanced support for Deployment
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
  pkg/descheduler/controllers/migration/controllerfinder/pods_finder.go
  pkg/descheduler/controllers/migration/controllerfinder/pods_finder_test.go
  pkg/descheduler/controllers/migration/filter.go
Labels: lgtm, approved, size/L

#1118 koordlet: Memcg reaper
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  config/manager/koordlet.yaml
  pkg/koordlet/metrics/common.go
  pkg/koordlet/metrics/expire_metric.go
  pkg/koordlet/metrics/expire_metric_test.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/qosmanager/k8s/k8s.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/system_config.go
  pkg/koordlet/resmanager/system_config_test.go
  pkg/koordlet/util/system/system_file.go
  pkg/koordlet/util/system/system_resource.go
  pkg/koordlet/util/system/system_resource_test.go
  pkg/koordlet/util/system/util_test_tool.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/util/config.go
Labels: lgtm, approved, size/L

#1101 koord-manager: revise node resource framework
  pkg/slo-controller/noderesource/framework/extender_plugin.go
  pkg/slo-controller/noderesource/framework/extender_plugin_test.go
  pkg/slo-controller/noderesource/framework/noderesource.go
  pkg/slo-controller/noderesource/framework/registry.go
  pkg/slo-controller/noderesource/framework/registry_test.go
  pkg/slo-controller/noderesource/nodemetric_event_handler.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins_profile.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: lgtm, approved, size/XL

#1121 apis: Reservation enables AllocateOnce by default
  apis/scheduling/v1alpha1/reservation_types.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
Labels: lgtm, approved, size/S

#1124 apis: update some comment
  apis/slo/v1alpha1/nodeslo_types.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Labels: lgtm, approved, size/M

#1125 koord-scheduler: ElasticQuota skips reserve pod in PostFilter phase
  pkg/scheduler/plugins/elasticquota/plugin.go
Labels: lgtm, approved, size/S

#922 proposal: Node Resource Reservation
  docs/proposals/scheduling/20221227-node-resource-reservation.md
Labels: lgtm, approved, size/L

#1126 koord-scheduler: enhanced frameworkext to support Reservation
  .licenseignore
  docs/images/koord-scheduler-framework-ext.png
  docs/images/scheduler-extension.jpg
  docs/proposals/scheduling/20220513-enhanced-scheduler-extension.md
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/framework_extender_factory_test.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_transformer.go
  pkg/scheduler/frameworkext/temporary_snapshot.go
  pkg/scheduler/frameworkext/temporary_snapshot_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: size/XXL, lgtm, approved

#1129 koordlet: use cgroup parent path straightforward
  pkg/koordlet/common/utils/pod.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux_test.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/statesinformer/states_pods.go
  pkg/koordlet/statesinformer/states_pods_test.go
  pkg/koordlet/util/cgroup_parent_utils.go
  pkg/koordlet/util/cgroup_parent_utils_test.go
  pkg/koordlet/util/container.go
  pkg/koordlet/util/container_test.go
  pkg/koordlet/util/pod.go
  pkg/koordlet/util/pod_test.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/util_test_tool.go
Labels: lgtm, approved, size/L

#1143 ci: disable cache when running actions/setup-go
  .github/workflows/ci.yaml
  .github/workflows/license.yml
  .github/workflows/release.yml
Labels: lgtm, approved, size/S

#1148 koordlet: fix update Device object error
  pkg/koordlet/statesinformer/states_device_linux.go
Labels: lgtm, approved, size/S, area/koordlet

#1151 koord-descheduler: improve compatibility with policy/v1beta1 eviction api
  pkg/descheduler/evictions/evictions.go
Labels: lgtm, approved, size/M

#1137 docs: fix double-subtract node.anno.reserved
  docs/proposals/scheduling/20221227-node-resource-reservation.md
Labels: size/XS, lgtm, approved

#998 support node resource reservation
  apis/extension/node_reservation.go
  apis/extension/node_reservation_test.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
  pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer_test.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/util/node.go
  pkg/util/node_test.go
Labels: enhancement, size/XXL, lgtm, approved, area/koordlet, area/koord-scheduler, area/koord-manager

#1146 koord-scheduler: DeviceShare supports preempting devices
  pkg/scheduler/plugins/deviceshare/allocator.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_cache_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
Labels: enhancement, lgtm, approved, size/XL, area/koord-scheduler

#1083 koordlet: pod eviction policy compatibility
  apis/extension/pod_evict.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/resmanager_test.go
  pkg/util/pod_evict.go
Labels: lgtm, approved, size/L

#1152 koord-descheduler: fix externally created MigrationJob not using default mode
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/evictions/evictions.go
Labels: lgtm, approved, size/M

#1164 apis: adjust unsuitable constant definitions
  apis/extension/pod_evict.go
  pkg/koordlet/resmanager/resmanager_test.go
  pkg/util/pod_evict.go
Labels: lgtm, approved, size/M

#1128 koord-descheduler: support soft eviction takeover eviction behavior
  apis/extension/descheduling.go
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/controllers/migration/evictor/evictor_soft.go
  pkg/descheduler/controllers/migration/evictor/evictor_soft_test.go
Labels: enhancement, lgtm, approved, size/L, area/koord-descheduler

#1161 koordlet: fix node aggregate policy config
  apis/extension/slo_controller_config.go
  apis/extension/zz_generated.deepcopy.go
  pkg/slo-controller/nodemetric/collect_policy.go
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/nodemetric/nodemetric_controller_test.go
Labels: lgtm, approved, size/L

#1163 koordlet: fix cpu evict test
  pkg/koordlet/resmanager/cpu_evict_test.go
Labels: lgtm, approved, size/S
