Repository koordinator-sh/koordinator, pull requests merged in 2023-05, with the labels that each got.

#1261 koord-manager: make fieldIndex register more scalable
  pkg/util/fieldindex/register.go
Labels: lgtm, approved, size/M

#1262 apis: add system usage in NodeMetric
  apis/slo/v1alpha1/nodemetric_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved, size/L

#1267 koordlet: improve metric GC
  pkg/koordlet/metrics/expire_metric.go
  pkg/koordlet/metrics/expire_metric_test.go
Labels: lgtm, approved, size/L

#1264 chore: more comments in injectForOrigin function
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/protocol_test.go
Labels: lgtm, approved, size/L

#1271 refactor: replace deprecated pointer function with the recommended pointer function
  pkg/koordlet/qosmanager/manager.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/koordlet/resmanager/pod_qos_control_test.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/resmanager/resmanager_test.go
  pkg/koordlet/resmanager/system_config_test.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
  pkg/koordlet/statesinformer/callback_runner_test.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
  pkg/koordlet/statesinformer/states_nodeslo_test.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/system_resource.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/plugins/deviceshare/device_handler_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/nodemetric/nodemetric_controller_test.go
  pkg/slo-controller/noderesource/device_resource_calculator_test.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/slo-controller/nodeslo/extender_config_test.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/util/sloconfig/colocation_config_extender_test.go
  pkg/util/sloconfig/colocation_config_test.go
  pkg/util/sloconfig/nodeslo_config.go
  pkg/util/utils_test.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
  pkg/webhook/pod/mutating/extended_resource_spec_test.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
  test/e2e/framework/node/runtimeclass.go
Labels: size/XXL, lgtm, approved

#1273 apis: defined Reservation.Spec.AllocateOnce as pointer
  apis/extension/reservation.go
  apis/scheduling/v1alpha1/reservation_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/reservation/util.go
  pkg/descheduler/controllers/migration/reservation/util_test.go
  pkg/scheduler/plugins/reservation/controller/controller.go
  pkg/scheduler/plugins/reservation/controller/controller_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  test/e2e/scheduling/nodenumaresource.go
  test/e2e/scheduling/preemption.go
  test/e2e/scheduling/reservation.go
Labels: lgtm, approved, size/M

#1275 koordlet: fix host cgroup check failed when the config is not the default
  pkg/koordlet/util/system/cgroup_driver_linux.go
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/util_test_tool.go
Labels: size/XS, lgtm, approved

#1274 koord-manager: add controllers options
  cmd/koord-manager/main.go
  cmd/koord-manager/options/controllers.go
  cmd/koord-manager/options/options.go
Labels: lgtm, approved, size/L

#1268 koord-scheduler: take over snapshot generation
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/framework_extender_factory_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_filter_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_filter_transformer_test.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_transformer_test.go
  pkg/scheduler/frameworkext/sharedlisterext/sharedlister_adapter.go
  pkg/scheduler/frameworkext/sharedlisterext/sharedlister_adapter_test.go
  pkg/scheduler/frameworkext/temporary_snapshot.go
  pkg/scheduler/frameworkext/temporary_snapshot_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: size/XXL, lgtm, approved

#1265 koord-scheduler: support select reservation via reservation affinity
  apis/extension/reservation.go
  docs/proposals/scheduling/20220609-resource-reservation.md
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/util/reservation/reservation.go
  test/e2e/scheduling/reservation.go
Labels: lgtm, approved, size/L

#1228 koordlet: change metric cache to tsdb
  config/manager/koordlet.yaml
  go.mod
  go.sum
  hack/mock-gen.sh
  pkg/koordlet/metriccache/config.go
  pkg/koordlet/metriccache/config_test.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_resources_test.go
  pkg/koordlet/metriccache/metric_result.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/metriccache/mockmetriccache/mock_metric_result.go
  pkg/koordlet/metriccache/mockmetriccache/mock_tsdb_storage.go
  pkg/koordlet/metriccache/tsdb_storage.go
  pkg/koordlet/metriccache/tsdb_storage_test.go
  pkg/koordlet/metriccache/util.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
  pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector.go
  pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector_test.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resmanager/metrics_query.go
Labels: size/XXL, lgtm, approved

#1280 koord-scheduler: refactor ReservationInfo as public
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/cache_test.go
  pkg/scheduler/plugins/reservation/eventhandler_test.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/reservation_info.go
  pkg/scheduler/plugins/reservation/scoring.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: lgtm, approved, size/L

#1281 koordlet: fix log error
  pkg/koordlet/resmanager/memory_evict.go
Labels: size/XS, lgtm, approved

#1282 koordlet: fix some unstable ut
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector_test.go
  pkg/koordlet/pleg/watcher_linux_test.go
Labels: lgtm, approved, size/S

#1283 koord-scheduler: optimize the signature of the transformer interface
  docs/proposals/scheduling/20220513-enhanced-scheduler-extension.md
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: lgtm, approved, size/M

#1286 koord-manager: fix variable typo
  pkg/slo-controller/config/colocation_cm_event_handler.go
Labels: size/XS, lgtm, approved

#1220 runtime-proxy: extract annotations from labels for docker
  pkg/runtimeproxy/server/docker/server.go
Labels: size/XS, lgtm, approved

#1288 koord-scheduler: implement EnqueueExtensions
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/reservation/plugin.go
Labels: lgtm, approved, size/M

#1289 koord-scheduler: fix duplicate allocate GPU after leader selection changed
  pkg/scheduler/plugins/deviceshare/pod_handler.go
  pkg/scheduler/plugins/deviceshare/pod_handler_test.go
Labels: lgtm, approved, size/L

#1284 koord-scheduler: optimize the flow of restore Reservation
  .licenseignore
  docs/proposals/scheduling/20220513-enhanced-scheduler-extension.md
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/reservation.go
  pkg/scheduler/plugins/reservation/error_channel.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/scoring.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/util/reservation/reservation.go
Labels: size/XXL, lgtm, approved

#1293 koord-scheduler: DeviceShare skips zero requests
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/S

#1296 koord-scheduler: optimize the patch implementation of the PreBind stage
  pkg/descheduler/controllers/migration/evictor/evictor_soft.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/L

#1298 chore: move koord-manager scheme under options, add host run mount
  cmd/koord-manager/main.go
  cmd/koord-manager/options/scheme.go
  config/manager/koordlet.yaml
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/config_test.go
Labels: lgtm, approved, size/M

#1299 koord-scheduler: coscheduling supports sensing PodGroup changes
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
Labels: lgtm, approved, size/M

#1300 koord-scheduler: support exporting scheduler cache and queue to plugin
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/eventhandlers/internal_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/scheduler_adapter.go
Labels: lgtm, approved, size/L

#1313 koord-manager: fix options
  cmd/koord-manager/options/options.go
  cmd/koord-manager/options/options_test.go
Labels: lgtm, approved, size/L

#1318 koord-scheduler: podgroup support minMember = 0
  pkg/scheduler/plugins/coscheduling/controller/podgroup.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
Labels: size/XS, lgtm, approved

#1314 koord-scheduler: complement Reservation plugin's Pod onUpdate handler
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
Labels: lgtm, approved, size/L

#1319 koordlet: add pod filter for metricsadvisor
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector.go
  pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector_test.go
  pkg/koordlet/metricsadvisor/framework/options.go
  pkg/koordlet/metricsadvisor/framework/plugin.go
  pkg/koordlet/metricsadvisor/framework/pod_filter.go
  pkg/koordlet/metricsadvisor/framework/pod_filter_test.go
  pkg/koordlet/metricsadvisor/metrics_advisor.go
  pkg/koordlet/metricsadvisor/plugins_profile.go
  pkg/koordlet/resourceexecutor/cgroup.go
Labels: lgtm, approved, size/XL

#1317 koord-scheduler: implement PreBindExtensions to support one-time apply patches
  cmd/koord-scheduler/app/server.go
  cmd/koord-scheduler/main.go
  pkg/descheduler/controllers/migration/evictor/evictor_soft.go
  pkg/scheduler/frameworkext/defaultprofile/profile.go
  pkg/scheduler/frameworkext/defaultprofile/profile_test.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/plugins/defaultprebind/plugin.go
  pkg/scheduler/plugins/defaultprebind/plugin_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: size/XXL, lgtm, approved

#1291 koord-scheduler: support Reservation allocate policy
  apis/scheduling/v1alpha1/reservation_types.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
  docs/proposals/scheduling/20220609-resource-reservation.md
  pkg/scheduler/plugins/deviceshare/allocator.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_cache_test.go
  pkg/scheduler/plugins/deviceshare/device_resources.go
  pkg/scheduler/plugins/deviceshare/device_resources_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/deviceshare/reservation_test.go
  pkg/scheduler/plugins/deviceshare/service.go
  pkg/scheduler/plugins/deviceshare/service_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  test/e2e/scheduling/deviceshare.go
  test/e2e/scheduling/reservation.go
Labels: size/XXL, lgtm, approved

#1322 koord-manager: ClusterColocationProfile support grayscale
  apis/config/v1alpha1/cluster_colocation_profile_types.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/XL

#1323 koord-descheduler: make pvc reservation switchable
  pkg/descheduler/controllers/migration/reservation/util.go
  pkg/descheduler/controllers/migration/reservation/util_test.go
  pkg/features/features.go
Labels: lgtm, approved, size/L

#1324 koord-scheduler: support dispatching scheduling error
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/errorhandler_dispatcher.go
  pkg/scheduler/frameworkext/errorhandler_dispatcher_test.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/interface.go
Labels: lgtm, approved, size/L

#1224 proposal: NUMA Topology Scheduling
  docs/images/numa-topology-hint-provider.svg
  docs/proposals/scheduling/20230415-numa-topology-scheduling.md
Labels: lgtm, approved, size/L

#1315 koord-scheduler: support reserve by pod
  apis/extension/operating_pod.go
  apis/extension/reservation.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/deviceshare/reservation_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/reservation.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/cache_test.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
  pkg/scheduler/plugins/reservation/scoring.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
Labels: lgtm, approved, size/XL

#1325 koord-manager: allow skip update resource
  apis/extension/cluster_colocation_profile.go
  pkg/features/features.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/XL

#1328 koord-scheduler: fix status is not handled correctly in DeviceShare
  pkg/scheduler/plugins/deviceshare/plugin.go
Labels: size/XS, lgtm, approved

#1316 koordlet: refactor node metrics to tsdb
  hack/mock-gen.sh
  pkg/koordlet/metriccache/api.go
  pkg/koordlet/metriccache/kv_storage.go
  pkg/koordlet/metriccache/kv_storage_test.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_result.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/metriccache/mockmetriccache/mock_kv_storage.go
  pkg/koordlet/metriccache/mockmetriccache/mock_metric_result.go
  pkg/koordlet/metriccache/mockmetriccache/mock_tsdb_storage.go
  pkg/koordlet/metriccache/util.go
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux_test.go
  pkg/koordlet/metricsadvisor/framework/plugin.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query_test.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/koordlet/resmanager/metrics_query.go
  pkg/koordlet/resmanager/metrics_query_test.go
  pkg/koordlet/statesinformer/states_device_linux.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/koordlet/statesinformer/states_nodemetric.go
  pkg/koordlet/statesinformer/states_nodemetric_test.go
  pkg/koordlet/util/device.go
Labels: size/XXL, lgtm, approved

#1330 koord-scheduler: add forget pod handler in extended handle
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/scheduler_adapter.go
Labels: lgtm, approved, size/M

#1331 koord-manager: remove priorityClassname validation in profile
  apis/config/v1alpha1/cluster_colocation_profile_types.go
  config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
Labels: size/XS, lgtm, approved

#1338 koord-scheduler: fix reservation affinity in filter stage
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/L

#1340 koord-scheduler: update coscheduling comments
  pkg/scheduler/plugins/coscheduling/coscheduling.go
Labels: size/XS, lgtm, approved

#1339 koordlet: revise cgroup update err when unsupported or path not exist
  pkg/koordlet/resourceexecutor/cgroup.go
  pkg/koordlet/resourceexecutor/config_test.go
  pkg/koordlet/resourceexecutor/executor.go
  pkg/koordlet/resourceexecutor/executor_test.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
  pkg/koordlet/util/system/system_resource.go
  pkg/koordlet/util/system/system_resource_test.go
  pkg/koordlet/util/system/util_test_tool.go
Labels: lgtm, approved, size/L
