Repository koordinator-sh/koordinator, pull requests merged in 2023-10, with the labels that each got.

#1695 scheduler: optimize reservation BeforePreFilter performance
  apis/extension/reservation.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_benchmark_test.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
Labels: lgtm, approved, size/XL

#1697 dockerfile: support multiarch image build
  .github/workflows/ci.yaml
  .github/workflows/release.yml
  Makefile
  docker/koord-descheduler.dockerfile
  docker/koord-manager.dockerfile
  docker/koord-runtimeproxy.dockerfile
  docker/koord-scheduler.dockerfile
  docker/koordlet.dockerfile
  go.mod
  go.sum
  hack/tools.go
Labels: lgtm, approved, size/L

#1688 ci: add more slo controllers e2e test
  .github/workflows/e2e-k8s-1.22.yaml
  .github/workflows/e2e-k8s-1.24.yaml
  .github/workflows/e2e-k8s-latest.yaml
  config/manager/manager.yaml
  config/webhook/manifests.yaml
  hack/deploy_kind.sh
  pkg/webhook/node/validating/webhooks.go
  test/e2e/framework/test_context.go
  test/e2e/scheduling/nodenumaresource.go
  test/e2e/scheduling/preemption.go
  test/e2e/slocontroller/batchresource.go
  test/e2e/slocontroller/cpunormalization.go
  test/e2e/testing-manifests/slocontroller/be-demo.yaml
Labels: lgtm, approved, size/XL

#1702 scheduler: modify coscheduling Less function with considering childScheduleCycle
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved, size/M

#1700 proposal: change node resource amplification from api to scheduling level
  docs/proposals/scheduling/20230811-node-resource-amplification.md
Labels: lgtm, approved, size/S

#1668 koord-scheduler: Add non-preemptible feature in Elastic Quota Management
  apis/extension/elastic_quota.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_summary.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/preempt.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
  pkg/webhook/elasticquota/pod_check.go
Labels: lgtm, approved, size/L

#1706 scheduler: quota debug api support multi tree
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_summary.go
  pkg/scheduler/plugins/elasticquota/plugin_service.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: lgtm, approved, size/M

#1705 ci: support loading all components image in E2E
  .github/workflows/e2e-k8s-1.22.yaml
  .github/workflows/e2e-k8s-1.24.yaml
  .github/workflows/e2e-k8s-latest.yaml
  hack/deploy_kind.sh
Labels: lgtm, approved, size/M

#1709 scheduler: make ReservationInfo.AddAssignedPod idempotent
  pkg/scheduler/frameworkext/helper/forcesync_eventhandler.go
  pkg/scheduler/frameworkext/reservation_info.go
Labels: size/XS, lgtm, approved

#1708 webhook: add force update label for elastic quota
  apis/extension/elastic_quota.go
  pkg/webhook/elasticquota/quota_info.go
  pkg/webhook/elasticquota/quota_topology_check.go
Labels: lgtm, approved, size/S

#1710 manager: add GetNodeAllocatable in quota-controller
  pkg/quota-controller/profile/profile_controller.go
  pkg/quota-controller/profile/util.go
Labels: lgtm, approved, size/S

#1712 koordlet: fix metric name typo
  pkg/koordlet/metrics/resource_summary.go
Labels: size/XS, lgtm, approved

#1694 scheduler: use asynclog to reduce klog performance overhead
  cmd/koord-scheduler/app/server.go
  pkg/util/asynclog/async_log.go
Labels: lgtm, approved, size/L

#1713 scheduler: reservation senses node affinity
  pkg/scheduler/frameworkext/controllers.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: lgtm, approved, size/L

#1714 scheduler: optimize memory allocations
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/scheduler_adapter.go
  pkg/util/transformer/device_transformer.go
  pkg/util/transformer/node_transformer.go
  pkg/util/transformer/pod_transformer.go
Labels: lgtm, approved, size/M

#1703 koord-manager: enhance batch resource configuration and updating
  apis/configuration/slo_controller_config.go
  apis/configuration/zz_generated.deepcopy.go
  apis/extension/node_colocation.go
  docs/images/noderesource-framework.svg
  pkg/slo-controller/config/colocation_cm_event_handler.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/noderesource/framework/README.md
  pkg/slo-controller/noderesource/framework/extender_plugin.go
  pkg/slo-controller/noderesource/framework/extender_plugin_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/util.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin_test.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins_profile.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/util/sloconfig/colocation_config.go
  pkg/util/sloconfig/colocation_config_extender_test.go
  pkg/util/sloconfig/colocation_config_test.go
Labels: size/XXL, lgtm, approved

#1716 scheduler: add elastic quota metric
  apis/extension/elastic_quota.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/metrics.go
Labels: lgtm, approved, size/L

#1717 scheduler: reservation transformer ends early with reservation affinity
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: lgtm, approved, size/L

#1718 apis: make PCIEID of DeviceTopology as string type
  apis/scheduling/v1alpha1/device_types.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Labels: lgtm, approved, size/L

#1699 koordlet: cold memory fix usageWithHotPage and add usageWithPageCache
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_collector.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled_test.go
  pkg/koordlet/metricsadvisor/collectors/pagecache/page_cache_collector.go
  pkg/koordlet/metricsadvisor/framework/config.go
  pkg/koordlet/metricsadvisor/framework/config_test.go
  pkg/koordlet/metricsadvisor/plugins_profile.go
  pkg/koordlet/resourceexecutor/reader_test.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
  pkg/koordlet/util/cold_page.go
  pkg/koordlet/util/cold_page_test.go
  pkg/koordlet/util/meminfo.go
  pkg/koordlet/util/meminfo_test.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/kidled_util.go
  pkg/koordlet/util/system/kidled_util_test.go
Labels: lgtm, approved, size/L

#1719 chores: update outdated dingtak qr code
  docs/images/dingtalk.png
Labels: size/XS, lgtm, approved

#1721 descheduler: check nodemetrics cr is expired or not when descheduling
  pkg/descheduler/apis/config/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/defaults_test.go
  pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/validation/validation_loadaware.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
Labels: lgtm, approved, size/M

#1723 pkg/koordlet: update some log level to silence log
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
  pkg/koordlet/statesinformer/impl/states_pods.go
Labels: size/XS, lgtm, approved
