Repository koordinator-sh/koordinator, pull requests merged in 2023-02, with the labels that each got.

#969 koord-scheduler: Reservation resolves ReadWriteOncePodAccessMode volume conflict
  pkg/scheduler/plugins/reservation/hook.go
  pkg/scheduler/plugins/reservation/hook_test.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/M

#975 koord-descheduler: fix LowNodeLoad when configuring nodeSelector
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
Labels: lgtm, approved, size/M

#976 koord-descheduler: set default values for evictQPS/evictBurst
  pkg/descheduler/apis/config/floatstr.go
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/validation/validation_pluginargs.go
  pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/evictor/interpreter.go
Labels: lgtm, approved, size/L

#981 koord-descheduler: use DefaultInsecureDeschedulerPort(10251) as healthz/metrics default port
  pkg/descheduler/apis/config/v1alpha2/defaults.go
Labels: size/XS, lgtm, approved

#980 koordlet:fix a bug in topologyinformer when start-up
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
Labels: lgtm, approved, size/S

#974 runtimeproxy: fix trap of nil interface{}
  pkg/runtimeproxy/dispatcher/dispatcher.go
  pkg/runtimeproxy/dispatcher/dispatcher_test.go
Labels: size/XS, lgtm, approved

#986 koordlet: remove deprecated executor package
  pkg/koordlet/executor/reason.go
  pkg/koordlet/executor/resctrl_executor.go
  pkg/koordlet/executor/resource_update_executor.go
  pkg/koordlet/executor/resource_update_executor_test.go
  pkg/koordlet/executor/types.go
  pkg/koordlet/executor/types_test.go
Labels: size/XXL, lgtm, approved

#985 koord-scheduler: fix a bug in spec.scheduleTimeoutSeconds nil pointer dereference
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Labels: lgtm, approved, size/M

#989 koord-scheduler: LoadAware supports custom estimator
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
  pkg/scheduler/plugins/loadaware/estimator/types.go
  pkg/scheduler/plugins/loadaware/load_aware.go
Labels: lgtm, approved, size/L

#859 docs: proposals for collect cpu schedule latency by eBPF
  docs/images/cpu-schedule-latency.svg
  docs/images/ebpf.png
  docs/images/thread-state-transition.svg
  docs/proposals/20221205-cpu-schedule-latency.md
Labels: lgtm, approved, size/L

#987 koord-descheduler: LowNodeLoad supports anomaly detector
  pkg/descheduler/apis/config/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/validation/validation_loadaware.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/utils/anomaly/basic_detector.go
  pkg/descheduler/utils/anomaly/basic_detector_test.go
  pkg/descheduler/utils/anomaly/counter.go
  pkg/descheduler/utils/anomaly/types.go
Labels: lgtm, approved, size/XL

#773 koordlet: runtime hook support failpolicy
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/config_test.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/proxyserver/server.go
  pkg/koordlet/runtimehooks/proxyserver/service.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
Labels: lgtm, approved, size/L

#993 koordlet: support reporting extension resource in statesInformer
  pkg/koordlet/statesinformer/extension_utils.go
  pkg/koordlet/statesinformer/states_nodemetric.go
Labels: lgtm, approved, size/S

#996 koord-scheduler: set Reservation indexer before informer start to avoid error
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/eventhandlers/reservation_handler_test.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/indexer/add_indexer.go
  pkg/scheduler/frameworkext/indexer/reservation.go
  pkg/scheduler/frameworkext/indexer/reservation_test.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/hook.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/utils.go
  pkg/scheduler/plugins/reservation/utils_test.go
Labels: lgtm, approved, size/L

#999 style: correct import alias in states_nodemetric
  pkg/koordlet/statesinformer/states_nodemetric.go
  pkg/koordlet/statesinformer/states_nodemetric_test.go
Labels: lgtm, approved, size/M

#992 koordlet: optimize if-else logics in cgroup reconcile
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/util/cache/expiration_cache.go
Labels: lgtm, approved, size/M

#1000 koordlet: skip fillExtensionMap if podMetric is nil
  pkg/koordlet/statesinformer/states_nodemetric.go
Labels: size/XS, lgtm, approved

#1007 koord-scheduler: compatible with lightweight-coscheduling
  apis/extension/scheduling.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Labels: lgtm, approved, size/L

#1008 koordlet: fix log typo
  pkg/koordlet/resmanager/cpu_suppress.go
Labels: size/XS, lgtm, approved

#1006 koordlet: support system config like minFreeKbytes,waterMarkScaleFactor
  apis/extension/slo_controller_config.go
  apis/extension/zz_generated.deepcopy.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/features/koordlet_features.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/system_config.go
  pkg/koordlet/resmanager/system_config_test.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/koordlet/statesinformer/states_nodeslo_test.go
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/resource.go
  pkg/koordlet/util/system/system_file.go
  pkg/koordlet/util/system/system_resource.go
  pkg/koordlet/util/system/system_resource_test.go
  pkg/koordlet/util/system/util_test_tool.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/util/config.go
  pkg/util/config_test.go
Labels: size/XXL, lgtm, approved

#1009 Improve project presentation based on chatgpt's suggestion
  README-zh_CN.md
  README.md
Labels: lgtm, approved, size/S

#1012 apis: add extension field in DeviceAllocation
  apis/extension/scheduling.go
Labels: size/XS, lgtm, approved

#984 koordlet: PerformanceCollector supports cgroups-v2
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metrics/psi.go
  pkg/koordlet/metrics/psi_test.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
  pkg/koordlet/metricsadvisor/performance_collector_unsupported.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resourceexecutor/executor.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/reader_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/util/container.go
  pkg/koordlet/util/container_test.go
  pkg/koordlet/util/pod.go
  pkg/koordlet/util/stat.go
  pkg/koordlet/util/stat_test.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/cgroup_test.go
  pkg/koordlet/util/system/psi.go
  pkg/koordlet/util/system/psi_test.go
Labels: lgtm, approved, size/L

#1015 koord-scheduler: fix GroupQuotaManager.updateMinQuotaNoLock
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
Labels: size/XS, lgtm, approved

#1020 add name to slo-controller-config cfg->NodeStrategies as selector alias
  apis/extension/slo_controller_config.go
  apis/extension/zz_generated.deepcopy.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/config/config_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
Labels: lgtm, approved, size/L

#1029 comment out the display of star history
  README-zh_CN.md
  README.md
Labels: size/XS, lgtm, approved

#1023 docs: introduce the CPU Co-location plug-in of CentOS
  docs/slides/koordinator-CPU-Co-location.pptx
Labels: size/XS, lgtm, approved

#1025 apis: deprecated device resource names with prefix kuberenetes.io
  apis/extension/deprecated.go
  apis/extension/resource.go
  apis/extension/scheduling_test.go
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
  pkg/koordlet/statesinformer/states_device_linux.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
  pkg/koordlet/statesinformer/states_nodemetric.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_handler_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_service_test.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/pod_handler.go
  pkg/scheduler/plugins/deviceshare/pod_handler_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/deviceshare/utils_test.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_test.go
Labels: size/XXL, lgtm, approved, area/api-machinery, api-changes

#1019 koordlet: refactor metrics advisor as framework
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/collector_gpu.go
  pkg/koordlet/metricsadvisor/collector_test.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector.go
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_unsupported.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux_test.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_unsupported.go
  pkg/koordlet/metricsadvisor/framework/config.go
  pkg/koordlet/metricsadvisor/framework/config_test.go
  pkg/koordlet/metricsadvisor/framework/context.go
  pkg/koordlet/metricsadvisor/framework/options.go
  pkg/koordlet/metricsadvisor/framework/plugin.go
  pkg/koordlet/metricsadvisor/metrics_advisor.go
  pkg/koordlet/metricsadvisor/metrics_advisor_test.go
  pkg/koordlet/metricsadvisor/state.go
  pkg/koordlet/metricsadvisor/state_test.go
  pkg/koordlet/resmanager/resmanager_test.go
Labels: size/XXL, lgtm, approved

#1026 koord-descheduler: check pod ready when migrating
  apis/scheduling/v1alpha1/pod_migration_job_types.go
  pkg/descheduler/controllers/migration/controller.go
Labels: lgtm, approved, size/M

#1045 ADOPTERS: add meiyapico as sample user
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#1048 Add stale config file
  .github/stale.yml
Labels: lgtm, approved, size/M

#1050 koordlet: add some logs for cpi and psi metric cache
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/storage.go
  pkg/koordlet/metriccache/storage_test.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
Labels: lgtm, approved, size/M

#1021 koordlet: use libcontainer check cgroupfsv2
  Makefile
  go.mod
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/util/container_test.go
  pkg/koordlet/util/pod_test.go
  pkg/koordlet/util/system/cgroup2.go
  pkg/koordlet/util/system/cgroup_driver_linux.go
  pkg/koordlet/util/system/cgroup_driver_unsupported.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/util_test_tool.go
Labels: lgtm, approved, size/L
