Repository koordinator-sh/koordinator, pull requests merged in 2023-01, with the labels that each got.

#916 koord-scheduler: fix reservation doesn't match pod when hostport is not set
  pkg/scheduler/plugins/reservation/utils.go
  pkg/scheduler/plugins/reservation/utils_test.go
Labels: lgtm, approved, size/S

#915 chore: update descheduler rbac
  config/rbac/descheduler_role.yaml
Labels: size/XS, lgtm, approved

#910 docs: fix community-membership url in README-zh_CN.md
  README-zh_CN.md
Labels: size/XS, lgtm, approved

#921 koord-manager: fix the validating and mutating logic of Pod resources
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
  pkg/webhook/pod/validating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
  pkg/webhook/pod/validating/request_limit_validator.go
Labels: lgtm, approved, size/L

#926 docs: fix ci badge in README.md
  README.md
Labels: size/XS, lgtm, approved

#927 docs: fix ci badge in README-zh_CN.md
  README-zh_CN.md
Labels: size/XS, lgtm, approved

#925 koord-manager: Fix log print fmt and add an example for slo-controller-config
  pkg/slo-controller/config/constants.go
  pkg/slo-controller/noderesource/noderesource.go
Labels: lgtm, approved, size/L

#912 koordlet: add more cli flags for audit log and ensure the audit log directory exist
  pkg/koordlet/audit/config.go
  pkg/koordlet/audit/event_logger.go
Labels: lgtm, approved, size/S

#914 koordlet: support cpu eviction in cpuset supress mode with cpu static policy
  pkg/koordlet/metricsadvisor/be_collector.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/util/node.go
Labels: lgtm, approved, size/L

#913 koordlet: add metrics for batch resources
  pkg/koordlet/koordlet.go
  pkg/koordlet/metrics/common.go
  pkg/koordlet/metrics/metrics.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metrics/resource_summary.go
  pkg/koordlet/metricsadvisor/collector.go
  pkg/koordlet/metricsadvisor/collector_test.go
  pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/resmanager_test.go
  pkg/koordlet/statesinformer/config_test.go
  pkg/koordlet/statesinformer/states_node.go
  pkg/koordlet/statesinformer/states_node_test.go
  pkg/koordlet/statesinformer/states_pods.go
  pkg/koordlet/statesinformer/states_pods_test.go
  pkg/util/resource.go
  pkg/util/resource_test.go
Labels: lgtm, approved, size/XL

#930 koordlet: fix cgroup validators
  pkg/koordlet/util/system/cgroup_resource.go
Labels: lgtm, approved, size/S

#931 koord-scheduler: ElasticQuota Plugin need DecoratePod OnPodDelete
  pkg/scheduler/plugins/elasticquota/pod_handler.go
Labels: size/XS, lgtm, approved

#936 koord-scheduler: add new method GetPodIsAssigned to QuotaInfo
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
Labels: lgtm, approved, size/S

#932 koord-descheduler: add evict event/metric for Pod during migration
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/evictor/evictor_delete.go
  pkg/descheduler/controllers/migration/evictor/evictor_native.go
  pkg/descheduler/controllers/migration/evictor/interpreter.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
  pkg/descheduler/framework/runtime/framework.go
  pkg/descheduler/framework/types.go
Labels: lgtm, approved, size/L

#937 koord-descheduler: refactor descheduler pod sorter
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/framework/plugins/loadaware/sorter.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
  pkg/descheduler/utils/sorter/helper.go
  pkg/descheduler/utils/sorter/pod.go
  pkg/descheduler/utils/sorter/scorer.go
  pkg/descheduler/utils/sorter/sorter_test.go
Labels: lgtm, approved, size/XL

#920 koord-scheduler: protect reserve pod from being preempted
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/M

#939 koord-descheduler: support pod deletion cost and eviction cost
  apis/extension/descheduling.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/util/util.go
  pkg/descheduler/controllers/migration/util/util_test.go
  pkg/descheduler/utils/sorter/pod.go
  pkg/descheduler/utils/sorter/pod_test.go
Labels: lgtm, approved, size/L

#944 koordlet: check key exist first before comparing node topo annotations
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
Labels: lgtm, approved, size/M

#918 koord-scheduler: remove allocated in filter hook
  pkg/scheduler/plugins/reservation/hook.go
  pkg/scheduler/plugins/reservation/hook_test.go
  pkg/scheduler/plugins/reservation/rcache.go
Labels: lgtm, approved, size/L

#945 koord-scheduler: additionally check parent's Quota if configured
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: lgtm, approved, size/L

#919 ci: use buildx to replace gorelaser to release image
  .github/workflows/release.yml
  .goreleaser.yaml
  .goreleaser/OWNERS
  .goreleaser/koord-descheduler.dockerfile
  .goreleaser/koord-manager.dockerfile
  .goreleaser/koord-scheduler.dockerfile
  .goreleaser/koordlet.dockerfile
Labels: lgtm, approved, size/L

#947 adopters: update iqyi adopter to stable status
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#933 koord-descheduler: optimize the migration defense strategies
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
  pkg/descheduler/controllers/migration/filter.go
  pkg/descheduler/controllers/migration/util/util.go
Labels: lgtm, approved, size/XL

#873 koord-scheduler: fix Coscheduling resource deadlock with groups
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
  pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Labels: lgtm, approved, size/L

#949 koord-manager: mv slo-controller config to api
  apis/extension/slo_controller_config.go
  apis/extension/zz_generated.deepcopy.go
  pkg/slo-controller/config/colocation_cm_event_handler.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/config/config_extender.go
  pkg/slo-controller/config/config_extender_test.go
  pkg/slo-controller/config/config_test.go
  pkg/slo-controller/nodemetric/collect_policy.go
  pkg/slo-controller/nodemetric/collect_policy_test.go
  pkg/slo-controller/nodemetric/nodemetric_controller_test.go
  pkg/slo-controller/noderesource/extender_plugin.go
  pkg/slo-controller/noderesource/extender_plugin_test.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
Labels: size/XXL, lgtm, approved

#951 koord-scheduler: optimize ElasticQuota QuotaInfo present methods
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
Labels: size/XS, lgtm, approved

#952 koordlet: fix batch resource plugin for empty label pods
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
Labels: lgtm, approved, size/M

#955 apis: add extension plugin framework for PodMetric
  apis/slo/v1alpha1/nodemetric_types.go
  apis/slo/v1alpha1/slo_extension.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved, size/S

#950 koord-descheduler: limits frequently migrated workloads
  go.mod
  go.sum
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
  pkg/descheduler/controllers/migration/filter.go
  pkg/descheduler/controllers/migration/util/util.go
Labels: lgtm, approved, size/L

#961 koord-manager: revise slo-controllers, fix for deleted node
  pkg/slo-controller/config/colocation_cm_event_handler.go
  pkg/slo-controller/config/config.go
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/noderesource/nodemetric_event_handler.go
  pkg/slo-controller/noderesource/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/noderesource_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
Labels: lgtm, approved, size/L

#929 koordlet: BECPUEvict supports cgroups-v2
  pkg/koordlet/metricsadvisor/be_collector.go
  pkg/koordlet/metricsadvisor/be_collector_test.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resourceexecutor/config.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
Labels: lgtm, approved, size/M

#942 koordlet: support NodeResourceTopology informer
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
Labels: lgtm, approved, size/L

#958 koord-scheduler: rename ElasticQuota QuotaInfo GetPodIsAssigned to CheckPodIsAssigned
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: lgtm, approved, size/S

#962 koordlet: clean up log format
  pkg/koordlet/statesinformer/states_pods.go
Labels: size/XS, lgtm, approved

#960 koordlet: fix not support cpu without L3 cache
  pkg/koordlet/util/cpuinfo_test.go
  pkg/koordlet/util/system/lscpu.go
Labels: lgtm, approved, size/M

#957 runtimeproxy: fix env lost
  pkg/runtimeproxy/server/docker/utils.go
  pkg/runtimeproxy/server/docker/utils_test.go
Labels: size/XS, lgtm, approved

#963 koord-descheduler: remove duplicated validation
  pkg/descheduler/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
Labels: size/XS, lgtm, approved

#967 koord-scheduler: DeviceShare plugin allocates devices in ascending order of Minor
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/pod_handler_test.go
Labels: lgtm, approved, size/L

#965 koord-scheduler: DeviceShare plugin supports custom allocator
  pkg/scheduler/apis/config/register.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/register.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/plugins/deviceshare/allocator.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_service_test.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/L

#966 koord-scheduler: optimize DeviceShare plugins pod event handler
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/pod_handler.go
Labels: lgtm, approved, size/M

#970 clean: resolve vet error
  pkg/scheduler/plugins/deviceshare/plugin.go
Labels: size/XS, lgtm, approved
