Repository koordinator-sh/koordinator, pull requests merged in 2023-08, with the labels that each got.

#1521 koordlet: fix the cpu.shares conversion on cgroups-v2
  pkg/koordlet/resourceexecutor/reader_test.go
  pkg/koordlet/util/system/cgroup2.go
  pkg/koordlet/util/system/cgroup2_test.go
  pkg/koordlet/util/system/cgroup_resource.go
Labels: lgtm, approved, size/M

#1516 koordlet: support numa topology reporting
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metrics/common.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector.go
  pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
  pkg/koordlet/metricsadvisor/plugins_profile.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile_test.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
  pkg/koordlet/util/cpuinfo.go
  pkg/koordlet/util/cpuinfo_test.go
  pkg/koordlet/util/kubelet/kubelet.go
  pkg/koordlet/util/meminfo.go
  pkg/koordlet/util/meminfo_test.go
  pkg/koordlet/util/system/system_file.go
  pkg/koordlet/util/testutil/mock_utils.go
Labels: size/XXL, lgtm, approved

#1525 chore: adjust the order of reviewers
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1524 koord-scheduler: set default priority in reserve pod
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
Labels: size/XS, lgtm, approved

#1522 proposal: DeviceShare supports scoring
  docs/proposals/scheduling/20230802-device-share-supports-scoring.md
Labels: lgtm, approved, size/L

#1526 koord-scheduler: add scoring strategy in DeviceShareArgs
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.defaults.go
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
Labels: lgtm, approved, size/M

#1528 proposal: enhance GPU Share API
  docs/proposals/scheduling/20230803-enhance-gpu-share-api.md
Labels: lgtm, approved, size/L

#1530 apis: add gang match policy alias annotation
  apis/extension/coscheduling.go
  apis/extension/scheduling.go
Labels: lgtm, approved, size/L

#1533 koord-descheduler: ignore create pmj when pod.schedulerName is not koord-scheduler
  go.mod
  go.sum
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/evict.go
  pkg/descheduler/controllers/migration/filter.go
Labels: lgtm, approved, size/M

#1532 koordlet: improve peak predictor server
  pkg/koordlet/prediction/peak_predictor.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
Labels: lgtm, approved, size/M

#1538 koordlet: report system resource usage in node metric
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector_test.go
  pkg/koordlet/metricsadvisor/framework/context.go
  pkg/koordlet/metricsadvisor/framework/context_test.go
  pkg/koordlet/metricsadvisor/metrics_advisor.go
  pkg/koordlet/metricsadvisor/metrics_advisor_test.go
  pkg/koordlet/metricsadvisor/plugins_profile.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: size/XXL, lgtm, approved

#1535 koord-descheduler: accumulates the sum of system and Pod usage as node usage
  pkg/descheduler/controllers/migration/filter.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
Labels: lgtm, approved, size/M

#1537 koord-scheduler: invalidate nodeDevice when deleting Device CRD object
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_cache_test.go
  pkg/scheduler/plugins/deviceshare/device_handler.go
  pkg/scheduler/plugins/deviceshare/device_handler_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
Labels: lgtm, approved, size/L

#1540 koord-descheduler: pmj controller support assign many schedulers that can handle reservation
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/evict.go
  pkg/descheduler/controllers/migration/filter.go
  pkg/util/utils.go
Labels: lgtm, approved, size/L

#1501 koordlet: add nri server for runtimehooks
  go.mod
  go.sum
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/config_test.go
  pkg/koordlet/runtimehooks/nri/server.go
  pkg/koordlet/runtimehooks/nri/server_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/container_context_test.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context_test.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
Labels: size/XXL, lgtm, approved

#1545 koord-manager: Optimize logs for reporting node devices
  pkg/slo-controller/noderesource/device_resource_calculator.go
Labels: lgtm, approved, size/S

#1543 koord-scheduler: make sure NodeInfo and other objects have synced before scheduling
  cmd/koord-scheduler/app/options/options.go
  pkg/scheduler/frameworkext/helper/forcesync_eventhandler.go
  pkg/scheduler/frameworkext/helper/forcesync_eventhandler_test.go
  pkg/scheduler/frameworkext/helper/forcesync_factory.go
  pkg/scheduler/frameworkext/helper/forcesync_factory_test.go
  pkg/scheduler/frameworkext/helper/forcesync_informer.go
Labels: lgtm, approved, size/L

#1514 Proposal: support cold memory collect and report
  docs/images/support-cold-memory-1.svg
  docs/images/support-cold-memory-2.svg
  docs/proposals/koordlet/20230728-support-cold-memory-compute.md
Labels: lgtm, approved, size/L

#1546 CI: fix goreleaser.yaml for the deprecated replacement field
  .goreleaser.yaml
Labels: lgtm, approved, size/S

#1548 fix crio version
  docs/proposals/20230608-nri-mode-resource-management.md
Labels: size/XS, lgtm, approved

#1551 koord-scheduler: fix missing AddEventHandler with forceSyncEventHandler
  pkg/scheduler/frameworkext/helper/forcesync_eventhandler.go
  pkg/scheduler/frameworkext/helper/forcesync_informer.go
Labels: lgtm, approved, size/M

#1550 koord-manager: fix noderesource update when compared values are zero
  .goreleaser.yaml
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/plugins_profile.go
  pkg/util/resource.go
  pkg/util/resource_test.go
Labels: lgtm, approved, size/M

#1552 koord-manager: fix node slo extension got overwriten
  pkg/slo-controller/nodeslo/extender_config_test.go
  pkg/slo-controller/nodeslo/extender_plugin.go
  pkg/slo-controller/nodeslo/extender_plugin_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
Labels: lgtm, approved, size/M

#1556 koordlet: resource qos config supports SYSTEM qos
  pkg/koordlet/qosmanager/helpers/property.go
  pkg/koordlet/qosmanager/helpers/property_test.go
  pkg/koordlet/qosmanager/plugins/cgreconcile/cgroup_reconcile.go
  pkg/koordlet/qosmanager/plugins/cgreconcile/cgroup_reconcile_test.go
  pkg/util/sloconfig/nodeslo_config.go
  pkg/util/sloconfig/nodeslo_config_test.go
Labels: lgtm, approved, size/L

#1564 koord-manager: only enable necessary plugin in the ut of resource calculator
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: size/XS, lgtm, approved

#1553 koord-manager: allow quotas that are not bound to pods to become parent nodes
  docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md
  pkg/util/fieldindex/register.go
  pkg/webhook/elasticquota/pod_check.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/L

#1565 koord-scheduler: fix quota onPodUpdate
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
Labels: lgtm, approved, size/M

#1563 koord-scheduler: skip checking for nodes whose nodemetrics update time has expired
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/conversion_plugin.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/M

#1575 Fix webhook patch manifests for pod update mutation
  config/webhook/patch_manifests.yaml
Labels: size/XS, lgtm, approved

#1454 proposal: Eviction Arbitration Mechanism in Descheduler
  docs/images/arbitration-mechanism-design.svg
  docs/images/arbitration-mechanism-filter-design.svg
  docs/images/arbitration-mechanism-sort-design.svg
  docs/images/arbitration-mechanism-time-diagram.svg
  docs/proposals/scheduling/20230707-eviction-arbitrate-mechanism-in-descheduler.md
Labels: lgtm, approved, size/L

#1572 koordlet: fix lose precision when show result of cpuspress
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
Labels: size/XS, lgtm, approved

#1571 koord-descheduler: Add Arbitration Mechanism config
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
Labels: lgtm, approved, size/L

#1576 koord-scheduler: fix missing IsParent when rebuild tree
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
Labels: lgtm, approved, size/S

#1569 koordlet: fix error in perf collector
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go
  pkg/koordlet/util/perf/perf_linux.go
Labels: size/XS, lgtm, approved

#1577 koordlet: fix http server with default pprof
  cmd/koordlet/main.go
Labels: size/XS, lgtm, approved

#1579 apis: optimize extension APIs layout
  apis/extension/device_share.go
  apis/extension/device_share_test.go
  apis/extension/load_aware.go
  apis/extension/node.go
  apis/extension/numa_aware.go
  apis/extension/resource.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/XL

#1581 apis: add NUMA-aware topology policies
  apis/extension/numa_aware.go
Labels: lgtm, approved, size/S

#1573 ci: initialize e2e workflow
  .github/workflows/e2e-k8s-1.22.yaml
  .github/workflows/e2e-k8s-1.24.yaml
  .github/workflows/e2e-k8s-latest.yaml
  config/manager/descheduler-config.yaml
  config/manager/koordlet.yaml
  config/manager/manager.yaml
  config/manager/scheduler-config.yaml
  config/manager/scheduler.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  hack/deploy_kind.sh
  test/kind-conf.yaml
Labels: lgtm, approved, size/L

#1578 koordlet: revise nri server start
  pkg/koordlet/runtimehooks/nri/server.go
  pkg/koordlet/runtimehooks/nri/server_test.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/util/system/util_test_tool.go
Labels: lgtm, approved, size/M

#1587 koordlet: fix NUMA info reporting
  pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
Labels: lgtm, approved, size/XL

#1584 koord-scheduler: add numa topology manager
  .licenseignore
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/topologymanager/manager.go
  pkg/scheduler/frameworkext/topologymanager/policy.go
  pkg/scheduler/frameworkext/topologymanager/policy_best_effort.go
  pkg/scheduler/frameworkext/topologymanager/policy_best_effort_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_none.go
  pkg/scheduler/frameworkext/topologymanager/policy_none_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_restricted.go
  pkg/scheduler/frameworkext/topologymanager/policy_restricted_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node.go
  pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_test.go
  pkg/util/bitmask/bitmask.go
  pkg/util/bitmask/bitmask_test.go
Labels: size/XXL, lgtm, approved

#1588 apis: update ResourceStatus to support NUMA-aware scheduling
  apis/extension/numa_aware.go
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
Labels: lgtm, approved, size/M

#1549 proposal: Node Resource Amplification
  docs/proposals/scheduling/20230811-node-resource-amplification.md
Labels: lgtm, approved, size/M

#1559 koord-manager: improve batch resource calculation with system metrics
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: lgtm, approved, size/L

#1591 apis: add cpu normalization ratio and cpu basic info annotations
  apis/extension/cpu_normalization.go
  apis/extension/cpu_normalization_test.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile_test.go
  pkg/koordlet/util/cpuinfo.go
Labels: lgtm, approved, size/L

#1555 koord-scheduler: export koordinator-root-quota as CRD object
  apis/extension/elastic_quota.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/elasticquota/quota_topology_check.go
Labels: lgtm, approved, size/L

#1594 koord-scheduler: deviceshare plugin skips handling nodes without device cr
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/S

#1592 koord-scheduler: support NUMA-aware scheduling
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation.go
  pkg/scheduler/plugins/nodenumaresource/cpu_manager.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager.go
  pkg/scheduler/plugins/nodenumaresource/node_allocation.go
  pkg/scheduler/plugins/nodenumaresource/node_allocation_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler_test.go
  pkg/scheduler/plugins/nodenumaresource/reservation.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/topology_options.go
  pkg/scheduler/plugins/nodenumaresource/topology_options_test.go
  test/e2e/scheduling/helper.go
  test/e2e/scheduling/nodenumaresource.go
  test/e2e/scheduling/reservation.go
Labels: size/XXL, lgtm, approved

#1596 apis: add elastic quota profile
  apis/quota/v1alpha1/elastic_quota_profile_types.go
  apis/quota/v1alpha1/groupversion_info.go
  apis/quota/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/quota.koordinator.sh_elasticquotaprofiles.yaml
  hack/update-codegen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/quota/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/quota/v1alpha1/elasticquotaprofile.go
  pkg/client/clientset/versioned/typed/quota/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/quota/v1alpha1/fake/fake_elasticquotaprofile.go
  pkg/client/clientset/versioned/typed/quota/v1alpha1/fake/fake_quota_client.go
  pkg/client/clientset/versioned/typed/quota/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/quota/v1alpha1/quota_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/quota/interface.go
  pkg/client/informers/externalversions/quota/v1alpha1/elasticquotaprofile.go
  pkg/client/informers/externalversions/quota/v1alpha1/interface.go
  pkg/client/listers/quota/v1alpha1/elasticquotaprofile.go
  pkg/client/listers/quota/v1alpha1/expansion_generated.go
Labels: size/XXL, lgtm, approved
