Repository koordinator-sh/koordinator, pull requests merged in 2023-11, with the labels that each got.

#1731 ci: disable codeql in github action workflow
  .github/workflows/codeql.yml
Labels: lgtm, approved

#1726 scheduler: numa-aware scheduling supports selecting numa node by score
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/frameworkext/topologymanager/policy.go
  pkg/scheduler/frameworkext/topologymanager/policy_best_effort_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_none_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_restricted_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node.go
  pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/util.go
Labels: lgtm, approved

#1732 scheduler: revise numa-aware hints generator
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
Labels: lgtm, approved

#1725 apis: add host application metric to node metric crd
  apis/slo/v1alpha1/nodemetric_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved

#1733 koordlet: report host application resource usage for calculating batc…
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled_test.go
  pkg/koordlet/metricsadvisor/collectors/hostapplication/host_app_collector.go
  pkg/koordlet/metricsadvisor/collectors/hostapplication/host_app_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector_test.go
  pkg/koordlet/metricsadvisor/framework/context.go
  pkg/koordlet/metricsadvisor/framework/context_test.go
  pkg/koordlet/metricsadvisor/plugins_profile.go
  pkg/koordlet/qosmanager/helpers/metrics_query.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict_test.go
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress_test.go
  pkg/koordlet/runtimehooks/protocol/host_qos_context.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
  pkg/koordlet/util/cold_page.go
  pkg/koordlet/util/cold_page_test.go
  pkg/koordlet/util/host_application.go
  pkg/koordlet/util/host_application_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/util.go
  pkg/slo-controller/noderesource/plugins/batchresource/util_test.go
Labels: lgtm, approved

#1740 scheduler: update reservationInfo ownerMatchers if reservation updated
  apis/extension/operating_pod.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/frameworkext/reservation_info_test.go
Labels: lgtm, approved

#1742 scheduler: leaky resources in ReservationInfo when pod failed to bind
  pkg/scheduler/plugins/reservation/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
Labels: lgtm, approved

#1720 apis: add core sched apis
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/pod.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/koordlet/util/cold_page.go
  pkg/util/sloconfig/nodeslo_config.go
  pkg/util/sloconfig/nodeslo_config_test.go
Labels: lgtm, approved, size/L

#1749 koordlet: fix prediction restore for node priorities
  pkg/koordlet/prediction/predict_server.go
  pkg/koordlet/prediction/predict_server_test.go
  pkg/koordlet/prediction/prediction.go
Labels: lgtm, approved, size/M

#1739 slo-controller: supppor third party allocator for batch resource calculation
  apis/slo/v1alpha1/node.go
  apis/slo/v1alpha1/node_test.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/util.go
Labels: lgtm, approved

#1752 koord-manager: get node batch allocatable from extended resource
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/util/node.go
Labels: lgtm, approved, size/S

#1598 proposal: CPU Normalization
  docs/images/cpu-normalization.svg
  docs/proposals/scheduling/20230831-cpu-normalization.md
Labels: lgtm, approved, size/L

#1755 scheduler: Add non-preemptible Request in quotaInfo's QuotaCalculateInfo
  apis/extension/elastic_quota.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_summary.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
Labels: lgtm, approved, size/L

#1751 koord-manager: improve batch resource calculation
  apis/slo/v1alpha1/nodemetric_types.go
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
  pkg/koordlet/prediction/peak_predictor.go
  pkg/koordlet/qosmanager/helpers/calculator.go
  pkg/koordlet/qosmanager/helpers/calculator_test.go
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
  pkg/koordlet/statesinformer/impl/states_pods.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
Labels: lgtm, approved, size/XL

#1763 api: add koordinator.sh/gpu.shared
  apis/extension/device_share.go
Labels: size/XS, lgtm, approved
