Repository koordinator-sh/koordinator, pull requests merged in 2023-07, with the labels that each got.

#1439 koord-scheduler: pod must declare gpu-memory or gpu-memory-ratio when applying for GPU
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/deviceshare/utils_test.go
Labels: lgtm, approved, size/XL

#1437 koord-scheduler: fix deletion of Reservation in concurrent scenarios
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/eventhandler.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/M

#1443 koord-scheduler: ElasticQuotaPlugin add RunDecoratePod in Reserve/Unreserve
  pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
  pkg/scheduler/plugins/elasticquota/plugin.go
Labels: size/XS, lgtm, approved

#1440 koord-manager: move expiring metrics into util, add prom metrics
  pkg/koordlet/metrics/common.go
  pkg/slo-controller/metrics/common.go
  pkg/slo-controller/metrics/metrics.go
  pkg/slo-controller/metrics/metrics_test.go
  pkg/slo-controller/metrics/node_resource.go
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/noderesource/framework/extender_plugin.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/nodeslo/extender_plugin.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/util/metrics/expire_metric.go
  pkg/util/metrics/expire_metric_test.go
Labels: lgtm, approved, size/L

#1447 koord-scheduler: fix missed json tag of internal configuration
  pkg/scheduler/apis/config/v1beta2/types.go
Labels: size/XS, lgtm, approved

#1394 doc: add forecasting controller proposal
  docs/images/forecasting/forecast-closure.svg
  docs/images/forecasting/forecast-grouping.svg
  docs/images/forecasting/forecasting-collect.svg
  docs/images/forecasting/forecasting-controller.svg
  docs/images/forecasting/metric-apis.svg
  docs/images/forecasting/metric-exporters.svg
  docs/images/forecasting/metric-on-node.svg
  docs/proposals/forecasting/20230613-framework-of-prediction-and-detection.md
Labels: lgtm, approved, size/L

#1448 koord-scheduler: run plugin transformers in configured order
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/framework_extender_factory_test.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
Labels: lgtm, approved, size/L

#1446 apis: add default PriorityClass and QoSClass, revise batch resource calculation
  apis/extension/priority.go
  apis/extension/priority_utils.go
  apis/extension/qos_utils.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/util/pod_qos_utils.go
Labels: lgtm, approved, size/XL

#1466 apis: add moduleID in Device CRD
  apis/scheduling/v1alpha1/device_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved, size/M

#1469 koordlet: fix scope of prodReclaimablePredictor resource reclaim
  pkg/koordlet/prediction/peak_predictor.go
  pkg/koordlet/prediction/peak_predictor_test.go
Labels: lgtm, approved, size/M

#1455 koordlet: change the `memory.high` calculation formula as 1.27
  apis/slo/v1alpha1/nodeslo_types.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile_test.go
  pkg/koordlet/util/system/common.go
Labels: lgtm, approved, size/M

#1461 apis: add priority-class compatible label
  apis/extension/constants.go
  apis/extension/priority.go
  apis/extension/priority_utils.go
  apis/extension/priority_utils_test.go
  docs/proposals/api-machinery/20230707-add-compatibility-interface-for-priority-class.md
Labels: lgtm, approved, size/L, area/api-machinery

#1462 koordlet: enhance node prediction
  apis/extension/priority.go
  pkg/koordlet/metrics/metrics.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metrics/prediction.go
  pkg/koordlet/metrics/resource_summary.go
  pkg/koordlet/prediction/peak_predictor.go
  pkg/koordlet/prediction/peak_predictor_test.go
  pkg/koordlet/prediction/predict_server.go
  pkg/koordlet/prediction/predict_server_test.go
  pkg/koordlet/prediction/prediction.go
  pkg/koordlet/prediction/prediction_test.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/util/resource.go
  pkg/util/resource_test.go
Labels: lgtm, approved, size/XL

#1471 koord-manager: add leader elect resource lock arg
  cmd/koord-manager/main.go
Labels: size/XS, lgtm, approved

#1475 koord-scheduler: optimize Coscheduling error message and logs
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
Labels: lgtm, approved, size/M

#1472 koord-scheduler: add elastic quota informer transformer
  pkg/scheduler/plugins/elasticquota/core/decorator.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/pod_handler.go
  pkg/scheduler/plugins/elasticquota/preempt.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
  pkg/util/transformer/elastic_quota_transformer.go
  pkg/util/transformer/elastic_quota_transformer_test.go
Labels: lgtm, approved, size/L

#1468 koordlet: evict pod event object use pod
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resmanager/resmanager_test.go
Labels: lgtm, approved, size/S

#1456 koord-scheduler: optimize nominate reservation
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/reservation/error_channel.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/scoring.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/XL

#1459 koord-descheduler: LowNodeLoad supports descheduling by node pool
  pkg/descheduler/apis/config/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/conversion_plugins.go
  pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/validation/validation_loadaware.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
Labels: lgtm, approved, size/L

#1451 koordlet: refactor becpu resource store
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_result.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/metriccache/mockmetriccache/mock_kv_storage.go
  pkg/koordlet/metriccache/mockmetriccache/mock_metric_result.go
  pkg/koordlet/metriccache/mockmetriccache/mock_tsdb_storage.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/koordlet/resmanager/resmanager.go
Labels: lgtm, approved, size/XL

#1478 all: fix GetPriorityClass with default
  apis/extension/priority.go
  apis/extension/priority_utils.go
  apis/extension/priority_utils_test.go
  apis/extension/qos_utils.go
  apis/extension/qos_utils_test.go
  pkg/descheduler/utils/sorter/pod.go
  pkg/descheduler/utils/sorter/pod_test.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector.go
  pkg/koordlet/resmanager/blkio_reconcile.go
  pkg/koordlet/resmanager/cgroup_reconcile.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
  pkg/scheduler/plugins/loadaware/helper.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/util/pod_qos_utils.go
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/M

#1487 apis: Device CRD add topology and virtual functions fields
  apis/scheduling/v1alpha1/device_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved, size/L

#1488 koordlet: cleanup koordlet get the cgroup driver logic
  pkg/koordlet/koordlet.go
  pkg/koordlet/util/system/cgroup_driver.go
  pkg/koordlet/util/system/cgroup_driver_linux.go
  pkg/koordlet/util/system/cgroup_driver_linux_test.go
  pkg/koordlet/util/system/cgroup_driver_unsupported.go
Labels: lgtm, approved, size/M

#1490 koord-descheduler: podMigrationJob filterExpectedReplicas
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/filter.go
Labels: lgtm, approved, size/L

#1381 koord-scheduler: Add unschedulable field to Reservation
  apis/scheduling/v1alpha1/reservation_types.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/frameworkext/reservation_info_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/M

#1492 koordlet: rename kubeClinet to kubeClient
  pkg/koordlet/qosmanager/k8s/k8s.go
Labels: size/XS, lgtm, approved

#1489 fix: reduce PMU multiplexing influence
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go
  pkg/koordlet/util/perf/perf_linux.go
  pkg/koordlet/util/stat.go
Labels: lgtm, approved, size/S

#1484 koordlet: remove dependencies of sqlite3
  go.mod
  go.sum
  hack/mock-gen.sh
  pkg/koordlet/metriccache/api.go
  pkg/koordlet/metriccache/fake_metric_cache.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/metriccache/storage.go
  pkg/koordlet/metriccache/storage_tables.go
  pkg/koordlet/metriccache/storage_test.go
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/koordlet/statesinformer/mockstatesinformer/mock.go
Labels: size/XXL, lgtm, approved

#1491 koord-manager: add noderesource plugin setup options
  pkg/slo-controller/metrics/common.go
  pkg/slo-controller/noderesource/framework/extender_plugin.go
  pkg/slo-controller/noderesource/framework/extender_plugin_test.go
  pkg/slo-controller/noderesource/framework/option.go
  pkg/slo-controller/noderesource/framework/option_test.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/plugins_profile.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: lgtm, approved, size/L

#1497 koordlet: fix util/perf compilation errors on darwin
  pkg/koordlet/util/perf/perf_unsupported.go
Labels: size/XS, lgtm, approved

#1498 koordlet: fix flaky tests
  pkg/koordlet/config/config_test.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
  pkg/koordlet/qosmanager/config/config_test.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
Labels: lgtm, approved, size/M

#1496 koord-manager: add README for noderesource framework
  docs/images/noderesource-framework.svg
  pkg/slo-controller/noderesource/framework/README.md
Labels: lgtm, approved, size/L

#1482 koordlet: fix cpi compute with CpuCyclesProfiler
  pkg/koordlet/util/perf/perf_linux.go
Labels: size/XS, lgtm, approved

#1505 koord-descheduler: PodMigrationJob supports skipping all filters
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
Labels: size/XS, lgtm, approved

#1515 chore: add unittests
  hack/run-test.sh
  pkg/koordlet/util/system/cgroup2_test.go
  pkg/koordlet/util/system/cgroup_test.go
Labels: lgtm, approved, size/XL
