Repository koordinator-sh/koordinator, pull requests merged in 2023-04, with the labels that each got.

#1168 koord-scheduler: DeviceShare ensure NodeName is not empty when handling new Pod
  pkg/scheduler/plugins/deviceshare/pod_handler.go
Labels: size/XS, lgtm, approved

#1162 koordlet: support resctrl on AMD
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/resourceexecutor/resctrl_updater.go
  pkg/koordlet/util/cpuinfo.go
  pkg/koordlet/util/system/resctrl.go
  pkg/koordlet/util/system/resctrl_linux.go
  pkg/koordlet/util/system/resctrl_linux_test.go
  pkg/koordlet/util/system/resctrl_test.go
  pkg/koordlet/util/system/resctrl_unsupported.go
Labels: lgtm, approved, size/L

#1172 koordlet: revise sysctl initialization of the group identity
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
Labels: lgtm, approved, size/L

#1173 koordlet: fix psicollector may cause other functions to block when started
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go
Labels: lgtm, approved, size/M

#1171 koord-descheduler: filter migrationJobs in running state for migration reconcile
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/filter.go
Labels: lgtm, approved, size/L, area/koord-descheduler

#1176 koord-descheduler: optimize LowNodeLoad logs
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
Labels: lgtm, approved, size/S

#1174 koord-descheduler: the reservation created during migration skips the original node
  pkg/descheduler/controllers/migration/reservation/util.go
  pkg/descheduler/controllers/migration/reservation/util_test.go
Labels: lgtm, approved, size/L, area/koord-descheduler

#1183 ci: run github actions job in parallel using matrix
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/M

#1139 koord-scheduler: enhanced reservation scheduling
  apis/extension/reservation.go
  apis/extension/reservation_test.go
  apis/extension/scheduling.go
  docs/proposals/scheduling/20220609-resource-reservation.md
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_filter_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_filter_transformer_test.go
  pkg/scheduler/frameworkext/temporary_snapshot.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/cache_test.go
  pkg/scheduler/plugins/reservation/controller/controller.go
  pkg/scheduler/plugins/reservation/controller/controller_test.go
  pkg/scheduler/plugins/reservation/controller/garbage_collection.go
  pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/controller/node_eventhandler.go
  pkg/scheduler/plugins/reservation/controller/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/controller/reservation_eventhandler.go
  pkg/scheduler/plugins/reservation/eventhandler.go
  pkg/scheduler/plugins/reservation/eventhandler_test.go
  pkg/scheduler/plugins/reservation/garbage_collection.go
  pkg/scheduler/plugins/reservation/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/rcache.go
  pkg/scheduler/plugins/reservation/reservation_info.go
  pkg/scheduler/plugins/reservation/scoring.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/scheduler/plugins/reservation/utils.go
  pkg/scheduler/plugins/reservation/utils_test.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
  pkg/util/reservation/reservation_to_pod_eventhandler.go
  pkg/util/reservation/reservation_to_pod_eventhandler_test.go
Labels: enhancement, size/XXL, lgtm, approved, area/koord-scheduler

#1170 e2e: add reservation scheduling e2e tests
  pkg/scheduler/plugins/reservation/controller/garbage_collection.go
  test/e2e/framework/manifest/manifest.go
  test/e2e/framework/replicaset/rest.go
  test/e2e/framework/replicaset/wait.go
  test/e2e/scheduling/helper.go
  test/e2e/scheduling/reservation.go
  test/e2e/testing-manifests/scheduling/simple-pod-with-reservation.yaml
  test/e2e/testing-manifests/scheduling/simple-reservation.yaml
Labels: size/XXL, lgtm, approved

#1141 koord-scheduler: support Reservation reserve devices
  apis/extension/scheduling.go
  pkg/descheduler/controllers/migration/evictor/evictor_soft.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_cache_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/pod_handler.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: enhancement, lgtm, approved, size/XL, area/koord-scheduler

#1182 koord-scheduler: fix device cache potential concurrency issue
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/pod_handler.go
Labels: lgtm, approved, size/M, area/koord-scheduler

#1140 koord-scheduler: support Reservation reserved CPU Cores
  apis/extension/resource.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
  pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation.go
  pkg/scheduler/plugins/nodenumaresource/cpu_allocation_test.go
  pkg/scheduler/plugins/nodenumaresource/cpu_manager.go
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
Labels: enhancement, lgtm, approved, size/XL, area/koord-scheduler

#1193 Update ADOPTERS.md
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#1196 koord-scheduler: optimize ElasticQuota preemption performance
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/preempt.go
Labels: lgtm, approved, size/L, area/koord-scheduler

#1180 koordlet: improve koordlet profiling and logs
  cmd/koordlet/main.go
  cmd/koordlet/options/options.go
  pkg/koordlet/config/config.go
Labels: lgtm, approved, size/M

#1197 koord-scheduler: fix pods outside the Reservation preempt pods in the Reservation
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_cache_test.go
  test/e2e/scheduling/helper.go
  test/e2e/scheduling/preemption.go
  test/e2e/scheduling/reservation.go
Labels: lgtm, approved, size/XL, area/koord-scheduler

#1202 chore: update license ignore
  .licenseignore
  test/e2e/scheduling/preemption.go
Labels: lgtm, approved, size/S

#1203 ci: include test folder in license check
  .github/workflows/license.yml
Labels: size/XS, lgtm, approved

#1208 koordlet: cleanup runtimehooks and remove the unused code.
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
Labels: size/XS, lgtm, approved

#1212 koordlet: improve newKubeletStub method.
  pkg/koordlet/statesinformer/states_pods.go
Labels: size/XS, lgtm, approved

#1209 koordlet: fix statsinformer interface function implementation.
  pkg/koordlet/statesinformer/states_device_linux.go
  pkg/koordlet/statesinformer/states_informer.go
Labels: lgtm, approved, size/S

#1222 koordlet: fix koordlet batchresource when batch resource limit is not set
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
  test/e2e/slocontroller/batchresource.go
Labels: lgtm, approved, size/L

#1221 koordlet: reduce the frequency of updating NodeResourceTopology
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
Labels: size/XS, lgtm, approved

#1225 koord-scheduler: support System QOS reserved cpus
  pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
Labels: lgtm, approved, size/M

#1217 apis: Node Resource Reservation supports apply policy
  apis/extension/node_reservation.go
  docs/proposals/scheduling/20221227-node-resource-reservation.md
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer_test.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/util/node.go
  pkg/util/node_test.go
Labels: lgtm, approved, size/L

#1227 tests: add tests for LoadAwareScheduling estimator
  pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
Labels: lgtm, approved, size/M

#1234 koordlet: revise metrics labels and states_informer
  pkg/koordlet/metrics/metrics.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metrics/resource_summary.go
  pkg/koordlet/statesinformer/registry.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/koordlet/statesinformer/states_node.go
  pkg/koordlet/statesinformer/states_pods.go
Labels: lgtm, approved, size/M

#1239 koord-scheduler: optimize the criteria for whether the Reservation is allocated
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: size/XS, lgtm, approved

#1240 koord-descheduler: LowNodeLoad supports configuring resourceWeights
  pkg/descheduler/apis/config/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/defaults_test.go
  pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
  pkg/descheduler/utils/sorter/pod.go
  pkg/descheduler/utils/sorter/pod_test.go
  pkg/descheduler/utils/sorter/scorer.go
Labels: lgtm, approved, size/L

#1233 koord-manager: refactor config validation by github.com/go-playground
  apis/extension/slo_controller_config.go
  apis/slo/v1alpha1/nodeslo_types.go
  go.mod
  pkg/util/sloconfig/config.go
  pkg/util/sloconfig/validator.go
  pkg/util/sloconfig/validator_test.go
  pkg/webhook/cm/plugins/sloconfig/checker.go
  pkg/webhook/cm/plugins/sloconfig/checker_test.go
  pkg/webhook/cm/plugins/sloconfig/colocation_checker.go
  pkg/webhook/cm/plugins/sloconfig/colocation_checker_test.go
  pkg/webhook/cm/plugins/sloconfig/cpu_burst_checker.go
  pkg/webhook/cm/plugins/sloconfig/cpu_burst_checker_test.go
  pkg/webhook/cm/plugins/sloconfig/resource_qos_checker.go
  pkg/webhook/cm/plugins/sloconfig/resource_qos_checker_test.go
  pkg/webhook/cm/plugins/sloconfig/resource_threshold_checker.go
  pkg/webhook/cm/plugins/sloconfig/system_config_checker.go
Labels: lgtm, approved, size/XL

#1223 koordlet: adjust node comparison method to improve program performance
  pkg/koordlet/statesinformer/states_node.go
Labels: size/XS, lgtm, approved

#1144 koordlet: support block I/O QoS
  apis/extension/pod.go
  apis/extension/slo_controller_config.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/features/koordlet_features.go
  pkg/koordlet/metriccache/api.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/metriccache/storage_tables.go
  pkg/koordlet/metrics/common.go
  pkg/koordlet/metricsadvisor/collectors/nodecpuinfo/node_info_collector.go
  pkg/koordlet/metricsadvisor/collectors/nodestorageinfo/node_info_collector.go
  pkg/koordlet/metricsadvisor/framework/config.go
  pkg/koordlet/metricsadvisor/framework/config_test.go
  pkg/koordlet/metricsadvisor/metrics_advisor.go
  pkg/koordlet/resmanager/blkio_reconcile.go
  pkg/koordlet/resmanager/blkio_reconcile_test.go
  pkg/koordlet/resmanager/resmanager.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/statesinformer/mockstatesinformer/mock.go
  pkg/koordlet/statesinformer/registry.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_pvc.go
  pkg/koordlet/util/cgroup_parent_utils.go
  pkg/koordlet/util/node.go
  pkg/koordlet/util/storageinfo.go
  pkg/koordlet/util/storageinfo_test.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/resource.go
  pkg/koordlet/util/system/util_test_tool.go
  pkg/koordlet/util/system/validator.go
  pkg/util/utils.go
Labels: enhancement, size/XXL, lgtm, approved, area/koordlet

#1243 koord-scheduler: skip daemonset usageThreshold check
  pkg/scheduler/plugins/loadaware/helper.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/M

#1254 koordlet: update dockerfile and yaml file of koordlet
  config/manager/koordlet.yaml
  docker/koordlet.dockerfile
Labels: size/XS, lgtm, approved

#1253 koordlet: disable unnecessary collector and informer is blkio qos fea…
  config/rbac/koordlet.yaml
  pkg/features/koordlet_features.go
  pkg/koordlet/metricsadvisor/collectors/nodestorageinfo/node_info_collector.go
  pkg/koordlet/statesinformer/states_pvc.go
Labels: lgtm, approved, size/S

#1248 koordlet: support sandbox cpuset for rund
  pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/util/cgroup_parent_utils.go
  pkg/koordlet/util/pod.go
  pkg/koordlet/util/pod_test.go
  pkg/koordlet/util/system/cgroup_driver.go
Labels: lgtm, approved, size/L

#1255 koordlet: compare the nodeMetric generation to improve the nodemetric informer updateFunc performance
  pkg/koordlet/statesinformer/states_nodemetric.go
Labels: size/XS, lgtm, approved

#1257 koordlet: generate mock states informer
  hack/mock-gen.sh
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/statesinformer/callback_runner_test.go
  pkg/koordlet/statesinformer/mockstatesinformer/mock.go
  pkg/koordlet/statesinformer/registry.go
  pkg/koordlet/statesinformer/states_device_linux_test.go
  pkg/koordlet/statesinformer/states_informer.go
  pkg/koordlet/statesinformer/states_informer_test.go
  pkg/koordlet/statesinformer/states_node.go
  pkg/koordlet/statesinformer/states_nodemetric.go
  pkg/koordlet/statesinformer/states_nodemetric_test.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
  pkg/koordlet/statesinformer/states_nodeslo.go
  pkg/koordlet/statesinformer/states_pods.go
  pkg/koordlet/statesinformer/states_pvc.go
Labels: lgtm, approved, size/L

#1242 koord-descheduler: add leaderelection metric
  cmd/koord-descheduler/main.go
Labels: size/XS, lgtm, approved

#1235 koord-manager: add args for common controllers
  cmd/koord-manager/main.go
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
Labels: lgtm, approved, size/M

#1259 bugfix: when cpuset is an empty string, error log
  pkg/koordlet/runtimehooks/protocol/container_context.go
Labels: size/XS, lgtm, approved
