Repository koordinator-sh/koordinator, pull requests merged in 2023-12, with the labels that each got.

#1529 proposal: add device allocation apis
  docs/proposals/scheduling/20230803-device-allocate-hint-apis.md
Labels: lgtm, approved, size/L

#1766 apis: add device allocate hints
  apis/extension/device_share.go
Labels: lgtm, approved, size/L

#1769 chore: fix koordinator typo
  cmd/koord-runtime-proxy/main.go
  docs/images/forecasting/metric-apis.svg
  docs/proposals/api-machinery/20220707-rename-extended-resource.md
  docs/proposals/forecasting/20230613-framework-of-prediction-and-detection.md
  docs/proposals/scheduling/20220513-enhanced-scheduler-extension.md
  docs/proposals/scheduling/20220701-simple-descheduler-framework.md
  docs/proposals/scheduling/20230803-enhance-gpu-share-api.md
Labels: lgtm, approved, size/S

#1738 koordlet: add page cache collector unit test and mend default cold memory config
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled_test.go
  pkg/koordlet/metricsadvisor/collectors/pagecache/page_cache_collector_test.go
  pkg/koordlet/resourceexecutor/reader_test.go
  pkg/koordlet/util/cold_page.go
  pkg/koordlet/util/cold_page_test.go
  pkg/koordlet/util/meminfo.go
  pkg/koordlet/util/meminfo_test.go
  pkg/koordlet/util/system/kidled_util.go
  pkg/koordlet/util/system/kidled_util_test.go
Labels: lgtm, approved, size/XL

#1775 koordlet: report gpu device topology
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux_test.go
  pkg/koordlet/metricsadvisor/devices/gpu/helper.go
  pkg/koordlet/metricsadvisor/devices/gpu/helper_test.go
  pkg/koordlet/statesinformer/impl/states_device_linux.go
  pkg/koordlet/statesinformer/impl/states_device_linux_test.go
  pkg/koordlet/util/device.go
  pkg/koordlet/util/system/system_file.go
Labels: lgtm, approved, size/L

#1744 koordlet: support hugepage reporting
  pkg/features/koordlet_features.go
  pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector.go
  pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector_test.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
  pkg/koordlet/util/meminfo.go
  pkg/koordlet/util/meminfo_test.go
  pkg/koordlet/util/system/system_file.go
Labels: size/XXL, lgtm, approved

#1782 scheduler: fix redundant argument when create a unschedulable status.
  pkg/scheduler/plugins/coscheduling/core/core.go
Labels: size/XS, lgtm, approved

#1774 scheduler: DeviceShare supports numa-aware scheduling
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/device_allocator_test.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/deviceshare/scoring.go
  pkg/scheduler/plugins/deviceshare/scoring_test.go
  pkg/scheduler/plugins/deviceshare/topology_hint.go
  pkg/scheduler/plugins/deviceshare/topology_hint_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
Labels: size/XXL, lgtm, approved

#1788 scheduler: fix DeviceShare concurrent map read and map write
  pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
Labels: size/XS, lgtm, approved

#1790 scheduler: Coscheduling skips check schedule cycle if pod has nominated node
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
Labels: lgtm, approved, size/S

#1791 scheduler: DeviceShare skips numa-aware if no device requests
  pkg/scheduler/plugins/deviceshare/topology_hint.go
Labels: size/XS, lgtm, approved

#1792 koordlet: fix lscpu for arm64
  pkg/koordlet/util/system/lscpu_arm64.go
Labels: lgtm, approved, size/S

#1793 koordlet: revise system qos and numa aware cpuset
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
Labels: lgtm, approved, size/L

#1794 koordlet: fix lscpu for arm ut
  pkg/koordlet/util/cpuinfo_test.go
Labels: size/XS, lgtm, approved

#1781 colocationprofile: support mutating pod labels and annotations with mapping
  apis/config/v1alpha1/cluster_colocation_profile_types.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/L

#1795 chores: add args for Makefile
  Makefile
Labels: lgtm, approved, size/S

#1800 scheduler: Reservation supports preempting permitted pods
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/M

#1802 scheduler: fix the calculation method in PreFilterExtension
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/deviceshare/device_resources.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/L
