Repository koordinator-sh/koordinator, pull requests merged in 2023-09, with the labels that each got.

#1601 apis: remove omitempty tag of Device's field health
  apis/scheduling/v1alpha1/device_types.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved, size/S

#1597 koord-manager: cleanup node.alloc when device cr have been deleted
  pkg/slo-controller/noderesource/device_resource_calculator.go
  pkg/slo-controller/noderesource/device_resource_calculator_test.go
Labels: lgtm, approved, size/L

#1508 apis: add HostApplications for out-of-band application
  Makefile
  apis/configuration/slo_controller_config.go
  apis/configuration/zz_generated.deepcopy.go
  apis/slo/v1alpha1/host_application.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/features/koordlet_features.go
Labels: lgtm, approved, size/L

#1583 koord-scheduler: fix runtime quota when quota is not allow lent resource
  apis/extension/elastic_quota.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_summary.go
Labels: lgtm, approved, size/L

#1600 koord-scheduler: supports plugins to adjust reservation reusable resources
  pkg/features/scheduler_features.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/service_test.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
  test/e2e/scheduling/deviceshare.go
Labels: lgtm, approved, size/XL

#1603 Add multi quota tree
  hack/update-codegen.sh
  pkg/client/clientset/versioned/typed/quota/v1alpha1/fake/fake_elasticquotaprofile.go
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/elasticquota/controller_test.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/profile_handler.go
  pkg/scheduler/plugins/elasticquota/profile_handler_test.go
Labels: lgtm, approved, size/XL

#1607 koord-scheduler: ignore non-existing resources in NUMA Node
  pkg/scheduler/frameworkext/topologymanager/manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
Labels: lgtm, approved, size/L

#1610 koord-scheduler: update NodeNUMAResource plugin args
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/M

#1612 koord-scheduler: update Node capacity by profile
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/node_handler_test.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/profile_handler.go
Labels: lgtm, approved, size/XL

#1611 koord-scheduler: optimize NUMA Topology Manager interface
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/topologymanager/manager.go
  pkg/scheduler/frameworkext/topologymanager/policy_test.go
  pkg/scheduler/frameworkext/topologymanager/store.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_options_test.go
Labels: lgtm, approved, size/L

#1619 apis: mark device health defaults to false
  apis/scheduling/v1alpha1/device_types.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: size/XS, lgtm, approved

#1605 koord-manager: add quota profile controller
  apis/extension/elastic_quota.go
  apis/quota/v1alpha1/elastic_quota_profile_types.go
  apis/quota/v1alpha1/zz_generated.deepcopy.go
  cmd/koord-manager/options/controllers.go
  cmd/koord-manager/options/scheme.go
  config/crd/bases/quota.koordinator.sh_elasticquotaprofiles.yaml
  pkg/quota-controller/profile/profile_controller.go
  pkg/quota-controller/profile/profile_controller_test.go
Labels: lgtm, approved, size/L

#1609 koord-scheduler: numa-aware scheduling supports scoring
  .licenseignore
  pkg/scheduler/frameworkext/topologymanager/policy.go
  pkg/scheduler/plugins/nodenumaresource/least_allocated.go
  pkg/scheduler/plugins/nodenumaresource/most_allocated.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/scoring_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/util.go
Labels: lgtm, approved, size/XL

#1620 koord-manager: fix role for elasticquotaprofile
  PROJECT
  config/crd/kustomization.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/scheduler_role.yaml
  pkg/quota-controller/profile/profile_controller.go
Labels: lgtm, approved, size/M

#1586 koord-descheduler: add Arbitrator
  pkg/descheduler/controllers/migration/arbitrator/arbitrator.go
  pkg/descheduler/controllers/migration/arbitrator/arbitrator_test.go
Labels: size/XXL, lgtm, approved

#1566 koord-scheduler: add annotation about namespaces that limit quota usage
  apis/extension/elastic_quota.go
  docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_helper_test.go
  pkg/util/fieldindex/register.go
  pkg/webhook/elasticquota/pod_check.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/L

#1622 apis: introduce api for node resource amplification
  apis/extension/node_resource_amplification.go
  apis/extension/node_resource_amplification_test.go
Labels: lgtm, approved, size/XL

#1604 koordlet: report CPUBasicInfo, adjust normalized cpu cgroups
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
  pkg/koordlet/qosmanager/plugins/cgreconcile/cgroup_reconcile_test.go
  pkg/koordlet/resourceexecutor/executor.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule_test.go
  pkg/koordlet/runtimehooks/hooks/cpunormalization/cpu_normalization.go
  pkg/koordlet/runtimehooks/hooks/cpunormalization/cpu_normalization_test.go
  pkg/koordlet/runtimehooks/hooks/cpunormalization/rule.go
  pkg/koordlet/runtimehooks/hooks/cpunormalization/rule_test.go
  pkg/koordlet/runtimehooks/nri/server.go
  pkg/koordlet/runtimehooks/nri/server_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/container_context_test.go
  pkg/koordlet/runtimehooks/protocol/kubeqos_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context_test.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/protocol/protocol_test.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/statesinformer/api.go
  pkg/koordlet/statesinformer/impl/callback_runner.go
  pkg/koordlet/statesinformer/impl/states_node.go
  pkg/koordlet/statesinformer/impl/states_node_test.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
  pkg/koordlet/util/container.go
  pkg/koordlet/util/cpuinfo.go
  pkg/koordlet/util/cpuinfo_test.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/resctrl.go
  pkg/koordlet/util/system/resctrl_linux.go
  pkg/koordlet/util/system/system_file.go
Labels: size/XXL, lgtm, approved

#1599 koord-manager: support cpu normalization
  apis/configuration/slo_controller_config.go
  apis/configuration/zz_generated.deepcopy.go
  apis/extension/cpu_normalization.go
  apis/extension/cpu_normalization_test.go
  pkg/slo-controller/noderesource/framework/option.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/configmap_event_handler.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/configmap_event_handler_test.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/noderesourcetopology_event_handler.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/noderesourcetopology_event_handler_test.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin_test.go
  pkg/slo-controller/noderesource/plugins_profile.go
Labels: size/XXL, lgtm, approved

#1628 koord-scheduler: support required CPU bind policy
  apis/extension/numa_aware.go
  docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
Labels: lgtm, approved, size/XL

#1630 ci: fix koord-manager role and ignore errors in e2e job
  .github/workflows/e2e-k8s-1.22.yaml
  .github/workflows/e2e-k8s-1.24.yaml
  .github/workflows/e2e-k8s-latest.yaml
  config/rbac/role.yaml
  hack/deploy_kind.sh
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
Labels: lgtm, approved, size/S

#1621 koord-scheduler: update quota and pod handle for elasticquotaprofile
  apis/extension/elastic_quota.go
  pkg/quota-controller/profile/profile_controller.go
  pkg/quota-controller/profile/profile_controller_test.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/controller_test.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/node_handler_test.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/pod_handler.go
  pkg/scheduler/plugins/elasticquota/profile_handler.go
  pkg/scheduler/plugins/elasticquota/profile_handler_test.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
  pkg/scheduler/plugins/elasticquota/quota_handler_test.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
  pkg/webhook/elasticquota/quota_info.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
  pkg/webhook/elasticquota/validating/validating_handler_test.go
Labels: size/XXL, lgtm, approved

#1632 ci: remove quota profile rbac role for koord-scheduler
  config/rbac/scheduler_role.yaml
Labels: size/XS, lgtm, approved

#1626 koordlet: report be cpu share pool and set cpuset if specified
  apis/extension/numa_aware.go
  pkg/features/koordlet_features.go
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
Labels: lgtm, approved, size/XL

#1625 koord-descheduler: add some SortFns for arbitration
  pkg/descheduler/controllers/migration/arbitrator/arbitrator.go
  pkg/descheduler/controllers/migration/arbitrator/sort.go
  pkg/descheduler/controllers/migration/arbitrator/sort_test.go
Labels: lgtm, approved, size/XL

#1635 ci: fix quota webhook verb
  config/webhook/manifests.yaml
  pkg/webhook/elasticquota/validating/webhooks.go
Labels: size/XS, lgtm, approved

#1637 koord-scheduler: ElasticQuota plugin implements EnqueueExtensions
  pkg/scheduler/plugins/elasticquota/plugin.go
Labels: lgtm, approved, size/S

#1636 koord-scheduler: add ElasticQuotaIgnoreOverhead feature-gate
  apis/extension/elastic_quota.go
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/helper.go
  pkg/scheduler/plugins/elasticquota/core/helper_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/preempt.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
Labels: lgtm, approved, size/L

#1633 koord-scheduler: framework extension executes handler after handling scheduling errors
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/errorhandler_dispatcher.go
  pkg/scheduler/frameworkext/errorhandler_dispatcher_test.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/scheduler_adapter.go
Labels: lgtm, approved, size/M

#1640 koordlet: report NRT zone resources mergeable
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
  pkg/util/resource.go
  pkg/util/resource_test.go
Labels: lgtm, approved, size/L

#1638 koordlet: support qos for out-of-band applications
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/config_test.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
  pkg/koordlet/runtimehooks/hooks/batchresource/rule_test.go
  pkg/koordlet/runtimehooks/hooks/cpunormalization/rule.go
  pkg/koordlet/runtimehooks/hooks/cpunormalization/rule_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/koordlet/runtimehooks/protocol/host_qos_context.go
  pkg/koordlet/runtimehooks/protocol/host_qos_context_test.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/reconciler/host_app_reconciler.go
  pkg/koordlet/runtimehooks/reconciler/host_app_reconciler_test.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/koordlet/statesinformer/api.go
  pkg/koordlet/statesinformer/impl/callback_runner.go
  pkg/koordlet/statesinformer/impl/callback_runner_test.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
Labels: size/XXL, lgtm, approved, area/koordlet, area/koord-manager

#1647 koord-scheduler: NodeNUMAResource only consider allocatable when generating hints
  pkg/scheduler/plugins/nodenumaresource/node_allocation.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler_test.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  test/e2e/scheduling/nodenumaresource.go
Labels: lgtm, approved, size/L

#1554 koordlet: add libpfm4&perf group
  .github/workflows/ci.yaml
  Makefile
  docker/koordlet.dockerfile
  go.mod
  go.sum
  pkg/features/koordlet_features.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
  pkg/koordlet/util/perf/perf_linux.go
  pkg/koordlet/util/perf_group/perf_group_linux.go
  pkg/koordlet/util/perf_group/perf_group_linux_test.go
  pkg/koordlet/util/stat.go
  pkg/koordlet/util/stat_test.go
Labels: lgtm, approved, size/XL

#1641 koordlet: revise BECPUEvict, RdtResctrl, CPUSetAllocator and system collector
  apis/slo/v1alpha1/nodeslo_types.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector_test.go
  pkg/koordlet/metricsadvisor/framework/config.go
  pkg/koordlet/metricsadvisor/framework/config_test.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict_test.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile_test.go
  pkg/koordlet/qosmanager/qosmanager.go
  pkg/koordlet/resourceexecutor/cgroup.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
  pkg/koordlet/statesinformer/impl/states_nodeslo_test.go
  pkg/koordlet/util/cpuinfo.go
  pkg/koordlet/util/system/resctrl.go
  pkg/koordlet/util/system/resctrl_linux.go
  pkg/koordlet/util/system/resctrl_test.go
  pkg/koordlet/util/system/util_test_tool.go
  pkg/util/resource.go
  pkg/util/resource_test.go
  pkg/util/sloconfig/nodeslo_config.go
Labels: size/XXL, lgtm, approved

#1653 koordlet: add perf cgroup unsupported
  pkg/koordlet/util/perf/perf_unsupported.go
  pkg/koordlet/util/perf_group/perf_group_linux.go
  pkg/koordlet/util/perf_group/perf_group_linux_test.go
  pkg/koordlet/util/perf_group/perf_group_unsupported.go
  pkg/koordlet/util/stat_test.go
Labels: lgtm, approved, size/M

#1660 koord-manager: fix LessThanOrEqual in elastic quota
  pkg/util/resource.go
  pkg/util/resource_test.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/L

#1657 koord-scheduler: revise NodeNUMAResource
  apis/extension/numa_aware.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
Labels: lgtm, approved, size/L

#1642 Add new adopter
  ADOPTERS.md
Labels: lgtm, approved, size/S

#1663 koordlet: fix resource qos rules missing LSE
  pkg/koordlet/qosmanager/helpers/property.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
Labels: lgtm, approved, size/M

#1631 koord-manager: add NUMA-level batch resources
  pkg/slo-controller/noderesource/framework/extender_plugin.go
  pkg/slo-controller/noderesource/framework/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/noderesourcetopology_event_handler.go
  pkg/slo-controller/noderesource/plugins/batchresource/noderesourcetopology_event_handler_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/util.go
  pkg/slo-controller/noderesource/plugins/batchresource/util_test.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin_test.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin.go
  pkg/slo-controller/noderesource/plugins_profile.go
Labels: size/XXL, lgtm, approved

#1661 Makefile: fix libpfm4 make test
  Makefile
  hack/libpfm.sh
Labels: lgtm, approved, size/M

#1664 Makefile: exit for macOS
  hack/libpfm.sh
Labels: size/XS, lgtm, approved

#1645 koord-scheduler: add ElasticQuota Guaranteed usage
  apis/extension/elastic_quota.go
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
  pkg/webhook/elasticquota/quota_info.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/XL

#1666 koord-scheduler: export min/max getters of QuotaInfo as public
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
Labels: lgtm, approved, size/S

#1665 add DisableDefaultQuota featuregate
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/pod_handler.go
  pkg/scheduler/plugins/elasticquota/pod_handler_test.go
  pkg/webhook/elasticquota/pod_check.go
Labels: lgtm, approved, size/L

#1667 koord-manager: calculate batch resource with kubelet reserved
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/util.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/util/node.go
  pkg/util/node_test.go
Labels: lgtm, approved, size/L

#1669 koord-scheduler: optimize NodeNUMAResource scoring
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/scoring_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/util.go
Labels: lgtm, approved, size/XL

#1673 koord-scheduler: LoadAware supports node amplification ratios
  pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
Labels: lgtm, approved, size/M

#1674 koord-scheduler: update elastic quota endpoint
  pkg/scheduler/plugins/elasticquota/plugin_service.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
Labels: size/XS, lgtm, approved

#1574 koordlet: add cold memory collection and reporting
  pkg/features/koordlet_features.go
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_collector.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled_test.go
  pkg/koordlet/metricsadvisor/framework/config.go
  pkg/koordlet/metricsadvisor/framework/config_test.go
  pkg/koordlet/metricsadvisor/plugins_profile.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/reader_test.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
  pkg/koordlet/util/cold_page.go
  pkg/koordlet/util/cold_page_test.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/kidled_util.go
  pkg/koordlet/util/system/kidled_util_test.go
  pkg/koordlet/util/system/system_resource.go
  pkg/koordlet/util/system/system_resource_test.go
Labels: size/XXL, lgtm, approved

#1672 koord-scheduler: inplace update quota min and max
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: lgtm, approved, size/L

#1671 koord-scheduler: NodeNUMAResource supports amplification ratios
  apis/extension/node_resource_amplification.go
  apis/extension/node_resource_amplification_test.go
  pkg/scheduler/plugins/nodenumaresource/node_allocation.go
  pkg/scheduler/plugins/nodenumaresource/node_allocation_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service.go
  pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/topology_options.go
  pkg/scheduler/plugins/nodenumaresource/util.go
Labels: lgtm, approved, size/XL

#1675 koord-scheduler: add e2e case for multi quota tree
  apis/extension/elastic_quota.go
  pkg/webhook/elasticquota/quota_topology.go
  test/e2e/e2e_test.go
  test/e2e/quota/framework.go
  test/e2e/quota/multi_tree.go
Labels: lgtm, approved, size/XL

#1678 koord-scheduler: fix root quota when deleted
  pkg/scheduler/plugins/elasticquota/quota_handler.go
  pkg/scheduler/plugins/elasticquota/quota_handler_test.go
Labels: lgtm, approved, size/S

#1679 koord-manager: fix quota profile resource ratio
  pkg/quota-controller/profile/profile_controller.go
  pkg/quota-controller/profile/profile_controller_test.go
Labels: lgtm, approved, size/M

#1677 koord-scheduler: NodeNUMAResource supports filtering/scoring with node-level amplification ratios
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/scoring_test.go
  pkg/scheduler/plugins/nodenumaresource/service.go
  pkg/scheduler/plugins/nodenumaresource/service_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_options_test.go
Labels: lgtm, approved, size/XL

#1683 koord-scheduler: NodeNUMAResource scoring fix and tweak with node-level amplification ratios
  apis/extension/node_resource_amplification.go
  apis/extension/node_resource_amplification_test.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
Labels: lgtm, approved, size/M

#1685 e2e: add basic quota e2e cases
  pkg/scheduler/plugins/elasticquota/quota_handler.go
  test/e2e/quota/multi_tree.go
  test/e2e/quota/quota.go
  test/e2e/quota/quota_guaranteed.go
Labels: lgtm, approved, size/L

#1682 koord-scheduler: fix NodeNUMAResource allocate CPUSets on mixed CPUSet/Share NUMA Node
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
Labels: lgtm, approved, size/L

#1684 koordlet: revise logs in be suppress and batch resource
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
  pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
Labels: lgtm, approved, size/S

#1593 Fix runtime proxy compatibility with CRI interface version
  cmd/koord-runtime-proxy/main.go
  cmd/koord-runtime-proxy/options/options.go
  go.mod
  go.sum
  hack/mock-gen.sh
  pkg/koordlet/util/runtime/handler/containerd_runtime.go
  pkg/koordlet/util/runtime/handler/mockclient/mock.go
  pkg/runtimeproxy/client/mock/mockhookclient.go
  pkg/runtimeproxy/config/mock/mockconfig.go
  pkg/runtimeproxy/dispatcher/dispatcher_test.go
  pkg/runtimeproxy/mock/runtimeproxy-client.go
  pkg/runtimeproxy/resexecutor/cri/container.go
  pkg/runtimeproxy/resexecutor/cri/container_test.go
  pkg/runtimeproxy/resexecutor/cri/pod.go
  pkg/runtimeproxy/resexecutor/cri/pod_test.go
  pkg/runtimeproxy/resexecutor/cri/utils.go
  pkg/runtimeproxy/resexecutor/cri/utils_test.go
  pkg/runtimeproxy/server/cri/criserver.go
  pkg/runtimeproxy/server/cri/image.go
  pkg/runtimeproxy/server/cri/runtime.go
  pkg/runtimeproxy/server/cri/utils.go
Labels: size/XXL, lgtm, approved

#1687 refactor codes to help readability
  pkg/features/features.go
  pkg/util/resource.go
  pkg/util/resource_test.go
  pkg/webhook/elasticquota/pod_check.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/L

#1651 koord-descheduler: add arbitration to migration controller
  pkg/descheduler/controllers/migration/arbitrator/arbitrator.go
  pkg/descheduler/controllers/migration/arbitrator/arbitrator_test.go
  pkg/descheduler/controllers/migration/arbitrator/filter.go
  pkg/descheduler/controllers/migration/arbitrator/filter_test.go
  pkg/descheduler/controllers/migration/arbitrator/handler.go
  pkg/descheduler/controllers/migration/arbitrator/sort.go
  pkg/descheduler/controllers/migration/arbitrator/sort_test.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
Labels: size/XXL, lgtm, approved

#1686 koord-scheduler: add decorator for quota
  apis/extension/elastic_quota.go
  pkg/quota-controller/profile/profile_controller.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: lgtm, approved, size/L

#1690 koord-scheduler: optimize elastic quota log
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
  pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
  pkg/scheduler/plugins/elasticquota/pod_handler.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
Labels: lgtm, approved, size/L

#1693 webhook: revise the validation of Pod resources
  pkg/webhook/pod/validating/cluster_colocation_profile.go
  pkg/webhook/pod/validating/cluster_colocation_profile_test.go
  pkg/webhook/pod/validating/request_limit_validator.go
Labels: lgtm, approved, size/XL
