Repository koordinator-sh/koordinator, pull requests merged in 2023-06, with the labels that each got.

#1337 koord-yarn: add pkg dir for YARN related modules
  OWNERS_ALIASES
  pkg/yarn/OWNERS
  pkg/yarn/controller/OWNERS
  pkg/yarn/copilot/OWNERS
Labels: lgtm, approved, size/M

#1341 koord-scheduler: fix leaky operating pod in reservation
  pkg/scheduler/plugins/reservation/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
Labels: lgtm, approved, size/M

#1342 koord-scheduler: export ReservationInfos via service endpoint
  pkg/scheduler/plugins/reservation/service.go
  pkg/scheduler/plugins/reservation/service_test.go
Labels: lgtm, approved, size/L

#1334 koordlet: refactor pod/container metrics to tsdb
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux.go
  pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux_test.go
  pkg/koordlet/metricsadvisor/framework/plugin.go
  pkg/koordlet/qosmanager/metricsquery/metrics_query.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_evict.go
  pkg/koordlet/resmanager/cpu_evict_test.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/memory_evict.go
  pkg/koordlet/resmanager/memory_evict_test.go
  pkg/koordlet/resmanager/metrics_query.go
  pkg/koordlet/resmanager/metrics_query_test.go
  pkg/koordlet/statesinformer/states_nodemetric.go
  pkg/koordlet/statesinformer/states_nodemetric_test.go
Labels: size/XXL, lgtm, approved

#1347 chore: resolve failed unit tests
  pkg/scheduler/plugins/reservation/service_test.go
Labels: size/XS, lgtm, approved

#1352 apis: support Hygon DCU device resource API
  apis/extension/resource.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/deviceshare/utils_test.go
Labels: lgtm, approved, size/M

#1353 koordlet: fix cgroup driver detection on cgroups-v2, revise UTs
  pkg/koordlet/koordlet.go
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
  pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector_test.go
  pkg/koordlet/util/node.go
  pkg/koordlet/util/pod.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/cgroup_driver.go
  pkg/koordlet/util/system/cgroup_driver_linux.go
  pkg/koordlet/util/system/cgroup_driver_linux_test.go
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/version.go
Labels: lgtm, approved, size/L

#1351 koord-scheduler: coscheduling supports skipping check schedule cycle
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
Labels: lgtm, approved, size/M

#1358 koordlet: fix flaky test of BEResourceCollector
  pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector.go
  pkg/koordlet/pleg/pleg_test.go
  pkg/koordlet/util/system/cgroup2.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/util_test_tool.go
Labels: lgtm, approved, size/S

#1362 koord-descheduler: compatible with k8s v1.21.x no policy/v1/eviction
  pkg/descheduler/evictions/utils/utils.go
Labels: size/XS, lgtm, approved

#1354 koord-scheduler: strictly check whether ReservationInfo is available or terminating
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/frameworkext/reservation_info_test.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/service_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/L

#1365 add a histogram util
  .licenseignore
  pkg/util/histogram/decaying_histogram.go
  pkg/util/histogram/decaying_histogram_test.go
  pkg/util/histogram/histogram.go
  pkg/util/histogram/histogram_checkpoint.go
  pkg/util/histogram/histogram_mock.go
  pkg/util/histogram/histogram_options.go
  pkg/util/histogram/histogram_options_test.go
  pkg/util/histogram/histogram_test.go
Labels: size/XXL, lgtm, approved

#1360 koord-scheduler: optimize the Reservation deletion process
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/scheduler/frameworkext/scheduler_adapter.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/cache_test.go
  pkg/scheduler/plugins/reservation/eventhandler.go
  pkg/scheduler/plugins/reservation/eventhandler_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/service.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: size/XXL, lgtm, approved

#1364 koord-scheduler: only remove unallocated ports if Reservation released
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/plugins/reservation/service.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/util/hostport.go
  pkg/util/hostport_test.go
  test/e2e/scheduling/hostport.go
Labels: size/XXL, lgtm, approved

#1336 koordlet: pod/container PSI/CPI metircs cache to tsdb
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
  pkg/util/utils.go
Labels: size/XXL, lgtm, approved

#1369 koord-scheduler: reject waiting reserve pod if reservation has been deleted
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
Labels: lgtm, approved, size/M

#1370 koord-scheduler: complement Coscheduling plugin's onPodUpdate handler
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
Labels: lgtm, approved, size/L

#1392 koordlet: fix node memory collection
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector_test.go
  pkg/koordlet/statesinformer/states_nodemetric.go
  pkg/koordlet/statesinformer/states_pods.go
Labels: lgtm, approved, size/L, ok-to-test

#1384 koordlet: refactor info-type resource to kv
  pkg/koordlet/metriccache/api.go
  pkg/koordlet/metriccache/kv_storage.go
  pkg/koordlet/metriccache/metric_cache.go
  pkg/koordlet/metriccache/metric_cache_test.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metriccache/mockmetriccache/mock.go
  pkg/koordlet/metricsadvisor/collectors/nodecpuinfo/node_info_collector.go
  pkg/koordlet/metricsadvisor/collectors/nodestorageinfo/node_info_collector.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
  pkg/koordlet/metricsadvisor/metrics_advisor_test.go
  pkg/koordlet/resmanager/blkio_reconcile.go
  pkg/koordlet/resmanager/blkio_reconcile_test.go
  pkg/koordlet/resmanager/cpu_burst.go
  pkg/koordlet/resmanager/cpu_burst_test.go
  pkg/koordlet/resmanager/cpu_suppress.go
  pkg/koordlet/resmanager/cpu_suppress_test.go
  pkg/koordlet/resmanager/resctrl_reconcile.go
  pkg/koordlet/resmanager/resctrl_reconcile_test.go
  pkg/koordlet/statesinformer/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
Labels: size/XXL, lgtm, approved

#1371 koord-scheduler: enhance the preemption when common resources are reserved
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  test/e2e/scheduling/preemption.go
Labels: size/XXL, lgtm, approved

#1390 koord-scheduler: eliminate unnecessary memory overhead and lock conflicts
  apis/extension/node_reservation.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/reservation/cache.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/util/node.go
Labels: lgtm, approved, size/M

#1396 koord-manager: use GenerationChangedPredicate to prevent unnessary repeated reconcile calls
  pkg/slo-controller/nodemetric/nodemetric_controller.go
  pkg/slo-controller/nodeslo/nodeslo_controller.go
Labels: size/XS, lgtm, approved

#1389 koordlet: add a resource usage predictserver to estimate long-term reclaimed resource
  pkg/koordlet/prediction/checkpoint.go
  pkg/koordlet/prediction/checkpoint_test.go
  pkg/koordlet/prediction/predict_server.go
  pkg/koordlet/prediction/predict_server_test.go
  pkg/koordlet/prediction/prediction.go
  pkg/koordlet/prediction/prediction_test.go
  pkg/util/histogram/decaying_histogram.go
  pkg/util/histogram/decaying_histogram_test.go
  pkg/util/histogram/histogram.go
  pkg/util/histogram/histogram_test.go
Labels: size/XXL, lgtm, approved

#1400 koordlet: refactor statesinformer to solve the circular dependency problem
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/statesinformer/api.go
  pkg/koordlet/statesinformer/impl/callback_runner.go
  pkg/koordlet/statesinformer/impl/callback_runner_test.go
  pkg/koordlet/statesinformer/impl/config.go
  pkg/koordlet/statesinformer/impl/config_test.go
  pkg/koordlet/statesinformer/impl/extension_utils.go
  pkg/koordlet/statesinformer/impl/kubelet_stub.go
  pkg/koordlet/statesinformer/impl/kubelet_stub_test.go
  pkg/koordlet/statesinformer/impl/registry.go
  pkg/koordlet/statesinformer/impl/states_device_linux.go
  pkg/koordlet/statesinformer/impl/states_device_linux_test.go
  pkg/koordlet/statesinformer/impl/states_device_unsupported.go
  pkg/koordlet/statesinformer/impl/states_informer.go
  pkg/koordlet/statesinformer/impl/states_informer_test.go
  pkg/koordlet/statesinformer/impl/states_node.go
  pkg/koordlet/statesinformer/impl/states_node_test.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
  pkg/koordlet/statesinformer/impl/states_nodeslo.go
  pkg/koordlet/statesinformer/impl/states_nodeslo_test.go
  pkg/koordlet/statesinformer/impl/states_pods.go
  pkg/koordlet/statesinformer/impl/states_pods_test.go
  pkg/koordlet/statesinformer/impl/states_pvc.go
  pkg/koordlet/statesinformer/mockstatesinformer/mock.go
Labels: lgtm, approved, size/L

#1375 apis: add Mid tier api
  apis/extension/resource.go
  apis/extension/slo_controller_config.go
  apis/extension/zz_generated.deepcopy.go
  apis/slo/v1alpha1/nodemetric_types.go
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Labels: lgtm, approved, size/M

#1402 koordlet: fix can not collect psi metrics
  pkg/koordlet/koordlet.go
  pkg/koordlet/util/system/cgroup_driver.go
  pkg/koordlet/util/system/cgroup_driver_linux.go
  pkg/koordlet/util/system/cgroup_driver_linux_test.go
  pkg/koordlet/util/system/cgroup_driver_unsupported.go
Labels: lgtm, approved, size/L

#1407 koordlet: report the amount of reclaimable resources of the node
  pkg/koordlet/config/config.go
  pkg/koordlet/koordlet.go
  pkg/koordlet/prediction/config.go
  pkg/koordlet/prediction/config_test.go
  pkg/koordlet/prediction/peak_predictor.go
  pkg/koordlet/prediction/peak_predictor_test.go
  pkg/koordlet/prediction/predict_server.go
  pkg/koordlet/prediction/predict_server_test.go
  pkg/koordlet/prediction/prediction_test.go
  pkg/koordlet/statesinformer/impl/states_informer.go
  pkg/koordlet/statesinformer/impl/states_informer_test.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
Labels: lgtm, approved, size/XL

#1401 koord-manager: add noderesource plugin for Mid
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins_profile.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: size/XXL, lgtm, approved

#1411 koordlet: add various configurations to the prediction package
  pkg/koordlet/koordlet.go
  pkg/koordlet/prediction/config.go
  pkg/koordlet/prediction/config_test.go
  pkg/koordlet/prediction/peak_predictor.go
  pkg/koordlet/prediction/peak_predictor_test.go
  pkg/koordlet/prediction/predict_server.go
  pkg/koordlet/prediction/predict_server_test.go
  pkg/koordlet/prediction/prediction.go
Labels: lgtm, approved, size/L

#1410 koord-scheduler: clean up the adaptation code in NodeNUMAResource
  apis/extension/priority.go
  apis/extension/resource.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
Labels: lgtm, approved, size/L

#1413 koord-scheduler: refactor the implementation of Validate/Convert of request in DeviceShare
  apis/extension/scheduling.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/deviceshare/utils_test.go
Labels: lgtm, approved, size/XL

#1393 util: remove eviction-related duplicate implementations
  pkg/descheduler/controllers/migration/evictor/evictor_native.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/utils/utils.go
  pkg/descheduler/framework/plugins/kubernetes/defaultevictor/evictor.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/koordlet/resmanager/resmanager_test.go
  pkg/util/pod_evict.go
Labels: lgtm, approved, size/L

#1408 koord-manager: enhance noderesource framework for updating node labels
  pkg/slo-controller/noderesource/framework/extender_plugin.go
  pkg/slo-controller/noderesource/framework/extender_plugin_test.go
  pkg/slo-controller/noderesource/framework/noderesource.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/plugins_profile.go
  pkg/slo-controller/noderesource/resource_calculator.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: lgtm, approved, size/L

#1416 koordlet: fix prediction setup
  pkg/koordlet/koordlet.go
  pkg/koordlet/metriccache/util.go
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
  pkg/koordlet/prediction/predict_server.go
  pkg/koordlet/resmanager/system_config.go
  pkg/koordlet/resmanager/system_config_test.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
Labels: lgtm, approved, size/M

#1366 proposal: NRI Mode Resource Management
  docs/images/RuntimeProxy.png
  docs/images/nri-proposal.png
  docs/images/nri.png
  docs/images/proxy.png
  docs/images/standalone.png
  docs/proposals/20230608-nri-mode-resource-management.md
Labels: lgtm, approved, size/L

#1414 koord-scheduler: remove CompatibleDefaultPreemption plugin
  cmd/koord-scheduler/main.go
  pkg/features/scheduler_features.go
  pkg/scheduler/frameworkext/informers.go
  pkg/scheduler/frameworkext/informers_test.go
  pkg/scheduler/plugins/compatibledefaultpreemption/preemption.go
  pkg/scheduler/plugins/compatibledefaultpreemption/preemption_test.go
Labels: lgtm, approved, size/L

#1417 koord-scheduler: use informer transformer to be compatible or modify objects
  apis/extension/deprecated.go
  cmd/koord-descheduler/app/server.go
  cmd/koord-scheduler/app/server.go
  cmd/koord-scheduler/main.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer_test.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_transformer.go
  pkg/scheduler/frameworkext/sharedlisterext/nodeinfo_transformer_test.go
  pkg/scheduler/plugins/batchresource/batch_resource.go
  pkg/scheduler/plugins/batchresource/batch_resource_test.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_handler_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/pod_handler.go
  pkg/scheduler/plugins/deviceshare/pod_handler_test.go
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/slo-controller/noderesource/device_resource_calculator.go
  pkg/util/transformer/device_transformer.go
  pkg/util/transformer/device_transformer_test.go
  pkg/util/transformer/node_transformer.go
  pkg/util/transformer/node_transformer_test.go
  pkg/util/transformer/pod_transformer.go
  pkg/util/transformer/pod_transformer_test.go
  pkg/util/transformer/transformers.go
Labels: size/XXL, lgtm, approved

#1418 koord-controller-manager: noderesource supports configuration plugins
  cmd/koord-manager/options/controllers.go
  cmd/koord-manager/options/options.go
  pkg/slo-controller/noderesource/framework/extender_plugin.go
  pkg/slo-controller/noderesource/framework/extender_plugin_test.go
  pkg/slo-controller/noderesource/noderesource_controller.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin.go
  pkg/slo-controller/noderesource/plugins_profile.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: lgtm, approved, size/L

#1420 koord-scheduler: remove unused tests in DeviceShare
  pkg/scheduler/plugins/deviceshare/device_handler_test.go
  pkg/scheduler/plugins/deviceshare/pod_handler_test.go
Labels: lgtm, approved, size/L

#1404 koordlet: exclude LSE from share cpu pool
  pkg/koordlet/resmanager/cpu_burst.go
Labels: size/XS, lgtm, approved

#1424 koord-scheduler: load-aware supports estimate node allocatable
  pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
  pkg/scheduler/plugins/loadaware/estimator/types.go
  pkg/scheduler/plugins/loadaware/load_aware.go
Labels: lgtm, approved, size/M

#1425 koord-scheduler: load-aware estimates pod that only has requests
  pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
Labels: lgtm, approved, size/M

#1422 koord-scheduler: refresh specific NodeInfos on demand instead of all
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/scheduler_adapter.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/L

#1380 koord-scheduler: coscheduling support multiple gang match policy
  apis/extension/scheduling.go
  docs/proposals/scheduling/20220901-gang-scheduling.md
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/core/gang_summary.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
  pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Labels: lgtm, approved, size/L

#1385 docs: propose node prediction
  docs/images/node-prediction.svg
  docs/proposals/20230613-node-prediction.md
Labels: lgtm, approved, size/L

#1432 chore: remove the tag in internal config as usual
  pkg/descheduler/apis/config/types.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/types.go
Labels: lgtm, approved, size/M

#1433 koord-descheduler: fix GetMaxUnavailable not properly handling percentage type param
  pkg/descheduler/controllers/migration/util/util.go
  pkg/descheduler/controllers/migration/util/util_test.go
Labels: lgtm, approved, size/M

#1419 koord-descheduler: support ignore expected replicas argument
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/filter.go
Labels: lgtm, approved, size/M

#1434 koord-scheduler: improve throughput with reservation via return PreFilterResult
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/M
