Repository koordinator-sh/koordinator, pull requests merged in 2024-01, with the labels that each got.

#1806 scheduler: support DeviceHandler to selectively generate requests and replicas
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/devicehandler_default.go
  pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
Labels: lgtm, approved, size/M

#1808 scheduler: optimize DeviceHandler interface
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/devicehandler_default.go
  pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
Labels: size/XS, lgtm, approved

#1804 scheduler: enhance ReservationNominator to support preemption
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/testing/fake_reservation_nominator.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/deviceshare/scoring.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
  pkg/scheduler/plugins/reservation/scoring.go
  pkg/scheduler/plugins/reservation/scoring_test.go
Labels: lgtm, approved, size/L

#1810 scheduler: fix preemption panic
  pkg/scheduler/plugins/deviceshare/device_resources.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/M

#1722 koordlet: support core sched cookie management
  apis/slo/v1alpha1/pod.go
  go.mod
  go.sum
  pkg/koordlet/metrics/core_sched.go
  pkg/koordlet/metrics/metrics.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/resourceexecutor/cgroup.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/coresched/cookie_cache.go
  pkg/koordlet/runtimehooks/hooks/coresched/cookie_cache_test.go
  pkg/koordlet/runtimehooks/hooks/coresched/core_sched.go
  pkg/koordlet/runtimehooks/hooks/coresched/core_sched_test.go
  pkg/koordlet/runtimehooks/hooks/coresched/helper.go
  pkg/koordlet/runtimehooks/hooks/coresched/helper_test.go
  pkg/koordlet/runtimehooks/hooks/coresched/rule.go
  pkg/koordlet/runtimehooks/hooks/coresched/rule_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/kubeqos_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/statesinformer/api.go
  pkg/koordlet/statesinformer/impl/callback_runner.go
  pkg/koordlet/statesinformer/impl/states_informer.go
  pkg/koordlet/statesinformer/impl/states_pods.go
  pkg/koordlet/util/cold_page_test.go
  pkg/koordlet/util/container.go
  pkg/koordlet/util/system/cgroup.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/common.go
  pkg/koordlet/util/system/common_test.go
  pkg/koordlet/util/system/core_sched.go
  pkg/koordlet/util/system/core_sched_linux.go
  pkg/koordlet/util/system/core_sched_linux_test.go
  pkg/koordlet/util/system/core_sched_test.go
  pkg/koordlet/util/system/core_sched_unsupported.go
  pkg/koordlet/util/system/proc.go
  pkg/koordlet/util/system/proc_test.go
  pkg/koordlet/util/system/system_file.go
  pkg/koordlet/util/system/system_file_test.go
  pkg/koordlet/util/system/system_resource.go
  pkg/koordlet/util/system/util_test_tool.go
  pkg/util/metrics/expire_metric.go
  pkg/util/metrics/expire_metric_test.go
  pkg/util/sloconfig/nodeslo_config.go
Labels: size/XXL, lgtm, approved

#1814 scheduler: change reservation default allocate policy to aligned
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/deviceshare/reservation_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/scoring_test.go
Labels: lgtm, approved, size/L

#1815 scheduler: remove useless code from Reservation plugin
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/M

#1813 chores: replace shimo doc to dingtalk
  README.md
Labels: size/XS, lgtm, approved

#1817 scheduler: add monitor to detect scheduling deadlock
  cmd/koord-scheduler/app/server.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/scheduler_monitor.go
  pkg/scheduler/frameworkext/scheduler_monitor_test.go
  pkg/scheduler/metrics/metrics.go
Labels: lgtm, approved, size/L

#1818 koordlet: fix be cpuset for numaResource
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
Labels: lgtm, approved, size/M

#1823 chore: only require security updates and exclude version updates
  .github/dependabot.yml
Labels: size/XS, lgtm, approved

#1824 chores: update bi-weekly meeting notes link
  README-zh_CN.md
Labels: size/XS, lgtm, approved

#1796 slo-controller: Introduce node resource amplification plugin
  pkg/slo-controller/noderesource/plugins/resourceamplification/plugin.go
  pkg/slo-controller/noderesource/plugins/resourceamplification/plugin_test.go
  pkg/slo-controller/noderesource/plugins_profile.go
Labels: lgtm, approved, size/L

#1826 scheduler: refine log in device share plugin
  pkg/scheduler/plugins/deviceshare/scoring.go
Labels: size/XS, lgtm, approved

#1827 scheduler: fix skip logic in reservation plugin
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: size/XS, lgtm, approved

#1785 webhook: add node webhook for resource amplification
  apis/extension/cpu_normalization.go
  apis/extension/cpu_normalization_test.go
  apis/extension/node_resource_amplification.go
  apis/extension/node_resource_amplification_test.go
  config/webhook/manifests.yaml
  pkg/descheduler/apis/config/validation/validation_loadaware_test.go
  pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
  pkg/features/features.go
  pkg/slo-controller/noderesource/plugins/batchresource/util_test.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
  pkg/util/resource.go
  pkg/util/resource_test.go
  pkg/webhook/add_node.go
  pkg/webhook/node/mutating/mutating_handler.go
  pkg/webhook/node/mutating/mutating_handler_test.go
  pkg/webhook/node/mutating/webhooks.go
  pkg/webhook/node/plugins/resourceamplification/resource_amplification.go
  pkg/webhook/node/plugins/resourceamplification/resource_amplification_test.go
Labels: size/XXL, lgtm, approved

#1789 koordlet: fix RDT cache id issue
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile_test.go
  pkg/koordlet/resourceexecutor/resctrl_updater.go
  pkg/koordlet/util/system/resctrl.go
  pkg/koordlet/util/system/resctrl_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/L

#1779 docs: support NetworkQoS based on external plugin such as terway-qos
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  docs/proposals/koordlet/20231208-support-netqos.md
  pkg/slo-controller/nodeslo/resource_strategy_test.go
  pkg/util/sloconfig/nodeslo_config.go
  pkg/webhook/cm/plugins/sloconfig/system_config_checker_test.go
Labels: lgtm, approved, size/XL

#1828 koordlet: fix memory leak in perfGroup
  pkg/koordlet/util/perf_group/perf_group_linux.go
Labels: size/XS, lgtm, approved

#1830 koordlet: fix typo in function isBECPUUsageHighEnough
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
Labels: size/XS, lgtm, approved

#1838 koordlet: fix by adding lock during podmap update
  pkg/koordlet/statesinformer/impl/states_pods.go
Labels: size/XS, lgtm, approved

#1848 koordlet: fix recursively disabling bvt
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/util/node.go
  pkg/koordlet/util/node_test.go
Labels: lgtm, approved, size/L

#1847 koordlet: fix struct type lost of node slo extension
  apis/configuration/slo_controller_config.go
  pkg/koordlet/statesinformer/impl/states_nodeslo.go
  pkg/koordlet/statesinformer/impl/states_nodeslo_test.go
Labels: lgtm, approved, size/S

#1845 scheduler: fix ElasticQuota creation failure on startup
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
Labels: size/XS, lgtm, approved

#1849 koordlet: eliminate cache GC is not started
  pkg/koordlet/koordlet.go
  pkg/koordlet/resourceexecutor/executor.go
Labels: size/XS, lgtm, approved

#1839 scheduler : supports disable runtime quota
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/defaults.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_helper_test.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/preempt.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
Labels: lgtm, approved, size/L

#1850 scheduler: optimize ElasticQuota status/metrics sync flow
  go.mod
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/controller_test.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_summary.go
  pkg/scheduler/plugins/elasticquota/metrics.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_service.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: lgtm, approved, size/XL

#1852 scheduler: fix ElasaticQuota sync status missing decorate used
  pkg/scheduler/plugins/elasticquota/controller.go
Labels: size/XS, lgtm, approved

#1853 scheduler: fix missing tree id in GetQuotaSummary()
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
Labels: size/XS, lgtm, approved

#1855 scheduler: ElasticQuota runtime is no longer calculated when not needed
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_service_test.go
Labels: lgtm, approved, size/M

#1858 descheduler: fix bug of nodeAnomalyDetector in LowNodeLoad plugin
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
Labels: size/XS, lgtm, approved

#1857 scheduler: improve plugin args
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta2/types.go
  pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/plugin_controller.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
  pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Labels: lgtm, approved, size/L

#1861 scheduler: improve Coscheduling PreFilter status
  pkg/scheduler/plugins/coscheduling/coscheduling.go
Labels: size/XS, lgtm, approved

#1865 Add a new adopter
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#1807 metrics: seperater metrics as internal and external for slo-controller and koordlet
  cmd/koord-manager/main.go
  cmd/koordlet/main.go
  pkg/koordlet/metrics/external_metrics.go
  pkg/koordlet/metrics/internal_metrics.go
  pkg/koordlet/metrics/metrics.go
  pkg/slo-controller/metrics/common.go
  pkg/slo-controller/metrics/metrics.go
  pkg/slo-controller/metrics/metrics_test.go
  pkg/slo-controller/metrics/node_resource.go
  pkg/util/metrics/merged_gather.go
  pkg/util/metrics/merged_gather_test.go
Labels: lgtm, approved, size/L

#1868 koordlet: fix metric record err
  pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
Labels: size/XS, lgtm, approved

#1870 scheduler: fix the method of calculating desiredCount in DeviceShare ApplyForAll strategy
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/devicehandler_default.go
  pkg/scheduler/plugins/deviceshare/devicehandler_default_test.go
  pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
Labels: lgtm, approved, size/L

#1841 webhook: validate network qos config in webhook
  pkg/webhook/cm/plugins/sloconfig/resource_qos_checker.go
  pkg/webhook/cm/plugins/sloconfig/resource_qos_checker_test.go
Labels: lgtm, approved, size/L

#1798 proposal: Resctrl Qos Enhancement Proposal
  docs/images/resctrl.png
  docs/proposals/koordlet/20231227-koordlet-resctrl-qos-enhance.md
Labels: lgtm, approved, size/XL

#1876 koordlet: decouple CUDA dependency Accelerators feature disabled
  pkg/koordlet/metricsadvisor/metrics_advisor.go
  pkg/koordlet/util/cpuinfo.go
Labels: lgtm, approved, size/S

#1885 koordlet: fix proxy container service and revise cpu.max updater
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/resourceexecutor/updater_test.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/proxyserver/service.go
  pkg/koordlet/runtimehooks/proxyserver/service_test.go
Labels: lgtm, approved, size/L
