Repository koordinator-sh/koordinator, pull requests merged in 2024-05, with the labels that each got.

#2027 chore: fix some nit error
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/features/features.go
Labels: size/XS, lgtm, approved

#2029 scheduler: coscheduling plugin only record gang OnceResourceSatisfied…
  pkg/scheduler/plugins/coscheduling/core/gang.go
Labels: size/XS, lgtm, approved

#1972 koordlet: add NRI reconnect
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/config_test.go
  pkg/koordlet/runtimehooks/nri/server.go
  pkg/koordlet/runtimehooks/nri/server_test.go
  pkg/koordlet/runtimehooks/runtimehooks.go
Labels: lgtm, approved, size/L

#1939 scheduler: support numa topology policy on pod
  apis/extension/numa_aware.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/topologymanager/manager.go
  pkg/scheduler/frameworkext/topologymanager/policy.go
  pkg/scheduler/frameworkext/topologymanager/policy_best_effort.go
  pkg/scheduler/frameworkext/topologymanager/policy_none.go
  pkg/scheduler/frameworkext/topologymanager/policy_none_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_restricted.go
  pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node.go
  pkg/scheduler/frameworkext/topologymanager/policy_test.go
  pkg/scheduler/plugins/deviceshare/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/node_allocation.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/util.go
  pkg/scheduler/plugins/nodenumaresource/util_test.go
  test/e2e/scheduling/nodenumaresource.go
Labels: lgtm, approved, size/XL

#2032 scheduler: coscheduling plugin sync scheduled in controller
  pkg/scheduler/plugins/coscheduling/controller/podgroup.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_test.go
Labels: lgtm, approved, size/L

#2046 koordlet: add nri remove
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/nri/server.go
  pkg/koordlet/runtimehooks/nri/server_test.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context_test.go
  pkg/runtimeproxy/config/config.go
Labels: lgtm, approved, size/L

#2053 ci: fix scheduler e2e workflow after 1.28 upgradation
  .github/workflows/e2e-k8s-1.22.yaml
  .github/workflows/e2e-k8s-1.24.yaml
  .github/workflows/e2e-k8s-1.28.yaml
  .github/workflows/e2e-k8s-latest.yaml
  config/manager/scheduler-config.yaml
  config/manager/scheduler.yaml
Labels: lgtm, approved, size/M

#2054 koordlet: change CollectContainerThrottledMetric with duration=2*collectoInterval
  pkg/koordlet/qosmanager/helpers/metrics_query.go
Labels: size/XS, lgtm, approved

#2055 koordlet: skip the container which is not running in cpuBurst applyCFSQuotaBurst
  pkg/koordlet/qosmanager/plugins/cpuburst/cpu_burst.go
  pkg/koordlet/qosmanager/plugins/cpuburst/cpu_burst_test.go
Labels: size/XS, lgtm, approved

#2056 koordlet: fix BlkioReconcile file close
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go
Labels: size/XS, lgtm, approved

#2060 koordlet: revise flaky test in pleg
  pkg/koordlet/pleg/pleg_test.go
Labels: lgtm, approved, size/M

#2059 scheduler: support empty reservation affinity
  apis/extension/reservation.go
  pkg/util/reservation/reservation.go
Labels: size/XS, lgtm, approved

#2061 koordlet: fix flaky test in pleg
  pkg/koordlet/pleg/pleg_test.go
Labels: lgtm, approved, size/M

#2063 scheduler: add reservation level event
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/deviceshare/reservation_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: lgtm, approved, size/XL

#2064 scheduler: make gang quickCheck earlier
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved, size/S

#2044 scheduler: make device topology alignment switchable
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/topology_hint.go
Labels: lgtm, approved, size/M

#2065 scheduler: remove unused imports
  go.mod
Labels: size/XS, lgtm, approved

#2067 koordlet: fix nri reconnect params
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/config_test.go
  pkg/koordlet/runtimehooks/nri/server.go
  pkg/koordlet/runtimehooks/nri/server_test.go
  pkg/koordlet/runtimehooks/runtimehooks.go
Labels: lgtm, approved, size/L

#2069 scheduler: fix fairness ut
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: size/XS, lgtm, approved

#2070 manager: only sync label when label key exists
  pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin.go
  pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin_test.go
Labels: lgtm, approved, size/L

#2072 fix some reservationAffinity related error
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/deviceshare/topology_hint.go
  pkg/scheduler/plugins/reservation/plugin.go
Labels: lgtm, approved, size/S

#2071 koordlet: reduce unnecessary call of Err() for better performance
  pkg/koordlet/metriccache/metric_result.go
Labels: size/XS, lgtm, approved
