Repository koordinator-sh/koordinator, pull requests merged in 2024-02, with the labels that each got.

#1872 webhook: improve node affinity performance for MultiQuotaTree
  pkg/webhook/elasticquota/plugin_check_quota_meta_validate.go
  pkg/webhook/elasticquota/plugin_check_quota_meta_validate_test.go
  pkg/webhook/elasticquota/quota_handler.go
  pkg/webhook/elasticquota/quota_handler_test.go
  pkg/webhook/elasticquota/quota_topology.go
  pkg/webhook/pod/mutating/multi_quota_tree_affinity.go
  pkg/webhook/pod/mutating/multi_quota_tree_affinity_test.go
  pkg/webhook/pod/mutating/mutating_handler_test.go
Labels: lgtm, approved, size/XL

#1891 scheduler: correct NodeNUMAResource handling with NodeFullPCPUsOnly and preferredCPUBindPolicy
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Labels: lgtm, approved, size/M

#1893 koordlet: fix misleading query helper
  pkg/koordlet/qosmanager/helpers/metrics_query.go
  pkg/koordlet/qosmanager/plugins/cpuburst/cpu_burst.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
Labels: lgtm, approved, size/S

#1878 webhook: more checks for netqos
  pkg/webhook/cm/plugins/sloconfig/resource_qos_checker.go
  pkg/webhook/cm/plugins/sloconfig/resource_qos_checker_test.go
Labels: lgtm, approved, size/L

#1907 koorldet: remove logging field from the kubelet configz
  pkg/koordlet/statesinformer/impl/kubelet_stub.go
  pkg/koordlet/statesinformer/impl/kubelet_stub_test.go
Labels: lgtm, approved, size/L

#1879 proposal: support Job-level preemption
  docs/proposals/scheduling/20240115-support-job-level-preemption.md
Labels: lgtm, approved, size/L

#1887 proposal: support Reservation preemption
  docs/proposals/scheduling/20240201-enbale-reservation-preempt.md
Labels: lgtm, approved, size/L

#1916 webhook: fix webhook for root quota creation
  pkg/webhook/elasticquota/mutating/mutating_handle_test.go
  pkg/webhook/elasticquota/quota_topology.go
Labels: lgtm, approved, size/S

#1917 scheduler: fix initializing built-in quota objects
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
Labels: lgtm, approved, size/M

#1902 Proposal: add proposal for multi tree quota
  docs/images/multi-quota-tree.jpg
  docs/proposals/scheduling/20240206-multi-tree-quota.md
Labels: lgtm, approved, size/L

#1911 webhook: forbid use internal protocols
  pkg/webhook/pod/validating/validating_handler.go
  pkg/webhook/pod/validating/verify_annotations.go
  pkg/webhook/pod/validating/verify_annotations_test.go
Labels: lgtm, approved, size/L

#1921 webhook: remove some annotation verify
  pkg/webhook/pod/validating/verify_annotations.go
  pkg/webhook/pod/validating/verify_annotations_test.go
Labels: lgtm, approved, size/S

#1894 scheduler: add Reservation restricted options to control allocatable resources
  apis/extension/reservation.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
Labels: lgtm, approved, size/L

#1913 koordlet: add metrics for kubelet and resource executor
  pkg/koordlet/metrics/internal_metrics.go
  pkg/koordlet/metrics/kubelet.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metrics/psi.go
  pkg/koordlet/metrics/psi_test.go
  pkg/koordlet/metrics/resource_executor.go
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
  pkg/koordlet/resourceexecutor/executor.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/resctrl_updater.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/statesinformer/impl/kubelet_stub.go
  pkg/koordlet/util/system/psi.go
  pkg/koordlet/util/system/psi_test.go
Labels: lgtm, approved, size/L

#1859 scheduler: remove the restriction that reservation cannot be preempted
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
Labels: lgtm, approved, size/L

#1926 scheduler: fix reservation restricted options
  pkg/scheduler/plugins/reservation/plugin.go
Labels: size/XS, lgtm, approved

#1925 scheduler: add unschedulable resource for root quota
  apis/extension/elastic_quota.go
  pkg/quota-controller/profile/profile_controller.go
  pkg/quota-controller/profile/profile_controller_test.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/controller_test.go
Labels: lgtm, approved, size/L

#1892 scheduler: improve NodeNUMAResource handling node cpu bind policy
  pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/scoring_test.go
  pkg/scheduler/plugins/nodenumaresource/service.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/util.go
  pkg/scheduler/plugins/nodenumaresource/util_test.go
Labels: lgtm, approved, size/XL
