Repository koordinator-sh/koordinator, pull requests merged in 2024-09, with the labels that each got.

#2156 koord-descheduler: update k8s descheduler to 0.28.0
  go.mod
  go.sum
  pkg/descheduler/framework/plugins/kubernetes/adaptor/evictor.go
  pkg/descheduler/framework/plugins/kubernetes/adaptor/framework.go
  pkg/descheduler/framework/plugins/kubernetes/defaultevictor/evictor.go
  pkg/descheduler/framework/plugins/kubernetes/plugin.go
  pkg/descheduler/framework/plugins/kubernetes/plugin_test.go
Labels: lgtm, approved, size/S

#2163 scheduler: support reservation ignored and nodenumaresource preemption
  apis/extension/reservation.go
  apis/extension/reservation_test.go
  apis/scheduling/v1alpha1/reservation_types.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/deviceshare/reservation_test.go
  pkg/scheduler/plugins/deviceshare/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/node_allocation.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/preempt.go
  pkg/scheduler/plugins/nodenumaresource/preempt_test.go
  pkg/scheduler/plugins/nodenumaresource/reservation.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/scoring.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_benchmark_test.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: size/XXL, lgtm, approved

#2172 koord-manager: support resource amplification config, cpu, memory and other resource
  apis/configuration/slo_controller_config.go
  apis/configuration/zz_generated.deepcopy.go
  pkg/slo-controller/noderesource/plugins/resourceamplification/configmap_event_handler.go
  pkg/slo-controller/noderesource/plugins/resourceamplification/configmap_event_handler_test.go
  pkg/slo-controller/noderesource/plugins/resourceamplification/plugin.go
  pkg/slo-controller/noderesource/plugins/resourceamplification/plugin_test.go
  pkg/slo-controller/noderesource/plugins_profile.go
Labels: lgtm, approved, size/XL

#2177 scheduler: fix pod update when pod creation is before quota creation
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
Labels: lgtm, approved, size/M

#2182 scheduler: permit other plugin to set numaAffinity
  pkg/scheduler/frameworkext/topologymanager/manager.go
  pkg/scheduler/frameworkext/topologymanager/store.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/scoring.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
Labels: lgtm, approved, size/M

#2142 koord-descheduler: LowNodeLoad check if evicted pod can cause new node over utilized
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
Labels: lgtm, approved, size/L

#2145 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS

#2160 koord-descheduler: fixes namespace object limiter
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/util/util.go
Labels: lgtm, approved, size/L

#2174 scheduler: suppport amd.com/gpu
  apis/extension/device_share.go
Labels: lgtm, approved

#2180 scheduler: elastic quota ignore terminating pod immediately
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
Labels: lgtm, approved, size/M, ok-to-test

#2186 apis: add reservation name, taints and tolerations in ReservationAffinitty
  apis/extension/reservation.go
  apis/scheduling/v1alpha1/reservation_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
Labels: lgtm, approved, size/M

#2189 scheduler: fix panic when nonimatingInfo nil
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/framework_extender.go
Labels: lgtm, approved, size/M

#2192 apis: add protobuf for reservation
  apis/scheduling/v1alpha1/reservation_types.go
Labels: lgtm, approved, size/M

#2190 scheduler: fix ElasticQuota state's Clone
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: lgtm, approved, size/M

#2193 koordlet: fix wrong msg in calculateBESuppressCPU
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
Labels: size/XS, lgtm, approved

#1965 chores(deps): Add support depguard rules in golangci-lint
  .golangci.yml
  test/e2e/e2e.go
  test/e2e/framework/framework.go
  test/e2e/framework/manifest/manifest.go
  test/e2e/framework/metrics/kubelet_metrics.go
  test/e2e/framework/pod/dial.go
  test/e2e/framework/ssh/ssh.go
  test/e2e/framework/test_context.go
  test/e2e/framework/testfiles/testfiles.go
  test/e2e/generated/bindata.go
  test/e2e/reporters/progress.go
  test/e2e/suites.go
Labels: lgtm, approved, size/M

#2196 koord-descheduler: fix migration controller max unavailable computing algorigthm
  pkg/descheduler/controllers/migration/util/util.go
  pkg/descheduler/controllers/migration/util/util_test.go
Labels: size/XS, lgtm, approved

#2199 scheduler: support devices of the same node gpuMem not equal
  pkg/scheduler/plugins/deviceshare/device_allocator_test.go
  pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
  pkg/scheduler/plugins/deviceshare/devicehandler_gpu_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/reservation_test.go
  pkg/scheduler/plugins/deviceshare/topology_hint_test.go
Labels: lgtm, approved

#2204 scheduler: support pod preemption from numa awareless reservation
  pkg/scheduler/plugins/nodenumaresource/preempt.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
Labels: lgtm, approved

#2209 scheduler: optimize numa affinity store
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/schedulingphase/scheduling_phase.go
  pkg/scheduler/frameworkext/topologymanager/manager.go
  pkg/scheduler/frameworkext/topologymanager/store.go
Labels: lgtm, approved

#2212 apis: fix type of MinResources in podgroup
  apis/thirdparty/scheduler-plugins/pkg/apis/scheduling/v1alpha1/types.go
  apis/thirdparty/scheduler-plugins/pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved

#2123 koordlet: Add resctrl runtime hook for pod level
  pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/hooks/resctrl/resctrl.go
  pkg/koordlet/runtimehooks/hooks/resctrl/resctrl_test.go
  pkg/koordlet/runtimehooks/hooks/resctrl/rule.go
  pkg/koordlet/runtimehooks/hooks/resctrl/updater.go
  pkg/koordlet/runtimehooks/hooks/resctrl/updater_test.go
  pkg/koordlet/runtimehooks/nri/server.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/proxyserver/server.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/util/resctrl/ctrl_mgr.go
  pkg/koordlet/util/resctrl/ctrl_mgr_test.go
  pkg/koordlet/util/resctrl/resctrl.go
  pkg/koordlet/util/resctrl/resctrl_test.go
  pkg/koordlet/util/system/resctrl.go
Labels: size/XXL, lgtm, approved

#2201 koord-manager: nodeslo-controller enqueue request when node labels updated
  pkg/slo-controller/nodemetric/node_event_handler.go
  pkg/slo-controller/nodemetric/node_event_handler_test.go
Labels: lgtm, approved

#2211 scheduler: optimize performance on transformer extension and Skip status
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/scoring.go
  pkg/scheduler/plugins/reservation/scoring_test.go
Labels: lgtm, approved

#2152 koord-manager: add unallocated resource into mid resource.
  apis/configuration/slo_controller_config.go
  apis/configuration/zz_generated.deepcopy.go
  pkg/slo-controller/config/colocation_cm_event_handler_test.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin.go
  pkg/slo-controller/noderesource/plugins/midresource/plugin_test.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
  pkg/util/sloconfig/colocation_config.go
  pkg/util/sloconfig/colocation_config_extender_test.go
  pkg/util/sloconfig/colocation_config_test.go
Labels: lgtm, approved, size/L

#2207 scheduler: support reservation name, taints and tolerations
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/util/reservation/reservation.go
Labels: lgtm, approved

#2217 scheduler: recover gang check in preFilter
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
Labels: lgtm, approved
