Repository koordinator-sh/koordinator, pull requests merged in 2024-06, with the labels that each got.

#2052 koordlet: add resctrl updater
  pkg/koordlet/resourceexecutor/config.go
  pkg/koordlet/resourceexecutor/resctrl_updater.go
  pkg/koordlet/resourceexecutor/resctrl_updater_test.go
  pkg/koordlet/util/system/resctrl.go
Labels: lgtm, approved, size/L

#1759 koordlet: kill container after calling eviction api success
  pkg/koordlet/qosmanager/framework/config.go
  pkg/koordlet/qosmanager/framework/config_test.go
  pkg/koordlet/qosmanager/framework/context.go
  pkg/koordlet/qosmanager/framework/context_test.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict_test.go
  pkg/koordlet/qosmanager/plugins/memoryevict/memory_evict.go
  pkg/koordlet/qosmanager/plugins/memoryevict/memory_evict_test.go
Labels: lgtm, approved, size/L, area/koordlet

#2073 koord-scheduler: fix gpu name to nvidia/gpu in reservation level event
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
Labels: lgtm, approved, size/S

#2076 koord-scheduler: add a parameter to mark whether scheduling is allowed on node with expired nodemetric
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1beta3/defaults.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/L

#2085 scheduler: refine reservation msg if matched filtered out by other plugins
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
Labels: lgtm, approved, size/L

#2087 Add ZiMengSheng into approvers alias
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#2084 scheduler: fix reservation plugin clone concurrent read write
  pkg/scheduler/plugins/reservation/plugin.go
Labels: lgtm, approved, size/M

#2083 scheduler: fix elastic quota TestPlugin_OnPodDelete random panic
  pkg/scheduler/plugins/elasticquota/pod_handler_test.go
Labels: lgtm, approved, size/S

#2090 scheduler: change reservation event message format
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
Labels: lgtm, approved, size/L

#2094 scheduler: add node info in reservation level event
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
Labels: lgtm, approved, size/S

#2080 scheduler: support consume reserved numa resource
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/nodenumaresource/node_allocation.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/reservation.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
Labels: lgtm, approved, size/XL

#1992 scheduler: add new pod estimate with loadaware plugin
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/XL

#2091 koord-descheduler: limit the total number of pod evictions
  cmd/koord-descheduler/app/server.go
  pkg/descheduler/apis/config/types.go
  pkg/descheduler/apis/config/v1alpha2/types.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/evictions/eviction_limiter.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
Labels: lgtm, approved, size/L

#2101 chore: fix e2e configs after the load-aware scheduling updated
  test/e2e/slocontroller/batchresource.go
  test/e2e/testing-manifests/slocontroller/be-demo.yaml
Labels: lgtm, approved, size/S

#2103 chore: fix low node load test after prod thresholds added
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
Labels: size/XS, lgtm, approved

#2100 koord-scheduler: Pod updates should not update the timestamp
  pkg/scheduler/plugins/loadaware/pod_assign_cache.go
  pkg/scheduler/plugins/loadaware/pod_assign_cache_test.go
Labels: lgtm, approved, size/M

#2088 koord-descheduler: fix object limiter by move it to reconciler
  pkg/descheduler/controllers/migration/arbitrator/arbitrator.go
  pkg/descheduler/controllers/migration/arbitrator/filter.go
  pkg/descheduler/controllers/migration/arbitrator/filter_test.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
  pkg/descheduler/controllers/migration/evict.go
Labels: lgtm, approved, size/XL

#2092 koord-descheduler: enhance LowNodeLoad scorer
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
  pkg/descheduler/utils/sorter/pod.go
  pkg/descheduler/utils/sorter/pod_test.go
  pkg/descheduler/utils/sorter/scorer.go
  pkg/descheduler/utils/sorter/scorer_test.go
Labels: lgtm, approved, size/L

#2079 koordlet: update resctrl qos proposal
  docs/proposals/koordlet/20231227-koordlet-resctrl-qos-enhance.md
Labels: lgtm, approved, size/S

#2057 koordlet: add taskids in statesinformer
  pkg/koordlet/statesinformer/api.go
  pkg/koordlet/statesinformer/impl/config.go
  pkg/koordlet/statesinformer/impl/config_test.go
  pkg/koordlet/statesinformer/impl/states_pods.go
  pkg/koordlet/statesinformer/impl/states_pods_test.go
Labels: lgtm, approved, size/L

#2107 koord-manager: fix the prom metrics handler
  cmd/koord-manager/main.go
Labels: lgtm, approved, size/S

#2114 koord-descheduler: fix descheduler log
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
Labels: size/XS, lgtm, approved
