Repository koordinator-sh/koordinator, pull requests merged in 2024-07, with the labels that each got.

#2121 scheduler: support pod request exact match reservation
  apis/extension/reservation.go
  apis/extension/reservation_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/L

#2120 scheduler: reduce cycleState overhead for reservation
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: size/XXL, lgtm, approved

#2124 scheduler: fix reserveNUMAResource bug
  pkg/scheduler/plugins/nodenumaresource/reservation.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint.go
  pkg/scheduler/plugins/nodenumaresource/util.go
Labels: lgtm, approved, size/M

#2112 koordlet: add allpods reconciler func
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
Labels: lgtm, approved, size/L

#2126 scheduler: reduce deviceShare memory overhead
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/reservation.go
Labels: lgtm, approved, size/S

#2129 webhook: add quota evaluate webhook
  apis/extension/elastic_quota.go
  pkg/features/features.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/webhook/elasticquota/quota_topology_test.go
  pkg/webhook/elasticquota/util.go
  pkg/webhook/pod/validating/evaluate_quota.go
  pkg/webhook/pod/validating/evaluate_quota_test.go
  pkg/webhook/pod/validating/validating_handler.go
  pkg/webhook/pod/validating/webhooks.go
  pkg/webhook/quotaevaluate/evaluator.go
  pkg/webhook/quotaevaluate/evaluator_test.go
  pkg/webhook/quotaevaluate/quota_accessor.go
  pkg/webhook/quotaevaluate/util.go
Labels: size/XXL, lgtm, approved

#2132 koordlet: upgrade nri to 0.6.1
  go.mod
  go.sum
  pkg/koordlet/runtimehooks/nri/server.go
  pkg/koordlet/runtimehooks/nri/server_test.go
Labels: lgtm, approved, size/M

#2128 koord-manager: support manually configured default cpu normalization settings
  apis/configuration/slo_controller_config.go
  apis/configuration/zz_generated.deepcopy.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/plugin_test.go
Labels: lgtm, approved, size/L

#1920 koordlet: tc plugin for netqos
  docker/koordlet.dockerfile
  go.mod
  go.sum
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/tc/helper.go
  pkg/koordlet/runtimehooks/hooks/tc/helper_test.go
  pkg/koordlet/runtimehooks/hooks/tc/ipset.go
  pkg/koordlet/runtimehooks/hooks/tc/iptables.go
  pkg/koordlet/runtimehooks/hooks/tc/netqos_tc.go
  pkg/koordlet/runtimehooks/hooks/tc/rule.go
  pkg/koordlet/runtimehooks/hooks/tc/tc.go
  pkg/koordlet/runtimehooks/hooks/tc/tc_linux.go
  pkg/koordlet/runtimehooks/hooks/tc/tc_linux_test.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/common_linux.go
  pkg/koordlet/util/system/common_linux_test.go
  pkg/koordlet/util/system/util_test_tool.go
  pkg/koordlet/util/system/validator.go
  pkg/koordlet/util/system/validator_test.go
Labels: size/XXL, lgtm, approved

#2134 chore: fix koordlet dockerfile
  docker/koordlet.dockerfile
Labels: size/XS, lgtm, approved

#2130 koord-descheduler: Fix threshold initialization for prod.
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
Labels: lgtm, approved, size/M

#2133 scheduler: support device topology strategy
  apis/extension/device_share.go
  docs/proposals/scheduling/20230803-device-allocate-hint-apis.md
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/device_allocator_test.go
  pkg/scheduler/plugins/deviceshare/numa_topology.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/L

#2136 scheduler: optimize when only 1 reservation/node
  pkg/scheduler/plugins/reservation/nominator.go
Labels: size/XS, lgtm, approved

#2068 koord-descheduler: add migration object limiter for namespace
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/controllers/migration/arbitrator/filter.go
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/controller_test.go
Labels: lgtm, approved, size/L

#2135 webhook: revise elasticquota mutating when validating disabled
  pkg/webhook/elasticquota/mutating/mutating_handler.go
  pkg/webhook/elasticquota/mutating/webhooks.go
  pkg/webhook/elasticquota/plugin_check_quota_meta_validate.go
  pkg/webhook/elasticquota/validating/validating_handler.go
Labels: lgtm, approved, size/M

#2143 koord-descheduler: support max migrating globally limitation
  pkg/descheduler/apis/config/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/validation/validation_pluginargs.go
  pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/controllers/migration/arbitrator/filter.go
  pkg/descheduler/controllers/migration/arbitrator/filter_test.go
Labels: lgtm, approved, size/L

#2138 scheduler: skip uncessary Filter&Score plugin
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/scoring.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/scoring.go
Labels: lgtm, approved, size/M

#2137 all: support priority and preemption policy transformer
  apis/extension/preemption.go
  apis/extension/preemption_test.go
  apis/extension/preemption_utils.go
  apis/extension/priority_utils.go
  apis/extension/priority_utils_test.go
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/util/transformer/pod_transformer.go
  pkg/util/transformer/pod_transformer_test.go
  pkg/util/transformer/transformers.go
Labels: lgtm, approved, size/XL

#2141 scheduler: elastic quota ignore terminating pod
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
Labels: lgtm, approved, size/L

#2144 koord-descheduler: fix maxMigratingGlobally arg json tag
  pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
Labels: size/XS, lgtm, approved

#2146 scheduler: return framework.Unschedulable when cpuPolicy not satisfied
  pkg/scheduler/plugins/nodenumaresource/plugin.go
  pkg/scheduler/plugins/nodenumaresource/plugin_test.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
Labels: lgtm, approved, size/S
