Repository koordinator-sh/koordinator, pull requests merged in 2024-04, with the labels that each got.

#1985 scheduler: fix reservation nominator residual bug
  pkg/scheduler/plugins/reservation/eventhandler.go
  pkg/scheduler/plugins/reservation/eventhandler_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/S

#1973 slo-controller: refactor codes for reading
  docs/images/node-resource-model.png
  pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins/batchresource/util.go
  pkg/slo-controller/noderesource/plugins/batchresource/util_test.go
  pkg/slo-controller/noderesource/resource_calculator_test.go
Labels: lgtm, approved, size/L

#1989 CI workflow with codecov token
  .github/workflows/ci.yaml
Labels: size/XS, lgtm, approved

#1970 chores: fix some fmt err
  pkg/descheduler/controllers/migration/evict.go
  pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled.go
  pkg/koordlet/qosmanager/framework/pod_qos_control.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
  pkg/koordlet/runtimehooks/hooks/coresched/helper.go
  pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/rule/rule.go
  pkg/koordlet/statesinformer/impl/callback_runner.go
  pkg/koordlet/statesinformer/impl/states_pods.go
  pkg/koordlet/util/meminfo.go
  pkg/koordlet/util/system/config.go
  pkg/util/httputil/reverseproxy.go
  pkg/util/metrics/expire_metric.go
  pkg/webhook/api_debug_server.go
  pkg/webhook/pod/mutating/extended_resource_spec.go
Labels: lgtm, approved, size/M

#1986 Revert "scheduler: pick vf by random (#1953)"
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/device_allocator_test.go
Labels: lgtm, approved, size/S

#1976 proposal: tc plugin for netqos
  docs/images/netqos-tc.jpg
  docs/images/tcplugin.png
  docs/proposals/koordlet/20231208-support-netqos.md
Labels: lgtm, approved, size/M

#1996 scheduler: assure Fairness and DeadlockFree
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_summary.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
Labels: lgtm, approved, size/XL

#1997 scheduler: sort gang of same gangGroup by gangId
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved, size/M

#1982 apis & slo-controller: allow specifying node-wise total bandwidth via annotation
  apis/extension/node_qos.go
  apis/extension/node_qos_test.go
  pkg/slo-controller/nodeslo/resource_strategy.go
  pkg/slo-controller/nodeslo/resource_strategy_test.go
Labels: lgtm, approved, size/L

#1994 descheduler: allow annotated pod pass non-retrievable filter
  pkg/descheduler/controllers/migration/arbitrator/filter.go
Labels: size/XS, lgtm, approved

#2001 scheduler: add more quota details used and request in quotaInfo
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/core/quota_summary.go
  pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
Labels: lgtm, approved, size/L

#2007 chores: add security docs
  README-zh_CN.md
  README.md
  SECURITY.md
  embargo-policy.md
Labels: lgtm, approved, size/M

#1995 koordlet: add close for querier
  go.mod
  pkg/koordlet/metriccache/config.go
  pkg/koordlet/metriccache/config_test.go
  pkg/koordlet/metriccache/mockmetriccache/mock_tsdb_storage.go
  pkg/koordlet/metriccache/tsdb_storage.go
  pkg/koordlet/prediction/prediction.go
  pkg/koordlet/qosmanager/helpers/metrics_query.go
  pkg/koordlet/qosmanager/helpers/metrics_query_test.go
  pkg/koordlet/qosmanager/plugins/cpuburst/cpu_burst_test.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
  pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict_test.go
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress_test.go
  pkg/koordlet/qosmanager/plugins/memoryevict/memory_evict_test.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
  pkg/koordlet/util/testutil/mock_utils.go
Labels: lgtm, approved, size/L

#2006 koordlet: add extended HTTP handler registry
  cmd/koordlet/main.go
  cmd/koordlet/options/options.go
Labels: lgtm, approved, size/S

#1988 chore: fix gpu api in comments
  apis/extension/device_share.go
  docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Labels: lgtm, approved, size/S

#2008 scheduler: quota info deepcopy withou pod deepcopy
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
Labels: size/XS, lgtm, approved

#2004 scheduler: refine coscheduling fairness consider gangGroup
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/core/gang_summary.go
  pkg/scheduler/plugins/coscheduling/core/gang_test.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
Labels: size/XXL, lgtm, approved

#2011 scheduler: optimize scheduleCycle logic when notEnoughChildren
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
Labels: lgtm, approved, size/L

#2012 scheduler: fix panic of podGroup and pod delete order issue
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_test.go
Labels: lgtm, approved, size/M

#2013 fix panic of podGroup and pod delete order issue2
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/core/gang_test.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup_test.go
Labels: lgtm, approved, size/L

#2010 scheduler: refine restricted topology policy
  pkg/scheduler/frameworkext/topologymanager/policy.go
  pkg/scheduler/frameworkext/topologymanager/policy_best_effort_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_restricted_test.go
  pkg/scheduler/frameworkext/topologymanager/policy_test.go
Labels: lgtm, approved, size/M

#2015 koordlet: revise node topology reporting for the kubelet cpu manager
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile_test.go
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
  pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/config_test.go
Labels: lgtm, approved, size/L

#1983 koordlet: support cri-o container runtime
  pkg/koordlet/util/pod.go
  pkg/koordlet/util/runtime/handler/crio_runtime.go
  pkg/koordlet/util/runtime/handler/crio_runtime_test.go
  pkg/koordlet/util/runtime/runtime.go
  pkg/koordlet/util/runtime/runtime_test.go
  pkg/koordlet/util/system/cgroup_driver.go
  pkg/koordlet/util/system/cgroup_driver_test.go
  pkg/koordlet/util/system/config.go
Labels: lgtm, approved, size/L

#2017 scheduler: try best to distribute cpu and memory evenly across numa
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
  pkg/scheduler/plugins/nodenumaresource/topology_hint_test.go
Labels: lgtm, approved, size/XL

#2018 scheduler: remove invalid hint in which some numaNode lack resource
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
Labels: lgtm, approved, size/M

#2023 chores: add openssf best practices badge into README
  README-zh_CN.md
  README.md
Labels: size/XS, lgtm, approved

#2025 webhook: optimize webhook patchResponse function
  pkg/webhook/node/mutating/mutating_handler.go
  pkg/webhook/pod/mutating/mutating_handler.go
Labels: lgtm, approved, size/S

#2016 utils: change metrics server util pkg name
  .licenseignore
  pkg/util/metricsserver/metrics_client.go
  pkg/util/metricsserver/metrics_client_test.go
  pkg/util/metricsserver/metrics_client_test_util.go
Labels: size/XS, lgtm, approved

#2000 descheduler: Add detail logs for nonRemovable pods
  pkg/descheduler/controllers/migration/arbitrator/arbitrator.go
  pkg/descheduler/controllers/migration/arbitrator/filter.go
  pkg/descheduler/controllers/migration/util/util.go
  pkg/descheduler/node/node.go
  pkg/descheduler/pod/pods.go
Labels: lgtm, approved, size/M
