Repository koordinator-sh/koordinator, pull requests merged in 2024-08, with the labels that each got.

#2153 koordlet: add some information to improve log readability
  pkg/koordlet/runtimehooks/hooks/hooks.go
Labels: size/XS, lgtm, approved

#2157 ci: add disk GC for E2E jobs
  .github/workflows/e2e-k8s-1.22.yaml
  .github/workflows/e2e-k8s-1.24.yaml
  .github/workflows/e2e-k8s-1.28.yaml
  .github/workflows/e2e-k8s-latest.yaml
Labels: lgtm, approved, size/M

#2151 scheduler: fix panic when NUMANode equals -1
  pkg/scheduler/plugins/deviceshare/numa_topology.go
Labels: lgtm, approved, size/S

#2154 scheduler: fix too many ut log
  go.mod
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved, size/S

#2167 scheduler: support scheduler config v1
  config/manager/scheduler-config.yaml
  hack/update-codegen.sh
  pkg/scheduler/apis/config/scheme/scheme.go
  pkg/scheduler/apis/config/v1/defaults.go
  pkg/scheduler/apis/config/v1/doc.go
  pkg/scheduler/apis/config/v1/register.go
  pkg/scheduler/apis/config/v1/types.go
  pkg/scheduler/apis/config/v1/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1/zz_generated.defaults.go
Labels: size/XXL, lgtm, approved

#2155 scheduler: add coscheduling preEnqueue
  config/manager/scheduler-config.yaml
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved, size/L

#2162 koordlet: add record events
  pkg/koordlet/koordlet.go
  pkg/koordlet/runtimehooks/protocol/container_context.go
  pkg/koordlet/runtimehooks/protocol/host_qos_context.go
  pkg/koordlet/runtimehooks/protocol/kubeqos_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context.go
  pkg/koordlet/runtimehooks/protocol/pod_context_test.go
  pkg/koordlet/runtimehooks/protocol/protocol.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/runtimehooks/runtimehooks.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
Labels: lgtm, approved, size/L

#2173 koordlet: fix unsafe conversion in net_cls
  pkg/koordlet/resourceexecutor/cgroup.go
  pkg/koordlet/resourceexecutor/reader.go
  pkg/koordlet/runtimehooks/hooks/tc/rule.go
Labels: lgtm, approved, size/M

#2178 scheduler: assure only gpu will allocate by topology
  pkg/scheduler/plugins/deviceshare/device_allocator.go
Labels: lgtm, approved, size/S

#2176 schedler: move gang OnceSatified to gangGroupInfo
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/core/gang_summary.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved, size/M

#2139 scheduler: add reservation preemption
  .licenseignore
  apis/extension/preemption.go
  apis/extension/preemption_test.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1/types.go
  pkg/scheduler/apis/config/v1/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1beta3/defaults.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/frameworkext/reservation_info_test.go
  pkg/scheduler/plugins/reservation/cache_test.go
  pkg/scheduler/plugins/reservation/eventhandler_test.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
  pkg/scheduler/plugins/reservation/preemption.go
  pkg/scheduler/plugins/reservation/preemption_test.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: size/XXL, lgtm, approved
