Repository koordinator-sh/koordinator, pull requests merged in 2024-03, with the labels that each got.

#1881 utils: add metric server client
  .licenseignore
  go.mod
  go.sum
  pkg/util/metricserver/metrics_client.go
  pkg/util/metricserver/metrics_client_test.go
  pkg/util/metricserver/metrics_client_test_util.go
Labels: lgtm, approved, size/L

#1930 scheduler: update resourceNames of ReservationInfo
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/frameworkext/reservation_info_test.go
Labels: lgtm, approved, size/M

#1843 koordlet: support NetworkQoS plugin
  apis/extension/constants.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/runtimehooks/config.go
  pkg/koordlet/runtimehooks/hooks/terwayqos/terwayqos.go
  pkg/koordlet/runtimehooks/hooks/terwayqos/terwayqos_test.go
  pkg/koordlet/runtimehooks/hooks/terwayqos/types.go
  pkg/koordlet/runtimehooks/hooks/terwayqos/types_test.go
  pkg/util/sloconfig/nodeslo_config.go
Labels: lgtm, approved, size/XL

#1928 koordlet: revise cgroupRoot param in podsInformer
  pkg/koordlet/statesinformer/impl/states_pods.go
  pkg/koordlet/statesinformer/impl/states_pods_test.go
Labels: lgtm, approved, size/M

#1931 koordlet: support blkio-cost rpct and wpct configuration
  apis/configuration/slo_controller_config.go
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile_test.go
Labels: lgtm, approved, size/L

#1934 scheduler: resolve the wrong use of gangmod in gang init phase
  pkg/scheduler/plugins/coscheduling/core/gang.go
Labels: lgtm, approved, size/S

#1938 Add a new adopter
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#1932 koordlet: fix bug that cpu eviction does not take effect
  pkg/koordlet/util/node.go
  pkg/koordlet/util/node_test.go
Labels: lgtm, approved, size/M

#1936 scheduler: extend reservation nominator to support reservation preemption
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/testing/fake_reservation_nominator.go
  pkg/scheduler/plugins/reservation/nominator.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/L

#1944 koordlet: fix GetAllPods error and wrong tsdb prometheus registry
  pkg/koordlet/metriccache/tsdb_storage.go
  pkg/koordlet/statesinformer/impl/kubelet_stub.go
Labels: lgtm, approved, size/S

#1910 proposal: support pod customizing numa policy
  docs/proposals/scheduling/20240131-pod-level-numa-policy.md
Labels: lgtm, approved, size/L

#1929 manager: add featuregate to remove the restriction of parent quota submit pods
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/webhook/elasticquota/pod_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/S

#1948 scheduler: improve coscheduling's PostFilter if not collect enough
  pkg/scheduler/plugins/coscheduling/core/core.go
Labels: size/XS, lgtm, approved

#1949 scheduler: fix reservation calc error
  pkg/scheduler/plugins/deviceshare/reservation.go
  pkg/scheduler/plugins/reservation/plugin.go
Labels: size/XS, lgtm, approved

#1942 koordlet: support blkio-cost user cost model configuration
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile_test.go
  pkg/koordlet/resourceexecutor/updater.go
  pkg/koordlet/util/system/cgroup_resource.go
  pkg/koordlet/util/system/validator.go
Labels: lgtm, approved, size/L

#1947 scheduler: improve the failed event of Reservation's scheduling
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
Labels: lgtm, approved, size/M

#1953 scheduler: pick vf by random
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/device_allocator_test.go
Labels: lgtm, approved, size/S

#1958 scheduler: give more context to device allocator
  pkg/scheduler/plugins/deviceshare/device_allocator.go
Labels: size/XS, lgtm, approved

#1957 descheduler: change the order of check len(lowNodes) and len(sourceNodes)
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
Labels: lgtm, approved, size/S

#1955 descheduler: add a cache timeout argument for nodeAnomalyDetectors in lowNodeLoad plugin.
  pkg/descheduler/apis/config/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/defaults.go
  pkg/descheduler/apis/config/v1alpha2/defaults_test.go
  pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
  pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
  pkg/descheduler/apis/config/zz_generated.deepcopy.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load.go
  pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
Labels: lgtm, approved, size/M

#1962 descheduler: only include the overused resources when sorting removable pods
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
  pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
Labels: lgtm, approved, size/L

#1937 apis: add Recommendation crd
  OWNERS_ALIASES
  apis/analysis/v1alpha1/condition.go
  apis/analysis/v1alpha1/groupversion_info.go
  apis/analysis/v1alpha1/recommendation_types.go
  apis/analysis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/analysis.koordinator.sh_recommendations.yaml
  config/crd/kustomization.yaml
  config/samples/analysis_v1aplha1_recommendation.yaml
  hack/update-codegen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/analysis/v1alpha1/analysis_client.go
  pkg/client/clientset/versioned/typed/analysis/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/analysis/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/analysis/v1alpha1/fake/fake_analysis_client.go
  pkg/client/clientset/versioned/typed/analysis/v1alpha1/fake/fake_recommendation.go
  pkg/client/clientset/versioned/typed/analysis/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/analysis/v1alpha1/recommendation.go
  pkg/client/informers/externalversions/analysis/interface.go
  pkg/client/informers/externalversions/analysis/v1alpha1/interface.go
  pkg/client/informers/externalversions/analysis/v1alpha1/recommendation.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/analysis/v1alpha1/expansion_generated.go
  pkg/client/listers/analysis/v1alpha1/recommendation.go
  pkg/prediction/OWNERS
  pkg/yarn/OWNERS
  pkg/yarn/controller/OWNERS
Labels: size/XXL, lgtm, approved

#1968 webhook: fix priority admission conflict
  pkg/webhook/pod/mutating/cluster_colocation_profile.go
  pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
Labels: lgtm, approved, size/S

#1943 apis: add Resctrl API
  apis/extension/resctrl.go
  apis/extension/resctrl_test.go
Labels: lgtm, approved, size/L

#1950 chore: fix make docker build xxx
  Makefile
  docker/koordlet.dockerfile
Labels: lgtm, approved, size/S

#1963 scheduler : fix deviceshare plugin of add\remove pod
  pkg/scheduler/plugins/deviceshare/device_resources.go
  pkg/scheduler/plugins/deviceshare/device_resources_test.go
  pkg/scheduler/plugins/deviceshare/nominator.go
  pkg/scheduler/plugins/deviceshare/nominator_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/XL

#1971 Revert "scheduler : fix deviceshare plugin of add\remove pod (#1963)"
  pkg/scheduler/plugins/deviceshare/device_resources.go
  pkg/scheduler/plugins/deviceshare/device_resources_test.go
  pkg/scheduler/plugins/deviceshare/nominator.go
  pkg/scheduler/plugins/deviceshare/nominator_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/XL

#1961 koordlet: record invoke metrics for runtime hook
  pkg/koordlet/metrics/internal_metrics.go
  pkg/koordlet/metrics/metrics_test.go
  pkg/koordlet/metrics/runtime_hook.go
  pkg/koordlet/runtimehooks/hooks/hooks.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
Labels: lgtm, approved, size/L

#1977 scheduler: optimize QueueSort func when Gang and Barepod Coexists
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
Labels: lgtm, approved, size/L
