Repository koordinator-sh/koordinator, pull requests merged in 2025-04, with the labels that each got.

#2386 fix(koordlet):BlkIOReconcile plugin not using WaitForCacheSync method correctly to synchronize
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile_test.go
Labels: size/XS, lgtm, approved

#2397 scheduler: add log for diagnosize
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/plugins/reservation/plugin.go
Labels: lgtm, approved, size/S

#2394 scheduler: add elasticquota ForgetPod, enable lazyreservationrestore for preferred topologyspread
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/pod_handler.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_benchmark_test.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: lgtm, approved, size/L

#2396 chore: update actions runner image to Ubuntu 22.04
  .github/workflows/e2e-k8s-1.22.yaml
  .github/workflows/e2e-k8s-1.24.yaml
  .github/workflows/e2e-k8s-1.28.yaml
  .github/workflows/e2e-k8s-latest.yaml
Labels: size/XS, lgtm, approved

#2390 apis: add default Pending phase when creating reservation
  apis/scheduling/v1alpha1/reservation_types.go
  config/crd/bases/scheduling.koordinator.sh_reservations.yaml
Labels: size/XS, lgtm, approved

#2399 scheduler: reduce loadaware lock overhead, improve reservation args
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1/defaults.go
  pkg/scheduler/apis/config/v1/types.go
  pkg/scheduler/apis/config/v1/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1beta3/defaults.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/pod_assign_cache.go
  pkg/scheduler/plugins/reservation/controller/controller.go
  pkg/scheduler/plugins/reservation/controller/controller_test.go
  pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/plugin.go
Labels: lgtm, approved, size/L

#2406 webhook: add error info when failed to check sub and parent group quo…
  pkg/webhook/elasticquota/quota_topology_check.go
Labels: size/XS, lgtm, approved

#2410 scheduler: support DispenseWithLRNDeviceAllocation
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/reservation.go
Labels: lgtm, approved, size/S

#2005 koordlet: add resctrl qos collector
  pkg/features/koordlet_features.go
  pkg/koordlet/metriccache/metric_resources.go
  pkg/koordlet/metriccache/metric_types.go
  pkg/koordlet/metrics/external_metrics.go
  pkg/koordlet/metrics/resctrl.go
  pkg/koordlet/metricsadvisor/collectors/resctrl/resctrl_collector.go
  pkg/koordlet/metricsadvisor/collectors/resctrl/resctrl_collector_test.go
  pkg/koordlet/metricsadvisor/framework/config.go
  pkg/koordlet/metricsadvisor/framework/config_test.go
  pkg/koordlet/metricsadvisor/plugins_profile.go
  pkg/koordlet/resourceexecutor/resctrl.go
  pkg/koordlet/resourceexecutor/resctrl_test.go
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/resctrl.go
  pkg/koordlet/util/system/resctrl_test.go
  pkg/koordlet/util/system/util_test_tool.go
  pkg/koordlet/util/system/util_test_tool_test.go
Labels: size/XXL, lgtm, approved

#2405 koord-descheduler: add nil check for podMetric in NodeFit of loadaware plugin
  pkg/descheduler/framework/plugins/loadaware/utilization_util.go
Labels: size/XS, lgtm, approved

#2416 scheduler: fix reservation cache leak when terminated and deleted
  pkg/scheduler/plugins/reservation/eventhandler.go
  pkg/scheduler/plugins/reservation/eventhandler_test.go
Labels: lgtm, approved, size/M

#2402 scheduler: Add gcDurationSeconds field to ReservationArgs
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1/defaults.go
  pkg/scheduler/apis/config/v1/types.go
  pkg/scheduler/apis/config/v1/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta3/defaults.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/plugins/reservation/controller/controller.go
  pkg/scheduler/plugins/reservation/controller/controller_test.go
  pkg/scheduler/plugins/reservation/controller/garbage_collection.go
  pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/plugin.go
Labels: lgtm, approved, size/M

#2409 webhook: check quota that only allow max >= used for specific resources
  apis/extension/elastic_quota.go
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: lgtm, approved, size/L

#2421 scheduler: change quota info to rw lock
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
Labels: lgtm, approved, size/M

#2425 scheduler: optimize secondary device well planned
  apis/extension/device_share.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
Labels: lgtm, approved, size/S

#2424 scheduler: avoid string concatenation and podLister in loadaware func…
  pkg/scheduler/plugins/loadaware/helper.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/M
