Repository koordinator-sh/koordinator, pull requests merged in 2025-08, with the labels that each got.

#2501 koordlet: support heterogeneous GPU device reporting
  apis/scheduling/v1alpha1/device_types.go
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.koordinator.sh_devices.yaml
  config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
  config/manager/koordlet.yaml
  pkg/koordlet/metricsadvisor/devices/xpu/collector_xpu.go
  pkg/koordlet/metricsadvisor/devices/xpu/collector_xpu_test.go
  pkg/koordlet/metricsadvisor/plugins_profile.go
  pkg/koordlet/statesinformer/impl/config.go
  pkg/koordlet/statesinformer/impl/states_device_linux.go
  pkg/koordlet/statesinformer/impl/states_device_linux_test.go
  pkg/koordlet/statesinformer/impl/states_device_unsupported.go
  pkg/koordlet/util/device.go
  pkg/koordlet/util/system/config.go
  pkg/koordlet/util/system/config_test.go
Labels: size/XXL, lgtm, approved, area/koordlet

#2573 koordlet: fix collectMetric() panic when nodeSLO is nil
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
Labels: lgtm, approved, size/S

#2576 scheduler: Reservation skips fitsNode to deduplicate with NodeResourceFit
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/L, area/koord-scheduler, concept/reservation

#2575 scheduler: clean expired ReservationAllocated for pods when reservation deleted
  apis/extension/reservation.go
  apis/extension/reservation_test.go
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/reservation/controller/controller.go
  pkg/scheduler/plugins/reservation/controller/controller_test.go
  pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/controller/node_eventhandler.go
  pkg/scheduler/plugins/reservation/controller/pod_eventhandler.go
  pkg/scheduler/plugins/reservation/controller/reservation_eventhandler.go
  pkg/scheduler/plugins/reservation/plugin.go
Labels: lgtm, approved, size/XL, area/koord-scheduler, concept/reservation

#2571 scheduler: support pre-allocation filter
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/plugins/reservation/controller/controller_test.go
  pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
  pkg/scheduler/plugins/reservation/nominator_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/plugin_benchmark_test.go
  pkg/scheduler/plugins/reservation/plugin_test.go
  pkg/scheduler/plugins/reservation/reservation_state.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
  pkg/scheduler/plugins/reservation/transformer_test.go
Labels: size/XXL, lgtm, approved, area/koord-scheduler, concept/reservation

#2577 scheduler: during scheduling, it must consider whether hami-core is installed on the nodes
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/M, area/koord-scheduler, concept/device

#2584 chore: fix typo for RegisterTypeNodeMetadata
  pkg/koordlet/statesinformer/api.go
Labels: size/XS, lgtm, approved

#2586 webhook: fix elasticquota validation error for min > max
  pkg/webhook/elasticquota/quota_topology_check.go
  pkg/webhook/elasticquota/quota_topology_test.go
Labels: size/XS, lgtm, approved

#2583 koordlet: support enhanced group identity for gpu
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
  pkg/koordlet/pleg/watcher_linux_test.go
  pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile_test.go
  pkg/koordlet/qosmanager/plugins/sysreconcile/system_config.go
  pkg/koordlet/qosmanager/plugins/sysreconcile/system_config_test.go
  pkg/koordlet/runtimehooks/runtimehooks_test.go
  pkg/koordlet/statesinformer/impl/states_device_unsupported.go
  pkg/koordlet/util/system/common.go
  pkg/koordlet/util/system/common_linux.go
  pkg/koordlet/util/system/core_sched.go
  pkg/koordlet/util/system/psi_test.go
  pkg/koordlet/util/system/system_file.go
  pkg/koordlet/util/system/system_file_test.go
  pkg/koordlet/util/system/system_resource.go
  pkg/koordlet/util/system/system_resource_test.go
  pkg/koordlet/util/system/util_test_tool_test.go
  pkg/runtimeproxy/server/docker/utils.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler_test.go
  pkg/slo-controller/nodeslo/nodeslo_controller_test.go
  pkg/util/sloconfig/nodeslo_config.go
Labels: lgtm, approved, size/XL

#2589 scheduler: preprocess unmatch reservation's allocated
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/frameworkext/reservation_info_test.go
  pkg/scheduler/plugins/reservation/cache_test.go
  pkg/scheduler/plugins/reservation/scoring_test.go
  pkg/scheduler/plugins/reservation/transformer.go
Labels: lgtm, approved, size/L

#2588 manager: support batch resource limit of nodeCapacity
  apis/configuration/slo_controller_config.go
  apis/configuration/zz_generated.deepcopy.go
  pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins/util/util.go
  pkg/util/resource.go
  pkg/util/resource_test.go
  pkg/util/sloconfig/colocation_config.go
  pkg/util/sloconfig/colocation_config_test.go
  pkg/webhook/cm/plugins/sloconfig/colocation_checker_test.go
Labels: lgtm, approved, size/L
