Repository koordinator-sh/koordinator, pull requests merged in 2025-06, with the labels that each got.

#2466 scheduler: add FG validatingPodDeviceResource and EnableSyncGPUShared…
  pkg/features/features.go
  pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin_test.go
  pkg/webhook/pod/validating/verify_device_resource.go
  pkg/webhook/pod/validating/verify_device_resource_test.go
Labels: lgtm, approved, size/L

#2465 scheduler: Add hook plugins logic in ReplaceQuotas and OnQuotaUpdate methods of ElasticQuota plugin.
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/hook_plugin.go
  pkg/scheduler/plugins/elasticquota/core/hook_plugin_test.go
  pkg/scheduler/plugins/elasticquota/hook_plugin_test.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: lgtm, approved, size/L

#2468 scheduler: make loadaware debuggable
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/service.go
  pkg/scheduler/plugins/loadaware/service_test.go
Labels: lgtm, approved, size/L

#2469 scheduler: fix data race issues in GroupQuotaManager#IsQuotaUpdated and MockHookPlugin
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/hook_plugin.go
  pkg/scheduler/plugins/elasticquota/core/hook_plugin_test.go
  pkg/scheduler/plugins/elasticquota/hook_plugin_test.go
Labels: lgtm, approved, size/L

#2472 manager: reconcile colocation-profile if enabled
  apis/extension/cluster_colocation_profile.go
  pkg/controller/colocationprofile/colocationprofile_controller.go
  pkg/controller/colocationprofile/colocationprofile_controller_test.go
  pkg/controller/colocationprofile/colocationprofile_util_test.go
Labels: lgtm, approved, size/M

#2423 proposal: heterogeneous GPU device reporting
  docs/images/GPU-device-reporting.svg
  docs/proposals/koordlet/20250425-heterogeneous-GPU-device-reporting.md
Labels: lgtm, approved, size/L

#2467 scheduler: fine-grained device scheduling support Huawei Ascend NPU (full card)
  apis/extension/device_share.go
  pkg/features/features.go
  pkg/koordlet/statesinformer/impl/states_device_linux.go
  pkg/koordlet/statesinformer/impl/states_device_linux_test.go
  pkg/scheduler/plugins/deviceshare/allocator_gpu_helper.go
  pkg/scheduler/plugins/deviceshare/device_plugin_adapter.go
  pkg/scheduler/plugins/deviceshare/device_plugin_adapter_test.go
  pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
  pkg/scheduler/plugins/deviceshare/devicehandler_gpu_test.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
  pkg/scheduler/plugins/deviceshare/utils_test.go
  pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin.go
  pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin_test.go
  pkg/slo-controller/noderesource/plugins/gpudeviceresource/utils.go
Labels: size/XXL, lgtm, approved

#2200 koord-descheduler: fix descheduler object limiter with multiple profiles
  pkg/descheduler/controllers/migration/controller.go
  pkg/descheduler/controllers/migration/evict.go
Labels: lgtm, approved, size/S

#2473 scheduler: fix quota webhook panic
  pkg/webhook/elasticquota/quota_topology.go
Labels: size/XS, lgtm, approved

#2476 scheduler: fix PreBind Patch for pods with same name but different uid
  pkg/scheduler/plugins/defaultprebind/plugin_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/L

#2478 scheduler: reject schedulerName unmatched binding
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory_test.go
  pkg/scheduler/frameworkext/framework_extender_test.go
Labels: lgtm, approved, size/L

#2479 koordlet: fix avg not being collected in AggregatedUsage
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
  pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
Labels: size/XS, lgtm, approved

#2444 chore: fix wrong event type
  pkg/quota-controller/profile/profile_controller.go
  pkg/slo-controller/config/colocation_cm_event_handler.go
  pkg/slo-controller/noderesource/plugins/cpunormalization/configmap_event_handler.go
  pkg/slo-controller/noderesource/plugins/resourceamplification/configmap_event_handler.go
  pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
Labels: lgtm, approved, size/S

#2482 scheduler: fix nodeName filter fail
  pkg/scheduler/plugins/coscheduling/core/gang.go
Labels: size/XS, lgtm, approved

#2483 koordlet: fix resctrl metric releated flags's comment.
  pkg/koordlet/metricsadvisor/framework/config.go
Labels: size/XS, lgtm, approved

#2485 scheduler: revise PreBind safe Patch
  pkg/scheduler/plugins/defaultprebind/plugin.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/XL

#2487 scheduler: support leave allocate logic to kubelet
  pkg/scheduler/plugins/deviceshare/plugin.go
Labels: size/XS, lgtm, approved

#2484 fix: GetLocalStorageInfo maybe hang
  pkg/koordlet/util/storageinfo.go
Labels: size/XS, lgtm, approved

#2494 scheduler: set PodGroup's OccupiedBy field correctly
  pkg/scheduler/plugins/coscheduling/controller/podgroup.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
Labels: lgtm, approved, size/M

#2497 scheduler: use RWMutex instead of Mutex
  pkg/scheduler/plugins/reservation/controller/controller.go
  pkg/scheduler/plugins/reservation/controller/pod_eventhandler.go
Labels: lgtm, approved, size/S
