Repository koordinator-sh/koordinator, pull requests merged in 2025-09, with the labels that each got.

#2599 koordlet: fix typo and add memory-ratio resource for buildXPUDevice()
  pkg/koordlet/statesinformer/impl/states_device_linux.go
  pkg/koordlet/statesinformer/impl/states_device_linux_test.go
Labels: lgtm, approved, size/S

#2600 scheduler: don't invoke SnapshotSharedLister in parallizer
  pkg/scheduler/plugins/reservation/transformer.go
Labels: size/XS, lgtm, approved

#2601 scheduler: add questionedObjectKet and topologyKeyToExplain
  apis/extension/schedule_explanation.go
  pkg/util/transformer/pod_transformer.go
  pkg/util/transformer/pod_transformer_test.go
Labels: lgtm, approved, size/L

#2597 koordlet: fix koordlet panic randomly,caused by node info not ready
  pkg/koordlet/statesinformer/impl/states_node.go
  pkg/koordlet/statesinformer/impl/states_node_test.go
Labels: lgtm, approved, size/M

#2603 scheduler: loadaware support dominantResourceWeight
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1/defaults.go
  pkg/scheduler/apis/config/v1/types.go
  pkg/scheduler/apis/config/v1/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta3/defaults.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
Labels: lgtm, approved, size/M

#2619 koordlet: fix typo and update xpu condition/partition
  pkg/koordlet/statesinformer/impl/states_device_linux.go
  pkg/koordlet/statesinformer/impl/states_device_linux_test.go
Labels: lgtm, approved, size/L

#2627 scheduler: remove unused apis/util
  apis/thirdparty/scheduler-plugins/pkg/util/podgroup.go
  apis/thirdparty/scheduler-plugins/pkg/util/resource.go
  pkg/scheduler/plugins/elasticquota/controller.go
Labels: lgtm, approved, size/L

#2632 scheduler: support customize preemption diagnosis
  pkg/scheduler/frameworkext/schedule_diagnosis.go
  pkg/scheduler/frameworkext/schedule_diagnosis_test.go
Labels: lgtm, approved, size/M

#2634 scheduler: fill scheduleDiagnosis when pod or gang
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/framework_extender_factory_test.go
  pkg/scheduler/frameworkext/schedule_diagnosis.go
  pkg/scheduler/frameworkext/schedule_diagnosis_test.go
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
Labels: lgtm, approved, size/L

#2636 koordlet: fix partition in buildXPUDeviceAnnotations()
  pkg/koordlet/statesinformer/impl/states_device_linux.go
Labels: size/XS, lgtm, approved

#2642 scheduler: enhance framework extender for multi-scheduler
  pkg/features/scheduler_features.go
  pkg/scheduler/frameworkext/eventhandlers/event_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_test.go
  pkg/scheduler/frameworkext/interface.go
Labels: lgtm, approved, size/L

#2644 device-daemon: add release
  .github/workflows/release.yml
Labels: size/XS, lgtm, approved
