Repository koordinator-sh/koordinator, pull requests merged in 2025-05, with the labels that each got.

#2428 scheduler: optimize filterNodeDevice
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/utils.go
Labels: lgtm, approved, size/M

#2431 scheduler: correct secondaryDeviceNotWellPlanned metric
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/deviceshare/device_cache.go
Labels: lgtm, approved, size/M

#2434 chore: update EnableRuntimeQuota param description
  pkg/scheduler/apis/config/types.go
Labels: size/XS, lgtm, approved

#2436 scheduler: fix shared gpu binpack bug
  pkg/scheduler/plugins/deviceshare/allocator_gpu.go
  pkg/scheduler/plugins/deviceshare/allocator_gpu_test.go
Labels: lgtm, approved, size/M

#2435 descheduler: return the unmatched cases first
  pkg/descheduler/pod/pods.go
Labels: size/XS, lgtm, approved

#2439 chore(statesInformer): remove useless code and use generateQueryDuration() func in collectMetric() func
  pkg/koordlet/statesinformer/impl/states_node.go
  pkg/koordlet/statesinformer/impl/states_nodemetric.go
Labels: lgtm, approved, size/M

#2441 scheduler: support multi-scheduler
  apis/extension/multi_scheduler.go
  pkg/util/transformer/pod_transformer.go
Labels: lgtm, approved, size/M

#2442 scheduler: fix CheckParentQuota bug when multiquotatree
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_helper.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
Labels: lgtm, approved, size/S

#2448 e2e: disable LoadAware Filter to fix flaky test
  config/manager/scheduler-config.yaml
Labels: size/XS, lgtm, approved

#2417 scheduler: abstract nextPod and gang inplements it
  config/manager/scheduler-config.yaml
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/framework_extender_factory_test.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/core_test.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache.go
  pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
  pkg/scheduler/plugins/coscheduling/core/gang_context.go
  pkg/scheduler/plugins/coscheduling/core/gang_summary.go
  pkg/scheduler/plugins/coscheduling/core/gang_test.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup_test.go
  pkg/scheduler/plugins/coscheduling/coscheduling.go
  pkg/scheduler/plugins/coscheduling/coscheduling_test.go
  pkg/scheduler/plugins/coscheduling/plugin_service_test.go
Labels: size/XXL, lgtm, approved

#2437 chore: qos manager removes repeat goroutine
  pkg/koordlet/qosmanager/qosmanager.go
Labels: size/XS, lgtm, approved

#2415 scheduler: add QuotaHookPlugin for extensible resource limiting in ElasticQuota plugin
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1/types.go
  pkg/scheduler/apis/config/v1/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/elasticquota/controller.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/hook_plugin.go
  pkg/scheduler/plugins/elasticquota/core/hook_plugin_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/hook_plugin_test.go
  pkg/scheduler/plugins/elasticquota/plugin.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: size/XXL, lgtm, approved

#2449 scheduler: add ElasticQuota arg to control preemption of default quota (#2413)
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1/defaults.go
  pkg/scheduler/apis/config/v1/types.go
  pkg/scheduler/apis/config/v1/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1beta3/defaults.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
  pkg/scheduler/plugins/elasticquota/preempt.go
Labels: lgtm, approved, size/M

#2453 scheduler: fix calFreeWithPreemptible modify nodeDevice
  pkg/scheduler/plugins/deviceshare/device_cache.go
  pkg/scheduler/plugins/deviceshare/device_cache_test.go
Labels: lgtm, approved, size/M

#2452 scheduler: allow to disable Controllers
  pkg/scheduler/frameworkext/controllers.go
  pkg/scheduler/frameworkext/debug.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
Labels: lgtm, approved, size/M

#2454 scheduler: gpuSharedPod doesn't fit secondaryDeviceWellPlanned
  pkg/scheduler/plugins/deviceshare/device_allocator.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
  pkg/scheduler/plugins/deviceshare/utils.go
Labels: lgtm, approved, size/M

#2426 chore: refactor ValidateNodeNUMAResourceArgs func and add miss NUMAScoringStrategy validate
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
  pkg/scheduler/plugins/nodenumaresource/plugin.go
Labels: lgtm, approved, size/S

#2427 chore: rename validateEstimatedResourceThresholds -> validateEstimatedScalingFactors
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
Labels: lgtm, approved, size/S

#2459 koordlet: support extension controllers
  cmd/koordlet/options/options.go
  pkg/koordlet/extension/interface.go
  pkg/koordlet/koordlet.go
Labels: lgtm, approved, size/M

#2461 scheduler: run pod-update hooks for elastic-quota regardless of whether used resources have changed
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/hook_plugin_test.go
Labels: size/XS, lgtm, approved
