Repository koordinator-sh/koordinator, pull requests merged in 2025-07, with the labels that each got.

#2504 scheduler: introduce gpu minors annotation to device plugin adapter
  pkg/scheduler/plugins/deviceshare/device_plugin_adapter.go
  pkg/scheduler/plugins/deviceshare/device_plugin_adapter_test.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/L

#2505 chores: update community meeting information
  README-zh_CN.md
  README.md
Labels: size/XS, lgtm, approved

#2506 manager: fix typo for colocationprofile
  apis/config/v1alpha1/cluster_colocation_profile_types.go
  config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
Labels: size/XS, lgtm, approved

#2509 scheduler: revise preEnqueue RepresentativePod
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang.go
  pkg/scheduler/plugins/coscheduling/core/gang_context.go
  pkg/scheduler/plugins/coscheduling/core/ganggroup.go
Labels: lgtm, approved, size/M

#2512 scheduler: mark gangGroupScheduling with startTime and fix pod status
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/plugins/coscheduling/core/core.go
  pkg/scheduler/plugins/coscheduling/core/gang_context.go
Labels: lgtm, approved, size/S

#2518 scheduler: fix unhandled timeout in SchedulerMonitor
  pkg/scheduler/frameworkext/scheduler_monitor.go
Labels: lgtm, approved, size/M

#2514 koord-descheduler: use RWMutex instead of use Mutex
  pkg/descheduler/evictions/eviction_limiter.go
  pkg/descheduler/evictions/eviction_limiter_test.go
  pkg/descheduler/evictions/evictions.go
Labels: lgtm, approved, size/L, area/koord-descheduler

#2520 Update descheduler approvers
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#2522 colocationprofile: support namespace selector for ClusterColocationProfile in controller
  pkg/controller/colocationprofile/colocationprofile_util.go
  pkg/controller/colocationprofile/colocationprofile_util_test.go
Labels: lgtm, approved, size/L, area/koord-manager

#2527 scheduler: add loadaware plugins Aggregated Args Validate
  pkg/scheduler/apis/config/validation/validation_pluginargs.go
Labels: lgtm, approved, size/M

#2474 proposal: network topology aware scheduling
  docs/images/networktopo-1.png
  docs/images/networktopo-2-dp-and-pp.png
  docs/images/networktopo-3-demo1.png
  docs/images/networktopo-4-cluster.png
  docs/images/networktopo-5-framework.png
  docs/images/networktopo-6-afterprefilter.png
  docs/images/networktopo-7-postfilter.png
  docs/images/networktopo-8-spine-leaf.png
  docs/images/networktopo-9-topo-gen.png
  docs/images/networktopo-preempt.png
  docs/images/networktopology_firstpod.svg
  docs/images/networktopology_nextpod.svg
  docs/images/pp_over_dp.jpg
  docs/images/ppgroup_placement.jpg
  docs/images/topology_final_placement.jpg
  docs/images/topology_offerslot_candidatenode.jpg
  docs/proposals/scheduling/20250611-networktopology-aware-scheduling.md
Labels: lgtm, approved, size/XL, area/koord-scheduler, concept/gang

#2532 scheduler: fix flaky test
  pkg/scheduler/plugins/deviceshare/service_test.go
Labels: size/XS, lgtm, approved

#2531 scheduler: loadaware support force estimated duration and other improvements
  apis/extension/load_aware.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1/types.go
  pkg/scheduler/apis/config/v1/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/v1beta3/types.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
  pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
  pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/scheduler/plugins/loadaware/pod_assign_cache.go
  pkg/scheduler/plugins/loadaware/pod_assign_cache_test.go
  pkg/scheduler/plugins/loadaware/service_test.go
Labels: lgtm, approved, size/L

#2534 remove inactive approve to smooth review process
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#2462 koord-manager: support enhanced validation for pod
  cmd/koord-manager/main.go
  pkg/features/features.go
  pkg/webhook/pod/validating/pod_enhanced_validator.go
  pkg/webhook/pod/validating/pod_enhanced_validator_test.go
  pkg/webhook/pod/validating/validating_handler.go
  pkg/webhook/pod/validating/validating_handler_test.go
  pkg/webhook/pod/validating/webhooks.go
Labels: lgtm, approved, size/XL, area/koord-manager

#2544 scheduler: fix missing Unreserve when ResizePod=true
  pkg/scheduler/frameworkext/framework_extender.go
  pkg/scheduler/frameworkext/framework_extender_factory.go
  pkg/scheduler/frameworkext/interface.go
  pkg/scheduler/plugins/deviceshare/plugin.go
Labels: lgtm, approved, size/M

#2533 scheduler: add ReservationResourceAllocated metrics in reservation controller
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/reservation/controller/controller.go
  pkg/scheduler/plugins/reservation/controller/controller_test.go
Labels: lgtm, approved, size/L, area/koord-scheduler, concept/reservation

#2551 cmd: refactor SecureServing.Serve return in scheduler and descheduler
  cmd/koord-descheduler/app/server.go
  cmd/koord-scheduler/app/server.go
Labels: lgtm, approved, size/M

#2554 scheduler: move DevicePluginAdaption to correct feature gates
  pkg/features/features.go
  pkg/features/scheduler_features.go
  pkg/scheduler/plugins/deviceshare/plugin.go
  pkg/scheduler/plugins/deviceshare/plugin_test.go
Labels: lgtm, approved, size/S

#2543 scheduler: handle cache.DeletedFinalStateUnknown event in quota controller handler
  pkg/scheduler/plugins/elasticquota/node_handler.go
  pkg/scheduler/plugins/elasticquota/quota_handler.go
Labels: lgtm, approved, size/S, area/koord-scheduler, concept/quota

#2555 scheduler: loadaware fix cache for pod conditions changed
  pkg/scheduler/plugins/loadaware/load_aware.go
  pkg/scheduler/plugins/loadaware/load_aware_test.go
  pkg/scheduler/plugins/loadaware/pod_assign_cache.go
  pkg/scheduler/plugins/loadaware/pod_assign_cache_test.go
  pkg/scheduler/plugins/loadaware/service_test.go
Labels: lgtm, approved, size/XL, area/koord-scheduler
