Repository koordinator-sh/koordinator, pull requests merged in 2025-03, with the labels that each got.

#2353 fix(scheduler/api): register missing NodeResourcesFitPlusArgs in v1 c…
  pkg/scheduler/apis/config/v1/register.go
Labels: lgtm, approved

#2356 scheduler: optimize nodeNUMAResource performance
  pkg/scheduler/plugins/nodenumaresource/reservation.go
  pkg/scheduler/plugins/nodenumaresource/resource_manager.go
Labels: lgtm, approved

#2355 scheduler: fix numaNodeResource not reserve cpu
  pkg/scheduler/plugins/nodenumaresource/topology_options.go
  pkg/scheduler/plugins/nodenumaresource/topology_options_test.go
Labels: lgtm, approved

#2357 koordlet: skip reconcile containers in runtime hooks for kata pods
  pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
  pkg/koordlet/runtimehooks/protocol/filters.go
  pkg/koordlet/runtimehooks/protocol/filters_test.go
  pkg/koordlet/runtimehooks/reconciler/reconciler.go
  pkg/koordlet/util/pod.go
Labels: lgtm, approved

#2351 scheduler: inplace update quota when quota parent change
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
  pkg/scheduler/plugins/elasticquota/plugin_test.go
  pkg/scheduler/plugins/elasticquota/quota_handler_test.go
Labels: lgtm, approved

#2358 scheduler: update quota tree when quota spec changed
  pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
  pkg/scheduler/plugins/elasticquota/core/quota_info.go
Labels: lgtm, approved

#2366 scheduler: pre-calculate reservation info for perf
  pkg/scheduler/frameworkext/reservation_info.go
  pkg/scheduler/frameworkext/reservation_info_test.go
  pkg/scheduler/plugins/reservation/cache_test.go
  pkg/scheduler/plugins/reservation/plugin.go
  pkg/scheduler/plugins/reservation/scoring_test.go
Labels: lgtm, approved, size/L

#2369 koordlet: BECPUSuppress supports cpuSuppressMinPercent
  apis/slo/v1alpha1/nodeslo_types.go
  apis/slo/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slo.koordinator.sh_nodeslos.yaml
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
  pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress_test.go
Labels: lgtm, approved, size/L

#2372 scheduler: make Activate invokable by handle
  pkg/scheduler/frameworkext/scheduler_adapter.go
Labels: size/XS, lgtm, approved

#2362 chore: move SetReservationUnschedulable func to util package
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
  pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
  pkg/util/reservation/reservation.go
  pkg/util/reservation/reservation_test.go
Labels: lgtm, approved, size/XL

#2382 feature(GCmetrics): support GCHistogramVec for util package
  pkg/util/metrics/expire_metric.go
  pkg/util/metrics/expire_metric_test.go
Labels: lgtm, approved, size/M
